

<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>Friendly tracebacks - markdown_docs format &mdash; Friendly tracebacks 0.2.8a documentation</title>
  

  
  <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />

  
  
  
  

  
  <!--[if lt IE 9]>
    <script src="_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
    
      <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
        <script src="_static/jquery.js"></script>
        <script src="_static/underscore.js"></script>
        <script src="_static/doctools.js"></script>
        <script src="_static/language_data.js"></script>
    
    <script type="text/javascript" src="_static/js/theme.js"></script>

    
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="Syntax errors - markdown_docs format" href="tracebacks_syntax_markdown.html" />
    <link rel="prev" title="Comparison between Python versions: SyntaxErrors" href="compare.html" /> 
</head>

<body class="wy-body-for-nav">

   
  <div class="wy-grid-for-nav">
    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
          

          
            <a href="index.html" class="icon icon-home" alt="Documentation Home"> Friendly tracebacks
          

          
          </a>

          
            
            
              <div class="version">
                0.2.8a
              </div>
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        
        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
              
            
            
              <p class="caption"><span class="caption-text">Begin here</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="usage.html">Installation and basic usage</a></li>
<li class="toctree-l1"><a class="reference internal" href="repl.html">Console basics</a></li>
<li class="toctree-l1"><a class="reference internal" href="editor.html">Using with an editor or IDE</a></li>
<li class="toctree-l1"><a class="reference internal" href="mu.html">Using with Mu</a></li>
<li class="toctree-l1"><a class="reference internal" href="thonny.html">Using with Thonny</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks.html">Multiple tracebacks</a></li>
</ul>
<p class="caption"><span class="caption-text">Thoughts on design</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="design.html">Some thoughts on the design of Friendly-traceback</a></li>
<li class="toctree-l1"><a class="reference internal" href="themes.html">Themes and colours</a></li>
</ul>
<p class="caption"><span class="caption-text">Use in your project</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="api.html">Public API</a></li>
<li class="toctree-l1"><a class="reference internal" href="lies.html">Learn to lie</a></li>
<li class="toctree-l1"><a class="reference internal" href="formatter.html">Custom formatter</a></li>
<li class="toctree-l1"><a class="reference internal" href="usage_adv.html">Other details for advanced users</a></li>
<li class="toctree-l1"><a class="reference internal" href="plugins.html">Editor plugins</a></li>
</ul>
<p class="caption"><span class="caption-text">Contribute</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="suggest.html">Suggest an addition</a></li>
<li class="toctree-l1"><a class="reference internal" href="adding_exception.html">Developer: Add a new Exception case</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_error.html">Developer: Add a new SyntaxError case</a></li>
<li class="toctree-l1"><a class="reference internal" href="translation_notes.html">Notes on translations - using gettext</a></li>
</ul>
<p class="caption"><span class="caption-text">All the tracebacks!</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="all_tb.html">Why all the tracebacks?</a></li>
<li class="toctree-l1"><a class="reference internal" href="known.html">Generic information about various exceptions</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.6.html">Friendly tracebacks - Python 3.6 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.6.html">SyntaxError - Python 3.6 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.7.html">Friendly tracebacks - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.7.html">SyntaxError - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.8.html">Friendly tracebacks - Python 3.8 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.8.html">SyntaxError - Python 3.8 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.9.html">Friendly tracebacks - Python 3.9 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.9.html">SyntaxError - Python 3.9 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.10.html">Friendly tracebacks - Python 3.10 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.10.html">SyntaxError - Python 3.10 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="compare_exceptions.html">Comparing Exception messages between Python versions</a></li>
<li class="toctree-l1"><a class="reference internal" href="compare.html">Comparison between Python versions: SyntaxErrors</a></li>
</ul>
<p class="caption"><span class="caption-text">Markdown examples</span></p>
<ul class="current">
<li class="toctree-l1 current"><a class="current reference internal" href="#">Friendly tracebacks - markdown_docs format</a><ul>
<li class="toctree-l2"><a class="reference internal" href="#arithmeticerror">ArithmeticError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-9-of-file-tests-runtime-test-arithmetic-error-py">Exception raised on line 9 of file TESTS:\runtime\test_arithmetic_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-class-attribute">AttributeError - class attribute</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-36-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 36 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-typo-in-object-attribute">AttributeError - typo in object attribute</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-52-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 52 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-using-builtin">AttributeError - using builtin</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-68-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 68 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-use-synonym">AttributeError - use synonym</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-84-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 84 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-typo-in-module-attribute">AttributeError - typo in module attribute</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-113-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 113 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-shadowning-stdlib-module">AttributeError - shadowning stdlib module</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-134-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 134 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-using-instead-of">AttributeError - using . instead of ,</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-171-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 171 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#filenotfounderror">FileNotFoundError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-file-not-found-error-py">Exception raised on line 6 of file TESTS:\runtime\test_file_not_found_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#importerror">ImportError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-import-error-py">Exception raised on line 6 of file TESTS:\runtime\test_import_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#keyerror">KeyError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-7-of-file-tests-runtime-test-key-error-py">Exception raised on line 7 of file TESTS:\runtime\test_key_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#lookuperror">LookupError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-10-of-file-tests-runtime-test-lookup-error-py">Exception raised on line 10 of file TESTS:\runtime\test_lookup_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#indexerror-short-tuple">IndexError - short tuple</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-8-of-file-tests-runtime-test-index-error-py">Exception raised on line 8 of file TESTS:\runtime\test_index_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#indexerror-long-list">IndexError - long list</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-22-of-file-tests-runtime-test-index-error-py">Exception raised on line 22 of file TESTS:\runtime\test_index_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#modulenotfounderror">ModuleNotFoundError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-module-not-found-error-py">Exception raised on line 6 of file TESTS:\runtime\test_module_not_found_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror-1">NameError - 1</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-name-error-py">Exception raised on line 6 of file TESTS:\runtime\test_name_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror-2">NameError - 2</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-20-of-file-tests-runtime-test-name-error-py">Exception raised on line 20 of file TESTS:\runtime\test_name_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror-3">NameError - 3</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-35-of-file-tests-runtime-test-name-error-py">Exception raised on line 35 of file TESTS:\runtime\test_name_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror-4">NameError - 4</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-48-of-file-tests-runtime-test-name-error-py">Exception raised on line 48 of file TESTS:\runtime\test_name_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#overflowerror">OverflowError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-overflow-error-py">Exception raised on line 6 of file TESTS:\runtime\test_overflow_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#recursionerror">RecursionError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#execution-stopped-on-line-8-of-file-tests-runtime-test-recursion-error-py">Execution stopped on line 8 of file TESTS:\runtime\test_recursion_error.py.</a></li>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-recursion-error-py">Exception raised on line 6 of file TESTS:\runtime\test_recursion_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-1-concatenate-two-different-types">TypeError - 1: concatenate two different types</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-36-of-file-tests-runtime-test-type-error-py">Exception raised on line 36 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-2-unsupported-operand-type-s-for">TypeError - 2: unsupported operand type(s) for +=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-66-of-file-tests-runtime-test-type-error-py">Exception raised on line 66 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-3-unsupported-operand-type-s-for">TypeError - 3: unsupported operand type(s) for -=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-94-of-file-tests-runtime-test-type-error-py">Exception raised on line 94 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-4-unsupported-operand-type-s-for">TypeError - 4: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">*=</span></code></a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-122-of-file-tests-runtime-test-type-error-py">Exception raised on line 122 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-5-unsupported-operand-type-s-for">TypeError - 5: unsupported operand type(s) for //=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-174-of-file-tests-runtime-test-type-error-py">Exception raised on line 174 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-6-unsupported-operand-type-s-for">TypeError - 6: unsupported operand type(s) for &amp;=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-202-of-file-tests-runtime-test-type-error-py">Exception raised on line 202 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-7-unsupported-operand-type-s-for">TypeError - 7: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">**=</span></code></a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-230-of-file-tests-runtime-test-type-error-py">Exception raised on line 230 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-8-unsupported-operand-type-s-for">TypeError - 8: unsupported operand type(s) for &gt;&gt;=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-258-of-file-tests-runtime-test-type-error-py">Exception raised on line 258 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-9-unsupported-operand-type-s-for">TypeError - 9: unsupported operand type(s) for &#64;=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-286-of-file-tests-runtime-test-type-error-py">Exception raised on line 286 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-10-comparison-between-incompatible-types">TypeError - 10: comparison between incompatible types</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-302-of-file-tests-runtime-test-type-error-py">Exception raised on line 302 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-11-bad-operand-type-for-unary">TypeError - 11: bad operand type for unary +</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-352-of-file-tests-runtime-test-type-error-py">Exception raised on line 352 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-12-object-does-not-support-item-assignment">TypeError - 12: object does not support item assignment</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-370-of-file-tests-runtime-test-type-error-py">Exception raised on line 370 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-13-wrong-number-of-positional-arguments">TypeError - 13: wrong number of positional arguments</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-402-of-file-tests-runtime-test-type-error-py">Exception raised on line 402 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-14-missing-positional-arguments">TypeError - 14: missing positional arguments</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-421-of-file-tests-runtime-test-type-error-py">Exception raised on line 421 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-15-list-object-is-not-callable">TypeError - 15: list object is not callable</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-456-of-file-tests-runtime-test-type-error-py">Exception raised on line 456 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-16-exception-derived-from-baseexception">TypeError - 16: exception derived from BaseException</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-481-of-file-tests-runtime-test-type-error-py">Exception raised on line 481 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-17-can-t-multiply-sequence-by-non-int">TypeError - 17: can’t multiply sequence by non-int</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-550-of-file-tests-runtime-test-type-error-py">Exception raised on line 550 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-18-object-cannot-be-interpreted-as-an-integer">TypeError - 18: object cannot be interpreted as an integer</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-598-of-file-tests-runtime-test-type-error-py">Exception raised on line 598 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#unboundlocalerror-1-missing-global">UnboundLocalError - 1: missing global</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#execution-stopped-on-line-27-of-file-tests-runtime-test-unbound-local-error-py">Execution stopped on line 27 of file TESTS:\runtime\test_unbound_local_error.py.</a></li>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-9-of-file-tests-runtime-test-unbound-local-error-py">Exception raised on line 9 of file TESTS:\runtime\test_unbound_local_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#unboundlocalerror-2-missing-nonlocal">UnboundLocalError - 2: missing nonlocal</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#execution-stopped-on-line-48-of-file-tests-runtime-test-unbound-local-error-py">Execution stopped on line 48 of file TESTS:\runtime\test_unbound_local_error.py.</a></li>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-18-of-file-tests-runtime-test-unbound-local-error-py">Exception raised on line 18 of file TESTS:\runtime\test_unbound_local_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#unknown-exception">Unknown exception</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-10-of-file-tests-runtime-test-unknown-error-py">Exception raised on line 10 of file TESTS:\runtime\test_unknown_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#zerodivisionerror-1">ZeroDivisionError - 1</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-zero-division-error-py">Exception raised on line 6 of file TESTS:\runtime\test_zero_division_error.py.</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#zerodivisionerror-2">ZeroDivisionError - 2</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#exception-raised-on-line-21-of-file-tests-runtime-test-zero-division-error-py">Exception raised on line 21 of file TESTS:\runtime\test_zero_division_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_syntax_markdown.html">Syntax errors - markdown_docs format</a></li>
</ul>
<p class="caption"><span class="caption-text">En français</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_fr.html"> Friendly tracebacks - en Français</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_fr.html"> Friendly SyntaxError tracebacks - en Français</a></li>
</ul>

            
          
        </div>
        
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="index.html">Friendly tracebacks</a>
        
      </nav>


      <div class="wy-nav-content">
        
        <div class="rst-content style-external-links">
        
          















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">
    
      <li><a href="index.html" class="icon icon-home"></a> &raquo;</li>
        
      <li>Friendly tracebacks - markdown_docs format</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
            
            <a href="_sources/tracebacks_markdown.md.txt" rel="nofollow"> View page source</a>
          
        
      </li>
    
  </ul>

  
  <div class="rst-breadcrumbs-buttons" role="navigation" aria-label="breadcrumb navigation">
      
        <a href="tracebacks_syntax_markdown.html" class="btn btn-neutral float-right" title="Syntax errors - markdown_docs format" accesskey="n">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="compare.html" class="btn btn-neutral float-left" title="Comparison between Python versions: SyntaxErrors" accesskey="p"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
  </div>
  
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <div class="section" id="friendly-tracebacks-markdown-docs-format">
<h1>Friendly tracebacks - markdown_docs format<a class="headerlink" href="#friendly-tracebacks-markdown-docs-format" title="Permalink to this headline">¶</a></h1>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The content of this page is generated by running
trb_english_markdown.py located in the <code class="docutils literal notranslate"><span class="pre">tests/</span></code> directory.
This needs to be done explicitly, independently of updating the
documentation using Sphinx.
</p>
</div><p>Friendly-traceback version: 0.2.8a
Python version: 3.8.4</p>
<hr class="docutils" />
<div class="section" id="arithmeticerror">
<h2>ArithmeticError<a class="headerlink" href="#arithmeticerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_arithmetic_error.py&quot;</span>, line <span class="m">9</span>, in <span class="n">test_arithmetic_error</span>
    <span class="k">raise</span> <span class="ne">ArithmeticError</span><span class="p">(</span><span class="s1">&#39;error&#39;</span><span class="p">)</span>
<span class="gr">ArithmeticError</span>: <span class="n">error</span>
</pre></div>
</div>
<p><code class="docutils literal notranslate"><span class="pre">ArithmeticError</span></code> is the base class for those built-in exceptions
that are raised for various arithmetic errors.
It is unusual that you are seeing this exception;
normally, a more specific exception should have been raised.</p>
<div class="section" id="exception-raised-on-line-9-of-file-tests-runtime-test-arithmetic-error-py">
<h3>Exception raised on line 9 of file TESTS:\runtime\test_arithmetic_error.py.<a class="headerlink" href="#exception-raised-on-line-9-of-file-tests-runtime-test-arithmetic-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">7</span><span class="p">:</span>         <span class="c1"># Usually, a subclass such as ZeroDivisionError, etc., would</span>
        <span class="mi">8</span><span class="p">:</span>         <span class="c1"># likely be raised.</span>
    <span class="o">--&gt;</span> <span class="mi">9</span><span class="p">:</span>         <span class="k">raise</span> <span class="ne">ArithmeticError</span><span class="p">(</span><span class="s1">&#39;error&#39;</span><span class="p">)</span>
       <span class="mi">10</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-class-attribute">
<h2>AttributeError - class attribute<a class="headerlink" href="#attributeerror-class-attribute" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">36</span>, in <span class="n">test_generic</span>
    <span class="n">a</span><span class="o">.</span><span class="n">x</span>  <span class="c1"># Testing instance</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;A&#39; object has no attribute &#39;x&#39;</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>The object <code class="docutils literal notranslate"><span class="pre">a</span></code> has no attribute named <code class="docutils literal notranslate"><span class="pre">x</span></code>.</p>
<div class="section" id="exception-raised-on-line-36-of-file-tests-runtime-test-attribute-error-py">
<h3>Exception raised on line 36 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-36-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">34</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
       <span class="mi">35</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="n">A</span><span class="p">()</span>
    <span class="o">--&gt;</span><span class="mi">36</span><span class="p">:</span>         <span class="n">a</span><span class="o">.</span><span class="n">x</span>  <span class="c1"># Testing instance</span>
       <span class="mi">37</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">A</span> <span class="nb">object</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_attribute_error.test_generic</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-typo-in-object-attribute">
<h2>AttributeError - typo in object attribute<a class="headerlink" href="#attributeerror-typo-in-object-attribute" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">52</span>, in <span class="n">test_object_attribute_typo</span>
    <span class="n">a</span><span class="o">.</span><span class="n">appendh</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;list&#39; object has no attribute &#39;appendh&#39;</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">append</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>Perhaps you meant to write <code class="docutils literal notranslate"><span class="pre">a.append</span></code> instead of <code class="docutils literal notranslate"><span class="pre">a.appendh</span></code></p>
<div class="section" id="exception-raised-on-line-52-of-file-tests-runtime-test-attribute-error-py">
<h3>Exception raised on line 52 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-52-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">50</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
       <span class="mi">51</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">52</span><span class="p">:</span>         <span class="n">a</span><span class="o">.</span><span class="n">appendh</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
                   <span class="o">^^^^^^^^^</span>
       <span class="mi">53</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-using-builtin">
<h2>AttributeError - using builtin<a class="headerlink" href="#attributeerror-using-builtin" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">68</span>, in <span class="n">test_use_builtin</span>
    <span class="n">a</span><span class="o">.</span><span class="n">length</span><span class="p">()</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;list&#39; object has no attribute &#39;length&#39;</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">len(a)</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>The object <code class="docutils literal notranslate"><span class="pre">a</span></code> has no attribute named <code class="docutils literal notranslate"><span class="pre">length</span></code>.
Perhaps you can use the Python builtin function <code class="docutils literal notranslate"><span class="pre">len</span></code> instead:
<code class="docutils literal notranslate"><span class="pre">len(a)</span></code>.</p>
<div class="section" id="exception-raised-on-line-68-of-file-tests-runtime-test-attribute-error-py">
<h3>Exception raised on line 68 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-68-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">66</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
       <span class="mi">67</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">68</span><span class="p">:</span>         <span class="n">a</span><span class="o">.</span><span class="n">length</span><span class="p">()</span>
                   <span class="o">^^^^^^^^</span>
       <span class="mi">69</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-use-synonym">
<h2>AttributeError - use synonym<a class="headerlink" href="#attributeerror-use-synonym" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">84</span>, in <span class="n">test_use_synonym</span>
    <span class="n">a</span><span class="o">.</span><span class="n">add</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;list&#39; object has no attribute &#39;add&#39;</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">append</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>The object <code class="docutils literal notranslate"><span class="pre">a</span></code> has no attribute named <code class="docutils literal notranslate"><span class="pre">add</span></code>.
However, <code class="docutils literal notranslate"><span class="pre">a</span></code> has the following attributes with similar meanings:
<code class="docutils literal notranslate"><span class="pre">append,</span> <span class="pre">extend,</span> <span class="pre">insert</span></code>.</p>
<div class="section" id="exception-raised-on-line-84-of-file-tests-runtime-test-attribute-error-py">
<h3>Exception raised on line 84 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-84-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">82</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
       <span class="mi">83</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">84</span><span class="p">:</span>         <span class="n">a</span><span class="o">.</span><span class="n">add</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
                   <span class="o">^^^^^</span>
       <span class="mi">85</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-typo-in-module-attribute">
<h2>AttributeError - typo in module attribute<a class="headerlink" href="#attributeerror-typo-in-module-attribute" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">113</span>, in <span class="n">test_module_attribute_typo</span>
    <span class="n">math</span><span class="o">.</span><span class="n">cost</span>
<span class="gr">AttributeError</span>: <span class="n">module &#39;math&#39; has no attribute &#39;cost&#39;</span>
</pre></div>
</div>
<p>Did you mean one of the following: <code class="docutils literal notranslate"><span class="pre">cos,</span> <span class="pre">cosh,</span> <span class="pre">acos</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>Instead of writing <code class="docutils literal notranslate"><span class="pre">math.cost</span></code>, perhaps you meant to write one of
the following names which are attributes of module <code class="docutils literal notranslate"><span class="pre">math</span></code>:
<code class="docutils literal notranslate"><span class="pre">cos,</span> <span class="pre">cosh,</span> <span class="pre">acos</span></code></p>
<div class="section" id="exception-raised-on-line-113-of-file-tests-runtime-test-attribute-error-py">
<h3>Exception raised on line 113 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-113-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">111</span><span class="p">:</span> 
       <span class="mi">112</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">113</span><span class="p">:</span>         <span class="n">math</span><span class="o">.</span><span class="n">cost</span>
       <span class="mi">114</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">math</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">module</span> <span class="n">math</span> <span class="p">(</span><span class="n">builtin</span><span class="p">)</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-shadowning-stdlib-module">
<h2>AttributeError - shadowning stdlib module<a class="headerlink" href="#attributeerror-shadowning-stdlib-module" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">134</span>, in <span class="n">test_shadow_stdlib_module</span>
    <span class="n">turtle</span><span class="o">.</span><span class="n">Pen</span>
<span class="gr">AttributeError</span>: <span class="n">module &#39;turtle&#39; has no attribute &#39;Pen&#39;</span>
</pre></div>
</div>
<p>Did you give your program the same name as a Python module?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>You imported a module named <code class="docutils literal notranslate"><span class="pre">turtle</span></code> from <code class="docutils literal notranslate"><span class="pre">TESTS:\turtle.py</span></code>.
There is also a module named <code class="docutils literal notranslate"><span class="pre">turtle</span></code> in Python’s standard library.
Perhaps you need to rename your module.</p>
<div class="section" id="exception-raised-on-line-134-of-file-tests-runtime-test-attribute-error-py">
<h3>Exception raised on line 134 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-134-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">132</span><span class="p">:</span> 
       <span class="mi">133</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">134</span><span class="p">:</span>         <span class="n">turtle</span><span class="o">.</span><span class="n">Pen</span>
       <span class="mi">135</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">turtle</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">module</span> <span class="n">turtle</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">TESTS</span><span class="p">:</span>\<span class="n">turtle</span><span class="o">.</span><span class="n">py</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-using-instead-of">
<h2>AttributeError - using . instead of ,<a class="headerlink" href="#attributeerror-using-instead-of" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">171</span>, in <span class="n">test_perhaps_comma</span>
    <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="n">abcd</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;str&#39; object has no attribute &#39;defg&#39;</span>
</pre></div>
</div>
<p>Did you mean to separate object names by a comma?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p><code class="docutils literal notranslate"><span class="pre">defg</span></code> is not an attribute of <code class="docutils literal notranslate"><span class="pre">abcd</span></code>.
However, both <code class="docutils literal notranslate"><span class="pre">abcd</span></code> and <code class="docutils literal notranslate"><span class="pre">defg</span></code> are known objects.
Perhaps you wrote a period to separate these two objects,
instead of using a comma.</p>
<div class="section" id="exception-raised-on-line-171-of-file-tests-runtime-test-attribute-error-py">
<h3>Exception raised on line 171 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-171-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">169</span><span class="p">:</span>     <span class="c1"># fmt: off</span>
       <span class="mi">170</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">171</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="n">abcd</span>
       <span class="mi">172</span><span class="p">:</span>         <span class="o">.</span><span class="n">defg</span><span class="p">]</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">abcd</span><span class="p">:</span> <span class="s1">&#39;hello&#39;</span>
    <span class="n">defg</span><span class="p">:</span> <span class="s1">&#39;world&#39;</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="filenotfounderror">
<h2>FileNotFoundError<a class="headerlink" href="#filenotfounderror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_file_not_found_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_file_not_found_error</span>
    <span class="nb">open</span><span class="p">(</span><span class="s2">&quot;does_not_exist&quot;</span><span class="p">)</span>
<span class="gr">FileNotFoundError</span>: <span class="n">[Errno 2] No such file or directory: &#39;does_not_exist&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">FileNotFoundError</span></code> exception indicates that you
are trying to open a file that cannot be found by Python.
This could be because you misspelled the name of the file.</p>
<p>In your program, the name of the
file that cannot be found is <code class="docutils literal notranslate"><span class="pre">does_not_exist</span></code>.</p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-file-not-found-error-py">
<h3>Exception raised on line 6 of file TESTS:\runtime\test_file_not_found_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-file-not-found-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_file_not_found_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="nb">open</span><span class="p">(</span><span class="s2">&quot;does_not_exist&quot;</span><span class="p">)</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="importerror">
<h2>ImportError<a class="headerlink" href="#importerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_import_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_import_error</span>
    <span class="kn">from</span> <span class="nn">math</span> <span class="kn">import</span> <span class="n">Pi</span>
<span class="gr">ImportError</span>: <span class="n">cannot import name &#39;Pi&#39; from &#39;math&#39; (unknown location)</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">pi</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">ImportError</span></code> exception indicates that a certain object could not
be imported from a module or package. Most often, this is
because the name of the object is not spelled correctly.</p>
<p>Perhaps you meant to import <code class="docutils literal notranslate"><span class="pre">pi</span></code> (from <code class="docutils literal notranslate"><span class="pre">math</span></code>) instead of <code class="docutils literal notranslate"><span class="pre">Pi</span></code></p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-import-error-py">
<h3>Exception raised on line 6 of file TESTS:\runtime\test_import_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-import-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_import_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="kn">from</span> <span class="nn">math</span> <span class="kn">import</span> <span class="n">Pi</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="keyerror">
<h2>KeyError<a class="headerlink" href="#keyerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_key_error.py&quot;</span>, line <span class="m">7</span>, in <span class="n">test_key_error</span>
    <span class="n">d</span><span class="p">[</span><span class="s2">&quot;c&quot;</span><span class="p">]</span>
<span class="gr">KeyError</span>: <span class="n">&#39;c&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">KeyError</span></code> is raised when a value is not found as a
key in a Python dict.</p>
<p>In your program, the key that cannot be found is <code class="docutils literal notranslate"><span class="pre">'c'</span></code>.</p>
<div class="section" id="exception-raised-on-line-7-of-file-tests-runtime-test-key-error-py">
<h3>Exception raised on line 7 of file TESTS:\runtime\test_key_error.py.<a class="headerlink" href="#exception-raised-on-line-7-of-file-tests-runtime-test-key-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">5</span><span class="p">:</span>     <span class="n">d</span> <span class="o">=</span> <span class="p">{</span><span class="s2">&quot;a&quot;</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="s2">&quot;b&quot;</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">6</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">7</span><span class="p">:</span>         <span class="n">d</span><span class="p">[</span><span class="s2">&quot;c&quot;</span><span class="p">]</span>
       <span class="mi">8</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">d</span><span class="p">:</span> <span class="p">{</span><span class="s1">&#39;a&#39;</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="s1">&#39;b&#39;</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="lookuperror">
<h2>LookupError<a class="headerlink" href="#lookuperror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_lookup_error.py&quot;</span>, line <span class="m">10</span>, in <span class="n">test_lookup_error</span>
    <span class="k">raise</span> <span class="ne">LookupError</span><span class="p">(</span><span class="s2">&quot;Fake message&quot;</span><span class="p">)</span>
<span class="gr">LookupError</span>: <span class="n">Fake message</span>
</pre></div>
</div>
<p><code class="docutils literal notranslate"><span class="pre">LookupError</span></code> is the base class for the exceptions that are raised
when a key or index used on a mapping or sequence is invalid.
It can also be raised directly by codecs.lookup().</p>
<div class="section" id="exception-raised-on-line-10-of-file-tests-runtime-test-lookup-error-py">
<h3>Exception raised on line 10 of file TESTS:\runtime\test_lookup_error.py.<a class="headerlink" href="#exception-raised-on-line-10-of-file-tests-runtime-test-lookup-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">8</span><span class="p">:</span>         <span class="c1"># other than possibly codecs.lookup(), which is why we raise</span>
        <span class="mi">9</span><span class="p">:</span>         <span class="c1"># it directly here for our example.</span>
    <span class="o">--&gt;</span><span class="mi">10</span><span class="p">:</span>         <span class="k">raise</span> <span class="ne">LookupError</span><span class="p">(</span><span class="s2">&quot;Fake message&quot;</span><span class="p">)</span>
       <span class="mi">11</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="indexerror-short-tuple">
<h2>IndexError - short tuple<a class="headerlink" href="#indexerror-short-tuple" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_index_error.py&quot;</span>, line <span class="m">8</span>, in <span class="n">test_index_error1</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">3</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">2</span><span class="p">])</span>
<span class="gr">IndexError</span>: <span class="n">tuple index out of range</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">IndexError</span></code> occurs when you are try to get an item from a list,
a tuple, or a similar object (sequence), by using an index which
does not exists; typically, this is because the index you give
is greater than the length of the sequence.
Reminder: the first item of a sequence is at index 0.</p>
<div class="section" id="exception-raised-on-line-8-of-file-tests-runtime-test-index-error-py">
<h3>Exception raised on line 8 of file TESTS:\runtime\test_index_error.py.<a class="headerlink" href="#exception-raised-on-line-8-of-file-tests-runtime-test-index-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">6</span><span class="p">:</span>     <span class="n">b</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
        <span class="mi">7</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span> <span class="mi">8</span><span class="p">:</span>         <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">3</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">2</span><span class="p">])</span>
                         <span class="o">^^^^</span>
        <span class="mi">9</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="indexerror-long-list">
<h2>IndexError - long list<a class="headerlink" href="#indexerror-long-list" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_index_error.py&quot;</span>, line <span class="m">22</span>, in <span class="n">test_index_error2</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">50</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span>
<span class="gr">IndexError</span>: <span class="n">list index out of range</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">IndexError</span></code> occurs when you are try to get an item from a list,
a tuple, or a similar object (sequence), by using an index which
does not exists; typically, this is because the index you give
is greater than the length of the sequence.
Reminder: the first item of a sequence is at index 0.</p>
<div class="section" id="exception-raised-on-line-22-of-file-tests-runtime-test-index-error-py">
<h3>Exception raised on line 22 of file TESTS:\runtime\test_index_error.py.<a class="headerlink" href="#exception-raised-on-line-22-of-file-tests-runtime-test-index-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">20</span><span class="p">:</span>     <span class="n">b</span> <span class="o">=</span> <span class="nb">tuple</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">50</span><span class="p">))</span>
       <span class="mi">21</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">22</span><span class="p">:</span>         <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">50</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span>
                         <span class="o">^^^^^</span>
       <span class="mi">23</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="mi">12</span><span class="p">,</span> <span class="mi">13</span><span class="p">,</span> <span class="mi">14</span><span class="p">,</span> <span class="mi">15</span><span class="p">,</span> <span class="mi">16</span><span class="p">,</span> <span class="mi">17</span><span class="p">,</span> <span class="mi">18</span><span class="p">,</span> <span class="o">...</span><span class="p">]</span>
        <span class="nb">len</span><span class="p">(</span><span class="n">a</span><span class="p">):</span> <span class="mi">40</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="modulenotfounderror">
<h2>ModuleNotFoundError<a class="headerlink" href="#modulenotfounderror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_module_not_found_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_module_not_found_error</span>
    <span class="kn">import</span> <span class="nn">Tkinter</span>
<span class="gr">ModuleNotFoundError</span>: <span class="n">No module named &#39;Tkinter&#39;</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">tkinter</span></code>?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">ModuleNotFoundError</span></code> exception indicates that you
are trying to import a module that cannot be found by Python.
This could be because you misspelled the name of the module
or because it is not installed on your computer.</p>
<p>The name of the module that could not be imported is <code class="docutils literal notranslate"><span class="pre">Tkinter</span></code>.
<code class="docutils literal notranslate"><span class="pre">tkinter</span></code> is an existing module that has a similar name.</p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-module-not-found-error-py">
<h3>Exception raised on line 6 of file TESTS:\runtime\test_module_not_found_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-module-not-found-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_module_not_found_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="kn">import</span> <span class="nn">Tkinter</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="nameerror-1">
<h2>NameError - 1<a class="headerlink" href="#nameerror-1" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_name_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_name_error</span>
    <span class="n">this</span> <span class="o">=</span> <span class="n">something</span>
<span class="gr">NameError</span>: <span class="n">name &#39;something&#39; is not defined</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<p>In your program, <code class="docutils literal notranslate"><span class="pre">something</span></code> is an unknown name.
I have no additional information for you.</p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-name-error-py">
<h3>Exception raised on line 6 of file TESTS:\runtime\test_name_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-name-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_name_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="n">this</span> <span class="o">=</span> <span class="n">something</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="nameerror-2">
<h2>NameError - 2<a class="headerlink" href="#nameerror-2" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_name_error.py&quot;</span>, line <span class="m">20</span>, in <span class="n">test_name_error2</span>
    <span class="n">x</span> <span class="o">=</span> <span class="n">babs</span><span class="p">(</span><span class="o">-</span><span class="mi">1</span><span class="p">)</span>
<span class="gr">NameError</span>: <span class="n">name &#39;babs&#39; is not defined</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">abs</span></code>?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<p>In your program, <code class="docutils literal notranslate"><span class="pre">babs</span></code> is an unknown name.
Instead of writing <code class="docutils literal notranslate"><span class="pre">babs</span></code>, perhaps you meant one of the following:</p>
<ul class="simple">
<li><p>Local scope: <code class="docutils literal notranslate"><span class="pre">nabs</span></code></p></li>
<li><p>Global scope: <code class="docutils literal notranslate"><span class="pre">fabs</span></code></p></li>
<li><p>Python builtins: <code class="docutils literal notranslate"><span class="pre">abs</span></code></p></li>
</ul>
<div class="section" id="exception-raised-on-line-20-of-file-tests-runtime-test-name-error-py">
<h3>Exception raised on line 20 of file TESTS:\runtime\test_name_error.py.<a class="headerlink" href="#exception-raised-on-line-20-of-file-tests-runtime-test-name-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">18</span><span class="p">:</span>     <span class="n">nabs</span> <span class="o">=</span> <span class="mi">1</span>
       <span class="mi">19</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">20</span><span class="p">:</span>         <span class="n">x</span> <span class="o">=</span> <span class="n">babs</span><span class="p">(</span><span class="o">-</span><span class="mi">1</span><span class="p">)</span>
       <span class="mi">21</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="nameerror-3">
<h2>NameError - 3<a class="headerlink" href="#nameerror-3" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_name_error.py&quot;</span>, line <span class="m">35</span>, in <span class="n">test_name_error3</span>
    <span class="n">y</span> <span class="o">=</span> <span class="n">x</span>
<span class="gr">NameError</span>: <span class="n">name &#39;x&#39; is not defined</span>
</pre></div>
</div>
<p>Did you use a colon instead of an equal sign?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<p>In your program, <code class="docutils literal notranslate"><span class="pre">x</span></code> is an unknown name.
A type hint found for <code class="docutils literal notranslate"><span class="pre">x</span></code> in the global scope.
Perhaps you had used a colon instead of an equal sign and written</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">x</span> <span class="p">:</span> <span class="mi">3</span>
</pre></div>
</div>
<p>instead of</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">x</span> <span class="o">=</span> <span class="mi">3</span>
</pre></div>
</div>
<div class="section" id="exception-raised-on-line-35-of-file-tests-runtime-test-name-error-py">
<h3>Exception raised on line 35 of file TESTS:\runtime\test_name_error.py.<a class="headerlink" href="#exception-raised-on-line-35-of-file-tests-runtime-test-name-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">33</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_name_error3</span><span class="p">():</span>
       <span class="mi">34</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">35</span><span class="p">:</span>         <span class="n">y</span> <span class="o">=</span> <span class="n">x</span>
       <span class="mi">36</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="nameerror-4">
<h2>NameError - 4<a class="headerlink" href="#nameerror-4" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_name_error.py&quot;</span>, line <span class="m">48</span>, in <span class="n">test_name_error4</span>
    <span class="n">cost</span>  <span class="c1"># wrote from math import * above</span>
<span class="gr">NameError</span>: <span class="n">name &#39;cost&#39; is not defined</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">cos</span></code>?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<p>In your program, <code class="docutils literal notranslate"><span class="pre">cost</span></code> is an unknown name.
Instead of writing <code class="docutils literal notranslate"><span class="pre">cost</span></code>, perhaps you meant one of the following:</p>
<ul class="simple">
<li><p>Global scope: <code class="docutils literal notranslate"><span class="pre">cos</span></code>, <code class="docutils literal notranslate"><span class="pre">cosh</span></code>, <code class="docutils literal notranslate"><span class="pre">acos</span></code></p></li>
</ul>
<div class="section" id="exception-raised-on-line-48-of-file-tests-runtime-test-name-error-py">
<h3>Exception raised on line 48 of file TESTS:\runtime\test_name_error.py.<a class="headerlink" href="#exception-raised-on-line-48-of-file-tests-runtime-test-name-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">46</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_name_error4</span><span class="p">():</span>
       <span class="mi">47</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">48</span><span class="p">:</span>         <span class="n">cost</span>  <span class="c1"># wrote from math import * above</span>
       <span class="mi">49</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="overflowerror">
<h2>OverflowError<a class="headerlink" href="#overflowerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_overflow_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_overflow_error</span>
    <span class="mf">2.0</span> <span class="o">**</span> <span class="mi">1600</span>
<span class="gr">OverflowError</span>: <span class="n">(34, &#39;Result too large&#39;)</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">OverflowError</span></code> is raised when the result of an arithmetic operation
is too large to be handled by the computer’s processor.</p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-overflow-error-py">
<h3>Exception raised on line 6 of file TESTS:\runtime\test_overflow_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-overflow-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_overflow_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="mf">2.0</span> <span class="o">**</span> <span class="mi">1600</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="recursionerror">
<h2>RecursionError<a class="headerlink" href="#recursionerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_recursion_error.py&quot;</span>, line <span class="m">8</span>, in <span class="n">test_function_recursion_error</span>
    <span class="n">a</span><span class="p">()</span>

<span class="x">       ... More lines not shown. ...</span>

  File <span class="nb">&quot;TESTS:\runtime\test_recursion_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">a</span>
    <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_recursion_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">a</span>
    <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
<span class="gr">RecursionError</span>: <span class="n">maximum recursion depth exceeded</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">RecursionError</span></code> is raised when a function calls itself,
directly or indirectly, too many times.
It almost always indicates that you made an error in your code
and that your program would never stop.</p>
<div class="section" id="execution-stopped-on-line-8-of-file-tests-runtime-test-recursion-error-py">
<h3>Execution stopped on line 8 of file TESTS:\runtime\test_recursion_error.py.<a class="headerlink" href="#execution-stopped-on-line-8-of-file-tests-runtime-test-recursion-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">6</span><span class="p">:</span>         <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
        <span class="mi">7</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span> <span class="mi">8</span><span class="p">:</span>         <span class="n">a</span><span class="p">()</span>
        <span class="mi">9</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">a</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_function_recursion_error</span>
</pre></div>
</div>
</div>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-recursion-error-py">
<h3>Exception raised on line 6 of file TESTS:\runtime\test_recursion_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-recursion-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_function_recursion_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">def</span> <span class="nf">a</span><span class="p">():</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
                         <span class="o">^^^</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">a</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_function_recursion_error</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-1-concatenate-two-different-types">
<h2>TypeError - 1: concatenate two different types<a class="headerlink" href="#typeerror-1-concatenate-two-different-types" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">36</span>, in <span class="n">test_type_error1</span>
    <span class="n">result</span> <span class="o">=</span> <span class="n">a_tuple</span> <span class="o">+</span> <span class="n">a_list</span>
<span class="gr">TypeError</span>: <span class="n">can only concatenate tuple (not &quot;list&quot;) to tuple</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to concatenate (add) two different types of objects:
a <code class="docutils literal notranslate"><span class="pre">tuple</span></code> and a <code class="docutils literal notranslate"><span class="pre">list</span></code></p>
<div class="section" id="exception-raised-on-line-36-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 36 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-36-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">34</span><span class="p">:</span>         <span class="n">a_tuple</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
       <span class="mi">35</span><span class="p">:</span>         <span class="n">a_list</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">36</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a_tuple</span> <span class="o">+</span> <span class="n">a_list</span>
                            <span class="o">^^^^^^^^^^^^^^^^</span>
       <span class="mi">37</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a_tuple</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
    <span class="n">a_list</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-2-unsupported-operand-type-s-for">
<h2>TypeError - 2: unsupported operand type(s) for +=<a class="headerlink" href="#typeerror-2-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">66</span>, in <span class="n">test_type_error2</span>
    <span class="n">one</span> <span class="o">+=</span> <span class="n">two</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for +=: &#39;int&#39; and &#39;str&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to add two incompatible types of objects:
an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>) and a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>)</p>
<div class="section" id="exception-raised-on-line-66-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 66 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-66-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">64</span><span class="p">:</span>         <span class="n">one</span> <span class="o">=</span> <span class="mi">1</span>
       <span class="mi">65</span><span class="p">:</span>         <span class="n">two</span> <span class="o">=</span> <span class="s2">&quot;two&quot;</span>
    <span class="o">--&gt;</span><span class="mi">66</span><span class="p">:</span>         <span class="n">one</span> <span class="o">+=</span> <span class="n">two</span>
       <span class="mi">67</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">one</span><span class="p">:</span> <span class="mi">1</span>
    <span class="n">two</span><span class="p">:</span> <span class="s1">&#39;two&#39;</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-3-unsupported-operand-type-s-for">
<h2>TypeError - 3: unsupported operand type(s) for -=<a class="headerlink" href="#typeerror-3-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">94</span>, in <span class="n">test_type_error3</span>
    <span class="n">b</span> <span class="o">-=</span> <span class="n">a</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for -=: &#39;list&#39; and &#39;tuple&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to subtract two incompatible types of objects:
a <code class="docutils literal notranslate"><span class="pre">list</span></code> and a <code class="docutils literal notranslate"><span class="pre">tuple</span></code></p>
<div class="section" id="exception-raised-on-line-94-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 94 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-94-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">92</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">)</span>
       <span class="mi">93</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="p">[</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">94</span><span class="p">:</span>         <span class="n">b</span> <span class="o">-=</span> <span class="n">a</span>
       <span class="mi">95</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="p">[</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]</span>
    <span class="n">a</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-4-unsupported-operand-type-s-for">
<h2>TypeError - 4: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">*=</span></code><a class="headerlink" href="#typeerror-4-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">122</span>, in <span class="n">test_type_error4</span>
    <span class="n">b</span> <span class="o">*=</span> <span class="n">a</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for *=: &#39;set&#39; and &#39;complex&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to multiply two incompatible types of objects:
a <code class="docutils literal notranslate"><span class="pre">set</span></code> and a complex number</p>
<div class="section" id="exception-raised-on-line-122-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 122 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-122-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">120</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="mi">1</span><span class="n">j</span>
       <span class="mi">121</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="p">{</span><span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">}</span>
    <span class="o">--&gt;</span><span class="mi">122</span><span class="p">:</span>         <span class="n">b</span> <span class="o">*=</span> <span class="n">a</span>
       <span class="mi">123</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="p">{</span><span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">}</span>
    <span class="n">a</span><span class="p">:</span> <span class="mi">1</span><span class="n">j</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-5-unsupported-operand-type-s-for">
<h2>TypeError - 5: unsupported operand type(s) for //=<a class="headerlink" href="#typeerror-5-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">174</span>, in <span class="n">test_type_error5</span>
    <span class="n">b</span> <span class="o">//=</span> <span class="n">a</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for //=: &#39;float&#39; and &#39;dict&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to divide two incompatible types of objects:
a number (<code class="docutils literal notranslate"><span class="pre">float</span></code>) and a dictionary (<code class="docutils literal notranslate"><span class="pre">dict</span></code>)</p>
<div class="section" id="exception-raised-on-line-174-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 174 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-174-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">172</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">173</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mf">3.1416</span>
    <span class="o">--&gt;</span><span class="mi">174</span><span class="p">:</span>         <span class="n">b</span> <span class="o">//=</span> <span class="n">a</span>
       <span class="mi">175</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="mf">3.1416</span>
    <span class="n">a</span><span class="p">:</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-6-unsupported-operand-type-s-for">
<h2>TypeError - 6: unsupported operand type(s) for &amp;=<a class="headerlink" href="#typeerror-6-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">202</span>, in <span class="n">test_type_error6</span>
    <span class="n">b</span> <span class="o">&amp;=</span> <span class="n">a</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for &amp;=: &#39;int&#39; and &#39;str&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to perform the bitwise operation &amp;=
on two incompatible types of objects:
an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>) and a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>)</p>
<div class="section" id="exception-raised-on-line-202-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 202 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-202-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">200</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">201</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">2</span>
    <span class="o">--&gt;</span><span class="mi">202</span><span class="p">:</span>         <span class="n">b</span> <span class="o">&amp;=</span> <span class="n">a</span>
       <span class="mi">203</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="mi">2</span>
    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-7-unsupported-operand-type-s-for">
<h2>TypeError - 7: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">**=</span></code><a class="headerlink" href="#typeerror-7-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">230</span>, in <span class="n">test_type_error7</span>
    <span class="n">a</span> <span class="o">**=</span> <span class="n">b</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for ** or pow(): &#39;dict&#39; and &#39;float&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to exponentiate (raise to a power)
using two incompatible types of objects:
a dictionary (<code class="docutils literal notranslate"><span class="pre">dict</span></code>) and a number (<code class="docutils literal notranslate"><span class="pre">float</span></code>)</p>
<div class="section" id="exception-raised-on-line-230-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 230 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-230-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">228</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">229</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mf">3.1416</span>
    <span class="o">--&gt;</span><span class="mi">230</span><span class="p">:</span>         <span class="n">a</span> <span class="o">**=</span> <span class="n">b</span>
       <span class="mi">231</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
    <span class="n">b</span><span class="p">:</span> <span class="mf">3.1416</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-8-unsupported-operand-type-s-for">
<h2>TypeError - 8: unsupported operand type(s) for &gt;&gt;=<a class="headerlink" href="#typeerror-8-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">258</span>, in <span class="n">test_type_error8</span>
    <span class="n">a</span> <span class="o">&gt;&gt;=</span> <span class="n">b</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for &gt;&gt;=: &#39;str&#39; and &#39;int&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to perform the bit shifting operation &gt;&gt;=
on two incompatible types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>)</p>
<div class="section" id="exception-raised-on-line-258-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 258 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-258-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">256</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">257</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">42</span>
    <span class="o">--&gt;</span><span class="mi">258</span><span class="p">:</span>         <span class="n">a</span> <span class="o">&gt;&gt;=</span> <span class="n">b</span>
       <span class="mi">259</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">b</span><span class="p">:</span> <span class="mi">42</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-9-unsupported-operand-type-s-for">
<h2>TypeError - 9: unsupported operand type(s) for &#64;=<a class="headerlink" href="#typeerror-9-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">286</span>, in <span class="n">test_type_error9</span>
    <span class="n">a</span> <span class="o">@=</span> <span class="n">b</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for @=: &#39;str&#39; and &#39;int&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to use the operator &#64;=
using two incompatible types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>).
This operator is normally used only
for multiplication of matrices.</p>
<div class="section" id="exception-raised-on-line-286-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 286 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-286-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">284</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">285</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">2</span>
    <span class="o">--&gt;</span><span class="mi">286</span><span class="p">:</span>         <span class="n">a</span> <span class="o">@=</span> <span class="n">b</span>
       <span class="mi">287</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">b</span><span class="p">:</span> <span class="mi">2</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-10-comparison-between-incompatible-types">
<h2>TypeError - 10: comparison between incompatible types<a class="headerlink" href="#typeerror-10-comparison-between-incompatible-types" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">302</span>, in <span class="n">test_type_error10</span>
    <span class="n">b</span> <span class="o">&lt;</span> <span class="n">a</span>
<span class="gr">TypeError</span>: <span class="n">&#39;&lt;&#39; not supported between instances of &#39;int&#39; and &#39;str&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to do an order comparison (&lt;)
between two incompatible types of objects:
an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>) and a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>)</p>
<div class="section" id="exception-raised-on-line-302-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 302 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-302-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">300</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">301</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">42</span>
    <span class="o">--&gt;</span><span class="mi">302</span><span class="p">:</span>         <span class="n">b</span> <span class="o">&lt;</span> <span class="n">a</span>
       <span class="mi">303</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="mi">42</span>
    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-11-bad-operand-type-for-unary">
<h2>TypeError - 11: bad operand type for unary +<a class="headerlink" href="#typeerror-11-bad-operand-type-for-unary" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">352</span>, in <span class="n">test_type_error11</span>
    <span class="n">a</span> <span class="o">=+</span> <span class="s2">&quot;def&quot;</span>
<span class="gr">TypeError</span>: <span class="n">bad operand type for unary +: &#39;str&#39;</span>
</pre></div>
</div>
<p>Perhaps you meant to write <code class="docutils literal notranslate"><span class="pre">+=</span></code> instead of <code class="docutils literal notranslate"><span class="pre">=+</span></code></p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to use the unary operator ‘+’
with the following type of object: a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>).
This operation is not defined for this type of object.</p>
<p>Perhaps you meant to write <code class="docutils literal notranslate"><span class="pre">+=</span></code> instead of <code class="docutils literal notranslate"><span class="pre">=+</span></code></p>
<div class="section" id="exception-raised-on-line-352-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 352 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-352-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">350</span><span class="p">:</span>         <span class="c1"># fmt: off</span>
       <span class="mi">351</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;abc&quot;</span>
    <span class="o">--&gt;</span><span class="mi">352</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=+</span> <span class="s2">&quot;def&quot;</span>
                       <span class="o">^^^^^^^</span>
       <span class="mi">353</span><span class="p">:</span>         <span class="c1"># fmt: on</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-12-object-does-not-support-item-assignment">
<h2>TypeError - 12: object does not support item assignment<a class="headerlink" href="#typeerror-12-object-does-not-support-item-assignment" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">370</span>, in <span class="n">test_type_error12</span>
    <span class="n">a</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span> <span class="o">=</span> <span class="mi">0</span>
<span class="gr">TypeError</span>: <span class="n">&#39;tuple&#39; object does not support item assignment</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>In Python, some objects are known as immutable:
once defined, their value cannot be changed.
You tried change part of such an immutable object: a <code class="docutils literal notranslate"><span class="pre">tuple</span></code>,
most likely by using an indexing operation.</p>
<div class="section" id="exception-raised-on-line-370-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 370 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-370-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">368</span><span class="p">:</span>     <span class="n">a</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
       <span class="mi">369</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">370</span><span class="p">:</span>         <span class="n">a</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span> <span class="o">=</span> <span class="mi">0</span>
       <span class="mi">371</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">[</span><span class="mi">0</span><span class="p">]:</span> <span class="mi">1</span>
    <span class="n">a</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-13-wrong-number-of-positional-arguments">
<h2>TypeError - 13: wrong number of positional arguments<a class="headerlink" href="#typeerror-13-wrong-number-of-positional-arguments" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">402</span>, in <span class="n">test_type_error13</span>
    <span class="n">A</span><span class="p">()</span><span class="o">.</span><span class="n">f</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="gr">TypeError</span>: <span class="n">f() takes 1 positional argument but 2 were given</span>
</pre></div>
</div>
<p>Perhaps you forgot <code class="docutils literal notranslate"><span class="pre">self</span></code> when defining <code class="docutils literal notranslate"><span class="pre">f</span></code>.</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You apparently have called the function <code class="docutils literal notranslate"><span class="pre">f</span></code> with
2 positional argument(s) while it requires 1
such positional argument(s).
Perhaps you forgot <code class="docutils literal notranslate"><span class="pre">self</span></code> when defining <code class="docutils literal notranslate"><span class="pre">f</span></code>.</p>
<div class="section" id="exception-raised-on-line-402-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 402 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-402-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">400</span><span class="p">:</span> 
       <span class="mi">401</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">402</span><span class="p">:</span>         <span class="n">A</span><span class="p">()</span><span class="o">.</span><span class="n">f</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
       <span class="mi">403</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">A</span><span class="p">:</span> <span class="o">&lt;</span><span class="k">class</span> <span class="nc">A</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_type_error.test_type_error13</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-14-missing-positional-arguments">
<h2>TypeError - 14: missing positional arguments<a class="headerlink" href="#typeerror-14-missing-positional-arguments" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">421</span>, in <span class="n">test_type_error14</span>
    <span class="n">fn</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="gr">TypeError</span>: <span class="n">fn() missing 2 required positional arguments: &#39;b&#39; and &#39;c&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You apparently have called the function ‘fn()’ with
fewer positional arguments than it requires (2 missing).</p>
<div class="section" id="exception-raised-on-line-421-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 421 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-421-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">419</span><span class="p">:</span> 
       <span class="mi">420</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">421</span><span class="p">:</span>         <span class="n">fn</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
       <span class="mi">422</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">fn</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">fn</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_type_error14</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-15-list-object-is-not-callable">
<h2>TypeError - 15: list object is not callable<a class="headerlink" href="#typeerror-15-list-object-is-not-callable" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">456</span>, in <span class="n">test_type_error15</span>
    <span class="n">_</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">](</span><span class="mi">3</span> <span class="o">+</span> <span class="mi">4</span><span class="p">)</span>
<span class="gr">TypeError</span>: <span class="n">&#39;list&#39; object is not callable</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">[1,</span> <span class="pre">2][3</span> <span class="pre">+</span> <span class="pre">4]</span></code>?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>Because of the surrounding parenthesis, <code class="docutils literal notranslate"><span class="pre">(3</span> <span class="pre">+</span> <span class="pre">4)</span></code>
is interpreted by Python as indicating a function call for
<code class="docutils literal notranslate"><span class="pre">[1,</span> <span class="pre">2]</span></code>, which is an object of type <code class="docutils literal notranslate"><span class="pre">list</span></code>
which cannot be called.</p>
<p>However, <code class="docutils literal notranslate"><span class="pre">[1,</span> <span class="pre">2]</span></code> is a sequence.
Perhaps you meant to use <code class="docutils literal notranslate"><span class="pre">[]</span></code> instead of <code class="docutils literal notranslate"><span class="pre">()</span></code> and write
<code class="docutils literal notranslate"><span class="pre">[1,</span> <span class="pre">2][3</span> <span class="pre">+</span> <span class="pre">4]</span></code></p>
<div class="section" id="exception-raised-on-line-456-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 456 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-456-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">454</span><span class="p">:</span> 
       <span class="mi">455</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">456</span><span class="p">:</span>         <span class="n">_</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">](</span><span class="mi">3</span> <span class="o">+</span> <span class="mi">4</span><span class="p">)</span>
                        <span class="o">^^^^^^^^^^^^^</span>
       <span class="mi">457</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-16-exception-derived-from-baseexception">
<h2>TypeError - 16: exception derived from BaseException<a class="headerlink" href="#typeerror-16-exception-derived-from-baseexception" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">481</span>, in <span class="n">test_type_error16</span>
    <span class="k">raise</span> <span class="s2">&quot;exception&quot;</span>
<span class="gr">TypeError</span>: <span class="n">exceptions must derive from BaseException</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>In Python 3, exceptions must be derived from BaseException.</p>
<div class="section" id="exception-raised-on-line-481-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 481 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-481-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">479</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_type_error16</span><span class="p">():</span>
       <span class="mi">480</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">481</span><span class="p">:</span>         <span class="k">raise</span> <span class="s2">&quot;exception&quot;</span>
       <span class="mi">482</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-17-can-t-multiply-sequence-by-non-int">
<h2>TypeError - 17: can’t multiply sequence by non-int<a class="headerlink" href="#typeerror-17-can-t-multiply-sequence-by-non-int" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">550</span>, in <span class="n">test_type_error17</span>
    <span class="s2">&quot;a&quot;</span> <span class="o">*</span> <span class="s2">&quot;2&quot;</span>
<span class="gr">TypeError</span>: <span class="n">can&#39;t multiply sequence by non-int of type &#39;str&#39;</span>
</pre></div>
</div>
<p>Did you forget to convert <code class="docutils literal notranslate"><span class="pre">&quot;2&quot;</span></code> into an integer?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You can only multiply sequences, such as list, tuples,
strings, etc., by integers.
Perhaps you forgot to convert <code class="docutils literal notranslate"><span class="pre">&quot;2&quot;</span></code> into an integer.</p>
<div class="section" id="exception-raised-on-line-550-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 550 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-550-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">548</span><span class="p">:</span> 
       <span class="mi">549</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">550</span><span class="p">:</span>         <span class="s2">&quot;a&quot;</span> <span class="o">*</span> <span class="s2">&quot;2&quot;</span>
       <span class="mi">551</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-18-object-cannot-be-interpreted-as-an-integer">
<h2>TypeError - 18: object cannot be interpreted as an integer<a class="headerlink" href="#typeerror-18-object-cannot-be-interpreted-as-an-integer" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">598</span>, in <span class="n">test_type_error18</span>
    <span class="nb">range</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">d</span><span class="p">)</span>
<span class="gr">TypeError</span>: <span class="n">&#39;str&#39; object cannot be interpreted as an integer</span>
</pre></div>
</div>
<p>Did you forget to convert <code class="docutils literal notranslate"><span class="pre">c,</span> <span class="pre">d</span></code> into integers?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You wrote an object of type <code class="docutils literal notranslate"><span class="pre">str</span></code> where an integer was expected.
Perhaps you forgot to convert <code class="docutils literal notranslate"><span class="pre">c,</span> <span class="pre">d</span></code> into integers.</p>
<div class="section" id="exception-raised-on-line-598-of-file-tests-runtime-test-type-error-py">
<h3>Exception raised on line 598 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-598-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">596</span><span class="p">:</span>     <span class="n">c</span><span class="p">,</span> <span class="n">d</span> <span class="o">=</span> <span class="s2">&quot;2&quot;</span><span class="p">,</span> <span class="s2">&quot;3&quot;</span>
       <span class="mi">597</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">598</span><span class="p">:</span>         <span class="nb">range</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">d</span><span class="p">)</span>
       <span class="mi">599</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">c</span><span class="p">:</span> <span class="s1">&#39;2&#39;</span>
    <span class="n">d</span><span class="p">:</span> <span class="s1">&#39;3&#39;</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="unboundlocalerror-1-missing-global">
<h2>UnboundLocalError - 1: missing global<a class="headerlink" href="#unboundlocalerror-1-missing-global" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">27</span>, in <span class="n">test_unbound_local_error_missing_global</span>
    <span class="n">outer_missing_global</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">11</span>, in <span class="n">outer_missing_global</span>
    <span class="n">inner</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">9</span>, in <span class="n">inner</span>
    <span class="n">spam_missing_global</span> <span class="o">+=</span> <span class="mi">1</span>
<span class="gr">UnboundLocalError</span>: <span class="n">local variable &#39;spam_missing_global&#39; referenced before assignment</span>
</pre></div>
</div>
<p>Did you forget to add <code class="docutils literal notranslate"><span class="pre">global</span> <span class="pre">spam_missing_global</span></code>?</p>
<p>In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a <code class="docutils literal notranslate"><span class="pre">global</span></code>
(or sometimes <code class="docutils literal notranslate"><span class="pre">nonlocal</span></code>) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an <code class="docutils literal notranslate"><span class="pre">UnboundLocalError</span></code>.</p>
<p>The name <code class="docutils literal notranslate"><span class="pre">spam_missing_global</span></code> exists in the global scope.
Perhaps the statement</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">global</span> <span class="n">spam_missing_global</span>
</pre></div>
</div>
<p>should have been included as the first line inside your function.</p>
<div class="section" id="execution-stopped-on-line-27-of-file-tests-runtime-test-unbound-local-error-py">
<h3>Execution stopped on line 27 of file TESTS:\runtime\test_unbound_local_error.py.<a class="headerlink" href="#execution-stopped-on-line-27-of-file-tests-runtime-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">25</span><span class="p">:</span> 
       <span class="mi">26</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">27</span><span class="p">:</span>         <span class="n">outer_missing_global</span><span class="p">()</span>
       <span class="mi">28</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">outer_missing_global</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">outer_missing_global</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
<div class="section" id="exception-raised-on-line-9-of-file-tests-runtime-test-unbound-local-error-py">
<h3>Exception raised on line 9 of file TESTS:\runtime\test_unbound_local_error.py.<a class="headerlink" href="#exception-raised-on-line-9-of-file-tests-runtime-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">7</span><span class="p">:</span> <span class="k">def</span> <span class="nf">outer_missing_global</span><span class="p">():</span>
        <span class="mi">8</span><span class="p">:</span>     <span class="k">def</span> <span class="nf">inner</span><span class="p">():</span>
    <span class="o">--&gt;</span> <span class="mi">9</span><span class="p">:</span>         <span class="n">spam_missing_global</span> <span class="o">+=</span> <span class="mi">1</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">spam_missing_global</span><span class="p">:</span> <span class="mi">1</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="unboundlocalerror-2-missing-nonlocal">
<h2>UnboundLocalError - 2: missing nonlocal<a class="headerlink" href="#unboundlocalerror-2-missing-nonlocal" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">48</span>, in <span class="n">test_unbound_local_error_missing_nonlocal</span>
    <span class="n">outer_missing_nonlocal</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">20</span>, in <span class="n">outer_missing_nonlocal</span>
    <span class="n">inner</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">18</span>, in <span class="n">inner</span>
    <span class="n">spam_missing_nonlocal</span> <span class="o">+=</span> <span class="mi">1</span>
<span class="gr">UnboundLocalError</span>: <span class="n">local variable &#39;spam_missing_nonlocal&#39; referenced before assignment</span>
</pre></div>
</div>
<p>Did you forget to add <code class="docutils literal notranslate"><span class="pre">nonlocal</span> <span class="pre">spam_missing_nonlocal</span></code>?</p>
<p>In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a <code class="docutils literal notranslate"><span class="pre">global</span></code>
(or sometimes <code class="docutils literal notranslate"><span class="pre">nonlocal</span></code>) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an <code class="docutils literal notranslate"><span class="pre">UnboundLocalError</span></code>.</p>
<p>The name <code class="docutils literal notranslate"><span class="pre">spam_missing_nonlocal</span></code> exists in the nonlocal scope.
Perhaps the statement</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">nonlocal</span> <span class="n">spam_missing_nonlocal</span>
</pre></div>
</div>
<p>should have been included as the first line inside your function.</p>
<div class="section" id="execution-stopped-on-line-48-of-file-tests-runtime-test-unbound-local-error-py">
<h3>Execution stopped on line 48 of file TESTS:\runtime\test_unbound_local_error.py.<a class="headerlink" href="#execution-stopped-on-line-48-of-file-tests-runtime-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">46</span><span class="p">:</span> 
       <span class="mi">47</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">48</span><span class="p">:</span>         <span class="n">outer_missing_nonlocal</span><span class="p">()</span>
       <span class="mi">49</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">outer_missing_nonlocal</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">outer_missing_nonlocal</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
<div class="section" id="exception-raised-on-line-18-of-file-tests-runtime-test-unbound-local-error-py">
<h3>Exception raised on line 18 of file TESTS:\runtime\test_unbound_local_error.py.<a class="headerlink" href="#exception-raised-on-line-18-of-file-tests-runtime-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">16</span><span class="p">:</span> 
       <span class="mi">17</span><span class="p">:</span>     <span class="k">def</span> <span class="nf">inner</span><span class="p">():</span>
    <span class="o">--&gt;</span><span class="mi">18</span><span class="p">:</span>         <span class="n">spam_missing_nonlocal</span> <span class="o">+=</span> <span class="mi">1</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="unknown-exception">
<h2>Unknown exception<a class="headerlink" href="#unknown-exception" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unknown_error.py&quot;</span>, line <span class="m">10</span>, in <span class="n">test_function_unknown_error</span>
    <span class="k">raise</span> <span class="n">MyException</span><span class="p">(</span><span class="s2">&quot;Some informative message about an unknown exception.&quot;</span><span class="p">)</span>
<span class="gr">MyException</span>: <span class="n">Some informative message about an unknown exception.</span>
</pre></div>
</div>
<p>No information is available about this exception.</p>
<div class="section" id="exception-raised-on-line-10-of-file-tests-runtime-test-unknown-error-py">
<h3>Exception raised on line 10 of file TESTS:\runtime\test_unknown_error.py.<a class="headerlink" href="#exception-raised-on-line-10-of-file-tests-runtime-test-unknown-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">8</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_function_unknown_error</span><span class="p">():</span>
        <span class="mi">9</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">10</span><span class="p">:</span>         <span class="k">raise</span> <span class="n">MyException</span><span class="p">(</span><span class="s2">&quot;Some informative message about an unknown exception.&quot;</span><span class="p">)</span>
       <span class="mi">11</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">MyException</span><span class="p">:</span> <span class="o">&lt;</span><span class="k">class</span> <span class="nc">test_unknown_error</span><span class="o">.</span><span class="n">MyException</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="zerodivisionerror-1">
<h2>ZeroDivisionError - 1<a class="headerlink" href="#zerodivisionerror-1" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_zero_division_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_zero_division_error</span>
    <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>
<span class="gr">ZeroDivisionError</span>: <span class="n">division by zero</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> occurs when you are attempting to divide
a value by zero:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">/</span> <span class="pre">0.</span></code>
It can also happen if you calculate the remainder of a division
using the modulo operator <code class="docutils literal notranslate"><span class="pre">%</span></code>:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">%</span> <span class="pre">0</span></code></p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-zero-division-error-py">
<h3>Exception raised on line 6 of file TESTS:\runtime\test_zero_division_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-zero-division-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_zero_division_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="zerodivisionerror-2">
<h2>ZeroDivisionError - 2<a class="headerlink" href="#zerodivisionerror-2" title="Permalink to this headline">¶</a></h2>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_zero_division_error.py&quot;</span>, line <span class="m">21</span>, in <span class="n">test_zero_division_error2</span>
    <span class="mi">1</span> <span class="o">%</span> <span class="n">zero</span>
<span class="gr">ZeroDivisionError</span>: <span class="n">integer division or modulo by zero</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> occurs when you are attempting to divide
a value by zero:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">/</span> <span class="pre">0.</span></code>
It can also happen if you calculate the remainder of a division
using the modulo operator <code class="docutils literal notranslate"><span class="pre">%</span></code>:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">%</span> <span class="pre">0</span></code></p>
<div class="section" id="exception-raised-on-line-21-of-file-tests-runtime-test-zero-division-error-py">
<h3>Exception raised on line 21 of file TESTS:\runtime\test_zero_division_error.py.<a class="headerlink" href="#exception-raised-on-line-21-of-file-tests-runtime-test-zero-division-error-py" title="Permalink to this headline">¶</a></h3>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">19</span><span class="p">:</span>     <span class="n">zero</span> <span class="o">=</span> <span class="mi">0</span>
       <span class="mi">20</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">21</span><span class="p">:</span>         <span class="mi">1</span> <span class="o">%</span> <span class="n">zero</span>
       <span class="mi">22</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">zero</span><span class="p">:</span> <span class="mi">0</span>
</pre></div>
</div>
</div>
</div>
</div>


           </div>
           
          </div>
          <footer>
  
    <div class="rst-footer-buttons" role="navigation" aria-label="footer navigation">
      
        <a href="tracebacks_syntax_markdown.html" class="btn btn-neutral float-right" title="Syntax errors - markdown_docs format" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="compare.html" class="btn btn-neutral float-left" title="Comparison between Python versions: SyntaxErrors" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
    </div>
  

  <hr/>

  <div role="contentinfo">
    <p>
        
        &copy; Copyright 2019, André Roberge

    </p>
  </div>
    
    
    
    Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a
    
    <a href="https://github.com/rtfd/sphinx_rtd_theme">theme</a>
    
    provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  

  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script>

  
  
    
   

</body>
</html>