

<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>Friendly tracebacks - markdown_docs format &mdash; Friendly tracebacks 0.1.1a documentation</title>
  

  
  <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />

  
  
  
  

  
  <!--[if lt IE 9]>
    <script src="_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
    
      <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
        <script src="_static/jquery.js"></script>
        <script src="_static/underscore.js"></script>
        <script src="_static/doctools.js"></script>
        <script src="_static/language_data.js"></script>
    
    <script type="text/javascript" src="_static/js/theme.js"></script>

    
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="Syntax errors - markdown_docs format" href="tracebacks_syntax_markdown.html" />
    <link rel="prev" title="Comparison between Python versions: SyntaxErrors" href="compare.html" /> 
</head>

<body class="wy-body-for-nav">

   
  <div class="wy-grid-for-nav">
    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
          

          
            <a href="index.html" class="icon icon-home" alt="Documentation Home"> Friendly tracebacks
          

          
          </a>

          
            
            
              <div class="version">
                0.1.1a
              </div>
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        
        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
              
            
            
              <p class="caption"><span class="caption-text">For beginners and teachers</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="usage.html">Usage</a></li>
<li class="toctree-l1"><a class="reference internal" href="thonny.html">Using with Thonny</a></li>
<li class="toctree-l1"><a class="reference internal" href="mu.html">Using with Mu</a></li>
</ul>
<p class="caption"><span class="caption-text">Thoughts on design</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="design.html">Some thoughts on the design of friendly-traceback</a></li>
<li class="toctree-l1"><a class="reference internal" href="verbosity.html">Verbosity: how much information do we want?</a></li>
</ul>
<p class="caption"><span class="caption-text">More advanced users</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="usage_adv.html">Advanced Usage</a></li>
</ul>
<p class="caption"><span class="caption-text">Use in your project</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="lies.html">Intentional lies</a></li>
<li class="toctree-l1"><a class="reference internal" href="api.html">Public API</a></li>
<li class="toctree-l1"><a class="reference internal" href="graph.html">Project files</a></li>
</ul>
<p class="caption"><span class="caption-text">Contribute</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="suggest.html">Suggest an addition</a></li>
<li class="toctree-l1"><a class="reference internal" href="adding_exception.html">Developer: Add a new Exception case</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_error.html">Developer: Add a new SyntaxError case</a></li>
<li class="toctree-l1"><a class="reference internal" href="translation_notes.html">Notes on translations - using gettext</a></li>
</ul>
<p class="caption"><span class="caption-text">All the tracebacks!</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="known.html">Known exceptions</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.6.html">Friendly tracebacks - Python 3.6 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.6.html">SyntaxError - Python 3.6 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.7.html">Friendly tracebacks - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.7.html">SyntaxError - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.8.html">Friendly tracebacks - Python 3.8 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.8.html">SyntaxError - Python 3.8 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.9.html">Friendly tracebacks - Python 3.9 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.9.html">SyntaxError - Python 3.9 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.10.html">Friendly tracebacks - Python 3.10 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.10.html">SyntaxError - Python 3.10 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="compare_exceptions.html">Comparing Exception messages between Python versions</a></li>
<li class="toctree-l1"><a class="reference internal" href="compare.html">Comparison between Python versions: SyntaxErrors</a></li>
</ul>
<p class="caption"><span class="caption-text">Markdown examples</span></p>
<ul class="current">
<li class="toctree-l1 current"><a class="current reference internal" href="#">Friendly tracebacks - markdown_docs format</a><ul>
<li class="toctree-l2"><a class="reference internal" href="#arithmeticerror">ArithmeticError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#python-exception">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-9-of-file-tests-except-test-arithmetic-error-py">Exception raised on line 9 of file ‘TESTS:\except\test_arithmetic_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-class-attribute">AttributeError - class attribute</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id1">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#likely-cause-based-on-the-information-given-by-python">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-10-of-file-tests-except-test-attribute-error-py">Exception raised on line 10 of file ‘TESTS:\except\test_attribute_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-typo-in-module-attribute">AttributeError - typo in module attribute</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id3">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id4">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-25-of-file-tests-except-test-attribute-error-py">Exception raised on line 25 of file ‘TESTS:\except\test_attribute_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror-typo-in-module-attribute-2">AttributeError - typo in module attribute 2</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id6">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id7">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-40-of-file-tests-except-test-attribute-error-py">Exception raised on line 40 of file ‘TESTS:\except\test_attribute_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#filenotfounderror">FileNotFoundError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id9">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id10">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-except-test-file-not-found-error-py">Exception raised on line 6 of file ‘TESTS:\except\test_file_not_found_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#importerror">ImportError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id12">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id13">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-except-test-import-error-py">Exception raised on line 6 of file ‘TESTS:\except\test_import_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#keyerror">KeyError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id14">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id15">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-7-of-file-tests-except-test-key-error-py">Exception raised on line 7 of file ‘TESTS:\except\test_key_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#lookuperror">LookupError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id17">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-10-of-file-tests-except-test-lookup-error-py">Exception raised on line 10 of file ‘TESTS:\except\test_lookup_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#indexerror-short-tuple">IndexError - short tuple</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id19">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-8-of-file-tests-except-test-index-error-py">Exception raised on line 8 of file ‘TESTS:\except\test_index_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#indexerror-long-list">IndexError - long list</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id21">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-21-of-file-tests-except-test-index-error-py">Exception raised on line 21 of file ‘TESTS:\except\test_index_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#modulenotfounderror">ModuleNotFoundError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id23">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id24">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-except-test-module-not-found-error-py">Exception raised on line 6 of file ‘TESTS:\except\test_module_not_found_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror-1">NameError - 1</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id25">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id26">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-except-test-name-error-py">Exception raised on line 6 of file ‘TESTS:\except\test_name_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror-2">NameError - 2</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id27">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id28">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-19-of-file-tests-except-test-name-error-py">Exception raised on line 19 of file ‘TESTS:\except\test_name_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror-3">NameError - 3</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id29">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id30">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-33-of-file-tests-except-test-name-error-py">Exception raised on line 33 of file ‘TESTS:\except\test_name_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror-4">NameError - 4</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id31">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id32">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-45-of-file-tests-except-test-name-error-py">Exception raised on line 45 of file ‘TESTS:\except\test_name_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#overflowerror">OverflowError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id33">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-except-test-overflow-error-py">Exception raised on line 6 of file ‘TESTS:\except\test_overflow_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#recursionerror">RecursionError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id34">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#execution-stopped-on-line-8-of-file-tests-except-test-recursion-error-py">Execution stopped on line 8 of file ‘TESTS:\except\test_recursion_error.py’.</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-except-test-recursion-error-py">Exception raised on line 6 of file ‘TESTS:\except\test_recursion_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-1-concatenate-two-different-types">TypeError - 1: concatenate two different types</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id37">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id38">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-8-of-file-tests-except-test-type-error-py">Exception raised on line 8 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-1a-concatenate-two-different-types">TypeError - 1a: concatenate two different types</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id40">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id41">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-25-of-file-tests-except-test-type-error-py">Exception raised on line 25 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-1b-concatenate-two-different-types">TypeError - 1b: concatenate two different types</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id43">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id44">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-42-of-file-tests-except-test-type-error-py">Exception raised on line 42 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-2-unsupported-operand-type-s-for">TypeError - 2: unsupported operand type(s) for +</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id46">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id47">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-57-of-file-tests-except-test-type-error-py">Exception raised on line 57 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-2a-unsupported-operand-type-s-for">TypeError - 2a: unsupported operand type(s) for +=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id49">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id50">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-72-of-file-tests-except-test-type-error-py">Exception raised on line 72 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-3-unsupported-operand-type-s-for">TypeError - 3: unsupported operand type(s) for -</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id52">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id53">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-87-of-file-tests-except-test-type-error-py">Exception raised on line 87 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-3a-unsupported-operand-type-s-for">TypeError - 3a: unsupported operand type(s) for -=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id55">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id56">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-102-of-file-tests-except-test-type-error-py">Exception raised on line 102 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-4-unsupported-operand-type-s-for">TypeError - 4: unsupported operand type(s) for *</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id58">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id59">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-117-of-file-tests-except-test-type-error-py">Exception raised on line 117 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-4a-unsupported-operand-type-s-for">TypeError - 4a: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">*=</span></code></a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id61">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id62">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-132-of-file-tests-except-test-type-error-py">Exception raised on line 132 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-5-unsupported-operand-type-s-for">TypeError - 5: unsupported operand type(s) for /</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id64">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id65">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-147-of-file-tests-except-test-type-error-py">Exception raised on line 147 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-5a-unsupported-operand-type-s-for">TypeError - 5a: unsupported operand type(s) for /=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id67">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id68">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-162-of-file-tests-except-test-type-error-py">Exception raised on line 162 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-5b-unsupported-operand-type-s-for">TypeError - 5b: unsupported operand type(s) for //</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id70">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id71">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-177-of-file-tests-except-test-type-error-py">Exception raised on line 177 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-5c-unsupported-operand-type-s-for">TypeError - 5c: unsupported operand type(s) for //=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id73">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id74">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-192-of-file-tests-except-test-type-error-py">Exception raised on line 192 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-6-unsupported-operand-type-s-for">TypeError - 6: unsupported operand type(s) for &amp;</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id76">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id77">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-207-of-file-tests-except-test-type-error-py">Exception raised on line 207 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-6a-unsupported-operand-type-s-for">TypeError - 6a: unsupported operand type(s) for &amp;=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id79">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id80">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-222-of-file-tests-except-test-type-error-py">Exception raised on line 222 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-7-unsupported-operand-type-s-for">TypeError - 7: unsupported operand type(s) for **</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id82">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id83">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-237-of-file-tests-except-test-type-error-py">Exception raised on line 237 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-7a-unsupported-operand-type-s-for">TypeError - 7a: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">**=</span></code></a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id85">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id86">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-252-of-file-tests-except-test-type-error-py">Exception raised on line 252 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-8-unsupported-operand-type-s-for">TypeError - 8: unsupported operand type(s) for &gt;&gt;</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id88">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id89">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-267-of-file-tests-except-test-type-error-py">Exception raised on line 267 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-8a-unsupported-operand-type-s-for">TypeError - 8a: unsupported operand type(s) for &gt;&gt;=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id91">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id92">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-282-of-file-tests-except-test-type-error-py">Exception raised on line 282 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-9-unsupported-operand-type-s-for">TypeError - 9: unsupported operand type(s) for &#64;</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id94">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id95">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-297-of-file-tests-except-test-type-error-py">Exception raised on line 297 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-9a-unsupported-operand-type-s-for">TypeError - 9a: unsupported operand type(s) for &#64;=</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id97">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id98">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-312-of-file-tests-except-test-type-error-py">Exception raised on line 312 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-10-comparison-between-incompatible-types">TypeError - 10: comparison between incompatible types</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id100">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id101">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-327-of-file-tests-except-test-type-error-py">Exception raised on line 327 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-11-bad-operand-type-for-unary">TypeError - 11: bad operand type for unary +</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id103">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id104">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-340-of-file-tests-except-test-type-error-py">Exception raised on line 340 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-11a-bad-operand-type-for-unary">TypeError - 11a: bad operand type for unary -</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id105">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id106">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-354-of-file-tests-except-test-type-error-py">Exception raised on line 354 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-11b-bad-operand-type-for-unary">TypeError - 11b: bad operand type for unary ~</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id107">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id108">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-368-of-file-tests-except-test-type-error-py">Exception raised on line 368 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-12-object-does-not-support-item-assignment">TypeError - 12: object does not support item assignment</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id109">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id110">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-383-of-file-tests-except-test-type-error-py">Exception raised on line 383 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-13-wrong-number-of-positional-arguments">TypeError - 13: wrong number of positional arguments</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id112">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id113">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-399-of-file-tests-except-test-type-error-py">Exception raised on line 399 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-14-missing-positional-arguments">TypeError - 14: missing positional arguments</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id115">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id116">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-435-of-file-tests-except-test-type-error-py">Exception raised on line 435 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-15-tuple-object-is-not-callable">TypeError - 15: tuple object is not callable</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id118">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id119">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-449-of-file-tests-except-test-type-error-py">Exception raised on line 449 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-15a-list-object-is-not-callable">TypeError - 15a: list object is not callable</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id120">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id121">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-462-of-file-tests-except-test-type-error-py">Exception raised on line 462 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror-16-exception-derived-from-baseexception">TypeError - 16: exception derived from BaseException</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id122">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id123">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-475-of-file-tests-except-test-type-error-py">Exception raised on line 475 of file ‘TESTS:\except\test_type_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#unboundlocalerror">UnboundLocalError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id124">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#id125">Likely cause based on the information given by Python</a></li>
<li class="toctree-l4"><a class="reference internal" href="#execution-stopped-on-line-21-of-file-tests-except-test-unbound-local-error-py">Execution stopped on line 21 of file ‘TESTS:\except\test_unbound_local_error.py’.</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-12-of-file-tests-except-test-unbound-local-error-py">Exception raised on line 12 of file ‘TESTS:\except\test_unbound_local_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#unknown-exception">Unknown exception</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id128">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-10-of-file-tests-except-test-unknown-error-py">Exception raised on line 10 of file ‘TESTS:\except\test_unknown_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#zerodivisionerror-1">ZeroDivisionError - 1</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id130">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-except-test-zero-division-error-py">Exception raised on line 6 of file ‘TESTS:\except\test_zero_division_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#zerodivisionerror-2">ZeroDivisionError - 2</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id131">Python exception</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-20-of-file-tests-except-test-zero-division-error-py">Exception raised on line 20 of file ‘TESTS:\except\test_zero_division_error.py’.</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_syntax_markdown.html">Syntax errors - markdown_docs format</a></li>
</ul>
<p class="caption"><span class="caption-text">En français</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_fr.html"> Friendly tracebacks - en Français</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_fr.html"> Friendly SyntaxError tracebacks - en Français</a></li>
</ul>
<p class="caption"><span class="caption-text">varia</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="changelog.html">Change Log</a></li>
</ul>

            
          
        </div>
        
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="index.html">Friendly tracebacks</a>
        
      </nav>


      <div class="wy-nav-content">
        
        <div class="rst-content style-external-links">
        
          















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">
    
      <li><a href="index.html" class="icon icon-home"></a> &raquo;</li>
        
      <li>Friendly tracebacks - markdown_docs format</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
            
            <a href="_sources/tracebacks_markdown.md.txt" rel="nofollow"> View page source</a>
          
        
      </li>
    
  </ul>

  
  <div class="rst-breadcrumbs-buttons" role="navigation" aria-label="breadcrumb navigation">
      
        <a href="tracebacks_syntax_markdown.html" class="btn btn-neutral float-right" title="Syntax errors - markdown_docs format" accesskey="n">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="compare.html" class="btn btn-neutral float-left" title="Comparison between Python versions: SyntaxErrors" accesskey="p"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
  </div>
  
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <div class="section" id="friendly-tracebacks-markdown-docs-format">
<h1>Friendly tracebacks - markdown_docs format<a class="headerlink" href="#friendly-tracebacks-markdown-docs-format" title="Permalink to this headline">¶</a></h1>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The content of this page is generated by running
trb_english_markdown.py located in the <code class="docutils literal notranslate"><span class="pre">tests/</span></code> directory.
This needs to be done explicitly, independently of updating the
documentation using Sphinx.
</p>
</div><p>Friendly-traceback version: 0.1.1a
Python version: 3.8.4</p>
<hr class="docutils" />
<div class="section" id="arithmeticerror">
<h2>ArithmeticError<a class="headerlink" href="#arithmeticerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="python-exception">
<h3>Python exception<a class="headerlink" href="#python-exception" title="Permalink to this headline">¶</a></h3>
<p>ArithmeticError:</p>
<p><code class="docutils literal notranslate"><span class="pre">ArithmeticError</span></code> is the base class for those built-in exceptions
that are raised for various arithmetic errors.
It is unusual that you are seeing this exception;
normally, a more specific exception should have been raised.</p>
<div class="section" id="exception-raised-on-line-9-of-file-tests-except-test-arithmetic-error-py">
<h4>Exception raised on line 9 of file ‘TESTS:\except\test_arithmetic_error.py’.<a class="headerlink" href="#exception-raised-on-line-9-of-file-tests-except-test-arithmetic-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">7</span><span class="p">:</span>         <span class="c1"># Usually, a subclass such as ZeroDivisionError, etc., would</span>
        <span class="mi">8</span><span class="p">:</span>         <span class="c1"># likely be raised.</span>
    <span class="o">--&gt;</span> <span class="mi">9</span><span class="p">:</span>         <span class="k">raise</span> <span class="ne">ArithmeticError</span>
</pre></div>
</div>
<div class="section" id="known-identifiers">
<h5>Known identifiers<a class="headerlink" href="#known-identifiers" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    ArithmeticError: &lt;class &#39;ArithmeticError&#39;&gt;
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-class-attribute">
<h2>AttributeError - class attribute<a class="headerlink" href="#attributeerror-class-attribute" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id1">
<h3>Python exception<a class="headerlink" href="#id1" title="Permalink to this headline">¶</a></h3>
<p>AttributeError: type object ‘A’ has no attribute ‘x’</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<div class="section" id="likely-cause-based-on-the-information-given-by-python">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#likely-cause-based-on-the-information-given-by-python" title="Permalink to this headline">¶</a></h4>
<p>In your program, the object is <code class="docutils literal notranslate"><span class="pre">A</span></code> and the attribute is <code class="docutils literal notranslate"><span class="pre">x</span></code>.</p>
</div>
<div class="section" id="exception-raised-on-line-10-of-file-tests-except-test-attribute-error-py">
<h4>Exception raised on line 10 of file ‘TESTS:\except\test_attribute_error.py’.<a class="headerlink" href="#exception-raised-on-line-10-of-file-tests-except-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">8</span><span class="p">:</span>     <span class="n">A</span><span class="p">()</span>
        <span class="mi">9</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">10</span><span class="p">:</span>         <span class="n">A</span><span class="o">.</span><span class="n">x</span>
</pre></div>
</div>
<div class="section" id="id2">
<h5>Known identifiers<a class="headerlink" href="#id2" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    A: &lt;class &#39;test_attribute_error.test_attrib...&gt;
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-typo-in-module-attribute">
<h2>AttributeError - typo in module attribute<a class="headerlink" href="#attributeerror-typo-in-module-attribute" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id3">
<h3>Python exception<a class="headerlink" href="#id3" title="Permalink to this headline">¶</a></h3>
<p>AttributeError: module ‘string’ has no attribute ‘ascii_lowecase’</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<div class="section" id="id4">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id4" title="Permalink to this headline">¶</a></h4>
<p>Perhaps you meant to write <code class="docutils literal notranslate"><span class="pre">ascii_lowercase</span></code> instead of <code class="docutils literal notranslate"><span class="pre">ascii_lowecase</span></code></p>
</div>
<div class="section" id="exception-raised-on-line-25-of-file-tests-except-test-attribute-error-py">
<h4>Exception raised on line 25 of file ‘TESTS:\except\test_attribute_error.py’.<a class="headerlink" href="#exception-raised-on-line-25-of-file-tests-except-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">23</span><span class="p">:</span> 
       <span class="mi">24</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">25</span><span class="p">:</span>         <span class="n">string</span><span class="o">.</span><span class="n">ascii_lowecase</span>
</pre></div>
</div>
<div class="section" id="id5">
<h5>Known identifiers<a class="headerlink" href="#id5" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">string</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">module</span> <span class="s1">&#39;string&#39;</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror-typo-in-module-attribute-2">
<h2>AttributeError - typo in module attribute 2<a class="headerlink" href="#attributeerror-typo-in-module-attribute-2" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id6">
<h3>Python exception<a class="headerlink" href="#id6" title="Permalink to this headline">¶</a></h3>
<p>AttributeError: module ‘math’ has no attribute ‘cost’</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<div class="section" id="id7">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id7" title="Permalink to this headline">¶</a></h4>
<p>Instead of writing <code class="docutils literal notranslate"><span class="pre">cost</span></code>, perhaps you meant one of the following:
[<code class="docutils literal notranslate"><span class="pre">cos</span></code>, <code class="docutils literal notranslate"><span class="pre">cosh</span></code>, <code class="docutils literal notranslate"><span class="pre">acos</span></code>]</p>
</div>
<div class="section" id="exception-raised-on-line-40-of-file-tests-except-test-attribute-error-py">
<h4>Exception raised on line 40 of file ‘TESTS:\except\test_attribute_error.py’.<a class="headerlink" href="#exception-raised-on-line-40-of-file-tests-except-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">38</span><span class="p">:</span> 
       <span class="mi">39</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">40</span><span class="p">:</span>         <span class="n">math</span><span class="o">.</span><span class="n">cost</span>
</pre></div>
</div>
<div class="section" id="id8">
<h5>Known identifiers<a class="headerlink" href="#id8" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">math</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">module</span> <span class="s1">&#39;math&#39;</span> <span class="p">(</span><span class="n">built</span><span class="o">-</span><span class="ow">in</span><span class="p">)</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="filenotfounderror">
<h2>FileNotFoundError<a class="headerlink" href="#filenotfounderror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id9">
<h3>Python exception<a class="headerlink" href="#id9" title="Permalink to this headline">¶</a></h3>
<p>FileNotFoundError: [Errno 2] No such file or directory: ‘does_not_exist’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">FileNotFoundError</span></code> exception indicates that you
are trying to open a file that cannot be found by Python.
This could be because you misspelled the name of the file.</p>
<div class="section" id="id10">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id10" title="Permalink to this headline">¶</a></h4>
<p>In your program, the name of the
file that cannot be found is <code class="docutils literal notranslate"><span class="pre">does_not_exist</span></code>.</p>
</div>
<div class="section" id="exception-raised-on-line-6-of-file-tests-except-test-file-not-found-error-py">
<h4>Exception raised on line 6 of file ‘TESTS:\except\test_file_not_found_error.py’.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-except-test-file-not-found-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_file_not_found_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="nb">open</span><span class="p">(</span><span class="s2">&quot;does_not_exist&quot;</span><span class="p">)</span>
</pre></div>
</div>
<div class="section" id="id11">
<h5>Known identifiers<a class="headerlink" href="#id11" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="nb">open</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">built</span><span class="o">-</span><span class="ow">in</span> <span class="n">function</span> <span class="nb">open</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="importerror">
<h2>ImportError<a class="headerlink" href="#importerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id12">
<h3>Python exception<a class="headerlink" href="#id12" title="Permalink to this headline">¶</a></h3>
<p>ImportError: cannot import name ‘Pi’ from ‘math’ (unknown location)</p>
<p>An <code class="docutils literal notranslate"><span class="pre">ImportError</span></code> exception indicates that a certain object could not
be imported from a module or package. Most often, this is
because the name of the object is not spelled correctly.</p>
<div class="section" id="id13">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id13" title="Permalink to this headline">¶</a></h4>
<p>The object that could not be imported is <code class="docutils literal notranslate"><span class="pre">Pi</span></code>.
The module or package where it was
expected to be found is <code class="docutils literal notranslate"><span class="pre">math</span></code>.</p>
</div>
<div class="section" id="exception-raised-on-line-6-of-file-tests-except-test-import-error-py">
<h4>Exception raised on line 6 of file ‘TESTS:\except\test_import_error.py’.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-except-test-import-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_import_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="kn">from</span> <span class="nn">math</span> <span class="kn">import</span> <span class="n">Pi</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="keyerror">
<h2>KeyError<a class="headerlink" href="#keyerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id14">
<h3>Python exception<a class="headerlink" href="#id14" title="Permalink to this headline">¶</a></h3>
<p>KeyError: ‘c’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">KeyError</span></code> is raised when a value is not found as a
key in a Python dict.</p>
<div class="section" id="id15">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id15" title="Permalink to this headline">¶</a></h4>
<p>In your program, the name of the key
that cannot be found is <code class="docutils literal notranslate"><span class="pre">c</span></code>.</p>
</div>
<div class="section" id="exception-raised-on-line-7-of-file-tests-except-test-key-error-py">
<h4>Exception raised on line 7 of file ‘TESTS:\except\test_key_error.py’.<a class="headerlink" href="#exception-raised-on-line-7-of-file-tests-except-test-key-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">5</span><span class="p">:</span>     <span class="n">d</span> <span class="o">=</span> <span class="p">{</span><span class="s2">&quot;a&quot;</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="s2">&quot;b&quot;</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">6</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">7</span><span class="p">:</span>         <span class="n">d</span><span class="p">[</span><span class="s2">&quot;c&quot;</span><span class="p">]</span>
</pre></div>
</div>
<div class="section" id="id16">
<h5>Known identifiers<a class="headerlink" href="#id16" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">d</span><span class="p">:</span> <span class="p">{</span><span class="s1">&#39;a&#39;</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="s1">&#39;b&#39;</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="lookuperror">
<h2>LookupError<a class="headerlink" href="#lookuperror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id17">
<h3>Python exception<a class="headerlink" href="#id17" title="Permalink to this headline">¶</a></h3>
<p>LookupError:</p>
<p><code class="docutils literal notranslate"><span class="pre">LookupError</span></code> is the base class for the exceptions that are raised
when a key or index used on a mapping or sequence is invalid.
It can also be raised directly by codecs.lookup().</p>
<div class="section" id="exception-raised-on-line-10-of-file-tests-except-test-lookup-error-py">
<h4>Exception raised on line 10 of file ‘TESTS:\except\test_lookup_error.py’.<a class="headerlink" href="#exception-raised-on-line-10-of-file-tests-except-test-lookup-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">8</span><span class="p">:</span>         <span class="c1"># other than possibly codecs.lookup(), which is why we raise</span>
        <span class="mi">9</span><span class="p">:</span>         <span class="c1"># it directly here for our example.</span>
    <span class="o">--&gt;</span><span class="mi">10</span><span class="p">:</span>         <span class="k">raise</span> <span class="ne">LookupError</span>
</pre></div>
</div>
<div class="section" id="id18">
<h5>Known identifiers<a class="headerlink" href="#id18" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    LookupError: &lt;class &#39;LookupError&#39;&gt;
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="indexerror-short-tuple">
<h2>IndexError - short tuple<a class="headerlink" href="#indexerror-short-tuple" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id19">
<h3>Python exception<a class="headerlink" href="#id19" title="Permalink to this headline">¶</a></h3>
<p>IndexError: tuple index out of range</p>
<p>An <code class="docutils literal notranslate"><span class="pre">IndexError</span></code> occurs when you are try to get an item from a list,
a tuple, or a similar object (sequence), by using an index which
does not exists; typically, this is because the index you give
is greater than the length of the sequence.
Reminder: the first item of a sequence is at index 0.</p>
<div class="section" id="exception-raised-on-line-8-of-file-tests-except-test-index-error-py">
<h4>Exception raised on line 8 of file ‘TESTS:\except\test_index_error.py’.<a class="headerlink" href="#exception-raised-on-line-8-of-file-tests-except-test-index-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">6</span><span class="p">:</span>     <span class="n">b</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
        <span class="mi">7</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span> <span class="mi">8</span><span class="p">:</span>         <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">3</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">2</span><span class="p">])</span>
</pre></div>
</div>
<div class="section" id="id20">
<h5>Known identifiers<a class="headerlink" href="#id20" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="nb">print</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">built</span><span class="o">-</span><span class="ow">in</span> <span class="n">function</span> <span class="nb">print</span><span class="o">&gt;</span>
    <span class="n">a</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
    <span class="n">b</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="indexerror-long-list">
<h2>IndexError - long list<a class="headerlink" href="#indexerror-long-list" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id21">
<h3>Python exception<a class="headerlink" href="#id21" title="Permalink to this headline">¶</a></h3>
<p>IndexError: list index out of range</p>
<p>An <code class="docutils literal notranslate"><span class="pre">IndexError</span></code> occurs when you are try to get an item from a list,
a tuple, or a similar object (sequence), by using an index which
does not exists; typically, this is because the index you give
is greater than the length of the sequence.
Reminder: the first item of a sequence is at index 0.</p>
<div class="section" id="exception-raised-on-line-21-of-file-tests-except-test-index-error-py">
<h4>Exception raised on line 21 of file ‘TESTS:\except\test_index_error.py’.<a class="headerlink" href="#exception-raised-on-line-21-of-file-tests-except-test-index-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">19</span><span class="p">:</span>     <span class="n">b</span> <span class="o">=</span> <span class="nb">tuple</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">50</span><span class="p">))</span>
       <span class="mi">20</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">21</span><span class="p">:</span>         <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">50</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span>
</pre></div>
</div>
<div class="section" id="id22">
<h5>Known identifiers<a class="headerlink" href="#id22" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="nb">print</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">built</span><span class="o">-</span><span class="ow">in</span> <span class="n">function</span> <span class="nb">print</span><span class="o">&gt;</span>
    <span class="n">a</span><span class="p">:</span> <span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="mf">1.</span><span class="o">..</span><span class="p">]</span>  <span class="o">|</span> <span class="nb">len</span><span class="p">(</span><span class="n">a</span><span class="p">):</span> <span class="mi">40</span>
    <span class="n">b</span><span class="p">:</span> <span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="mf">1.</span><span class="o">..</span><span class="p">)</span>  <span class="o">|</span> <span class="nb">len</span><span class="p">(</span><span class="n">b</span><span class="p">):</span> <span class="mi">50</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="modulenotfounderror">
<h2>ModuleNotFoundError<a class="headerlink" href="#modulenotfounderror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id23">
<h3>Python exception<a class="headerlink" href="#id23" title="Permalink to this headline">¶</a></h3>
<p>ModuleNotFoundError: No module named ‘does_not_exist’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">ModuleNotFoundError</span></code> exception indicates that you
are trying to import a module that cannot be found by Python.
This could be because you misspelled the name of the module
or because it is not installed on your computer.</p>
<div class="section" id="id24">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id24" title="Permalink to this headline">¶</a></h4>
<p>In your program, the name of the
module that cannot be found is <code class="docutils literal notranslate"><span class="pre">does_not_exist</span></code>.</p>
</div>
<div class="section" id="exception-raised-on-line-6-of-file-tests-except-test-module-not-found-error-py">
<h4>Exception raised on line 6 of file ‘TESTS:\except\test_module_not_found_error.py’.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-except-test-module-not-found-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_module_not_found_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="kn">import</span> <span class="nn">does_not_exist</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="nameerror-1">
<h2>NameError - 1<a class="headerlink" href="#nameerror-1" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id25">
<h3>Python exception<a class="headerlink" href="#id25" title="Permalink to this headline">¶</a></h3>
<p>NameError: name ‘something’ is not defined</p>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<div class="section" id="id26">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id26" title="Permalink to this headline">¶</a></h4>
<p>In your program, the unknown name is <code class="docutils literal notranslate"><span class="pre">something</span></code>.</p>
</div>
<div class="section" id="exception-raised-on-line-6-of-file-tests-except-test-name-error-py">
<h4>Exception raised on line 6 of file ‘TESTS:\except\test_name_error.py’.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-except-test-name-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_name_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="n">this</span> <span class="o">=</span> <span class="n">something</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="nameerror-2">
<h2>NameError - 2<a class="headerlink" href="#nameerror-2" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id27">
<h3>Python exception<a class="headerlink" href="#id27" title="Permalink to this headline">¶</a></h3>
<p>NameError: name ‘babs’ is not defined</p>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<div class="section" id="id28">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id28" title="Permalink to this headline">¶</a></h4>
<p>In your program, the unknown name is <code class="docutils literal notranslate"><span class="pre">babs</span></code>.
Instead of writing <code class="docutils literal notranslate"><span class="pre">babs</span></code>, perhaps you meant one of the following:</p>
<ul class="simple">
<li><p>Local scope: <code class="docutils literal notranslate"><span class="pre">nabs</span></code></p></li>
<li><p>Global scope: <code class="docutils literal notranslate"><span class="pre">fabs</span></code></p></li>
<li><p>Python builtins: <code class="docutils literal notranslate"><span class="pre">abs</span></code></p></li>
</ul>
</div>
<div class="section" id="exception-raised-on-line-19-of-file-tests-except-test-name-error-py">
<h4>Exception raised on line 19 of file ‘TESTS:\except\test_name_error.py’.<a class="headerlink" href="#exception-raised-on-line-19-of-file-tests-except-test-name-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">17</span><span class="p">:</span>     <span class="n">nabs</span> <span class="o">=</span> <span class="mi">1</span>
       <span class="mi">18</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">19</span><span class="p">:</span>         <span class="n">x</span> <span class="o">=</span> <span class="n">babs</span><span class="p">(</span><span class="o">-</span><span class="mi">1</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="nameerror-3">
<h2>NameError - 3<a class="headerlink" href="#nameerror-3" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id29">
<h3>Python exception<a class="headerlink" href="#id29" title="Permalink to this headline">¶</a></h3>
<p>NameError: name ‘x’ is not defined</p>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<div class="section" id="id30">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id30" title="Permalink to this headline">¶</a></h4>
<p>In your program, the unknown name is <code class="docutils literal notranslate"><span class="pre">x</span></code>.
A type hint found for <code class="docutils literal notranslate"><span class="pre">x</span></code> in the global scope.
Perhaps you had written <code class="docutils literal notranslate"><span class="pre">x</span> <span class="pre">:</span> <span class="pre">3</span></code> instead of <code class="docutils literal notranslate"><span class="pre">x</span> <span class="pre">=</span> <span class="pre">3</span></code>.</p>
</div>
<div class="section" id="exception-raised-on-line-33-of-file-tests-except-test-name-error-py">
<h4>Exception raised on line 33 of file ‘TESTS:\except\test_name_error.py’.<a class="headerlink" href="#exception-raised-on-line-33-of-file-tests-except-test-name-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">31</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_name_error3</span><span class="p">():</span>
       <span class="mi">32</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">33</span><span class="p">:</span>         <span class="n">y</span> <span class="o">=</span> <span class="n">x</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="nameerror-4">
<h2>NameError - 4<a class="headerlink" href="#nameerror-4" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id31">
<h3>Python exception<a class="headerlink" href="#id31" title="Permalink to this headline">¶</a></h3>
<p>NameError: name ‘cost’ is not defined</p>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<div class="section" id="id32">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id32" title="Permalink to this headline">¶</a></h4>
<p>In your program, the unknown name is <code class="docutils literal notranslate"><span class="pre">cost</span></code>.
Instead of writing <code class="docutils literal notranslate"><span class="pre">cost</span></code>, perhaps you meant one of the following:</p>
<ul class="simple">
<li><p>Global scope: <code class="docutils literal notranslate"><span class="pre">cos</span></code>, <code class="docutils literal notranslate"><span class="pre">cosh</span></code>, <code class="docutils literal notranslate"><span class="pre">acos</span></code></p></li>
</ul>
</div>
<div class="section" id="exception-raised-on-line-45-of-file-tests-except-test-name-error-py">
<h4>Exception raised on line 45 of file ‘TESTS:\except\test_name_error.py’.<a class="headerlink" href="#exception-raised-on-line-45-of-file-tests-except-test-name-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">43</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_name_error4</span><span class="p">():</span>
       <span class="mi">44</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">45</span><span class="p">:</span>         <span class="n">cost</span>  <span class="c1"># wrote from math import * above</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="overflowerror">
<h2>OverflowError<a class="headerlink" href="#overflowerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id33">
<h3>Python exception<a class="headerlink" href="#id33" title="Permalink to this headline">¶</a></h3>
<p>OverflowError: (34, ‘Result too large’)</p>
<p>An <code class="docutils literal notranslate"><span class="pre">OverflowError</span></code> is raised when the result of an arithmetic operation
is too large to be handled by the computer’s processor.</p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-except-test-overflow-error-py">
<h4>Exception raised on line 6 of file ‘TESTS:\except\test_overflow_error.py’.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-except-test-overflow-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_overflow_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="mf">2.0</span> <span class="o">**</span> <span class="mi">1600</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="recursionerror">
<h2>RecursionError<a class="headerlink" href="#recursionerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id34">
<h3>Python exception<a class="headerlink" href="#id34" title="Permalink to this headline">¶</a></h3>
<p>RecursionError: maximum recursion depth exceeded</p>
<p>A <code class="docutils literal notranslate"><span class="pre">RecursionError</span></code> is raised when a function calls itself,
directly or indirectly, too many times.
It almost always indicates that you made an error in your code
and that your program would never stop.</p>
<div class="section" id="execution-stopped-on-line-8-of-file-tests-except-test-recursion-error-py">
<h4>Execution stopped on line 8 of file ‘TESTS:\except\test_recursion_error.py’.<a class="headerlink" href="#execution-stopped-on-line-8-of-file-tests-except-test-recursion-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">6</span><span class="p">:</span>         <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
        <span class="mi">7</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span> <span class="mi">8</span><span class="p">:</span>         <span class="n">a</span><span class="p">()</span>
</pre></div>
</div>
<div class="section" id="id35">
<h5>Known identifiers<a class="headerlink" href="#id35" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">test_recursion_error</span><span class="o">.&lt;</span><span class="nb">locals</span><span class="o">&gt;.</span><span class="n">a</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="exception-raised-on-line-6-of-file-tests-except-test-recursion-error-py">
<h4>Exception raised on line 6 of file ‘TESTS:\except\test_recursion_error.py’.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-except-test-recursion-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_recursion_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">def</span> <span class="nf">a</span><span class="p">():</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
</pre></div>
</div>
<div class="section" id="id36">
<h5>Known identifiers<a class="headerlink" href="#id36" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">test_recursion_error</span><span class="o">.&lt;</span><span class="nb">locals</span><span class="o">&gt;.</span><span class="n">a</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-1-concatenate-two-different-types">
<h2>TypeError - 1: concatenate two different types<a class="headerlink" href="#typeerror-1-concatenate-two-different-types" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id37">
<h3>Python exception<a class="headerlink" href="#id37" title="Permalink to this headline">¶</a></h3>
<p>TypeError: can only concatenate str (not “int”) to str</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id38">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id38" title="Permalink to this headline">¶</a></h4>
<p>You tried to concatenate (add) two different types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-8-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 8 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-8-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">6</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
        <span class="mi">7</span><span class="p">:</span>         <span class="n">one</span> <span class="o">=</span> <span class="mi">1</span>
    <span class="o">--&gt;</span> <span class="mi">8</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">+</span> <span class="n">one</span>
</pre></div>
</div>
<div class="section" id="id39">
<h5>Known identifiers<a class="headerlink" href="#id39" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">one</span><span class="p">:</span> <span class="mi">1</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-1a-concatenate-two-different-types">
<h2>TypeError - 1a: concatenate two different types<a class="headerlink" href="#typeerror-1a-concatenate-two-different-types" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id40">
<h3>Python exception<a class="headerlink" href="#id40" title="Permalink to this headline">¶</a></h3>
<p>TypeError: can only concatenate str (not “list”) to str</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id41">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id41" title="Permalink to this headline">¶</a></h4>
<p>You tried to concatenate (add) two different types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and a <code class="docutils literal notranslate"><span class="pre">list</span></code></p>
</div>
<div class="section" id="exception-raised-on-line-25-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 25 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-25-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">23</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">24</span><span class="p">:</span>         <span class="n">a_list</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">25</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">+</span> <span class="n">a_list</span>
</pre></div>
</div>
<div class="section" id="id42">
<h5>Known identifiers<a class="headerlink" href="#id42" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">a_list</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-1b-concatenate-two-different-types">
<h2>TypeError - 1b: concatenate two different types<a class="headerlink" href="#typeerror-1b-concatenate-two-different-types" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id43">
<h3>Python exception<a class="headerlink" href="#id43" title="Permalink to this headline">¶</a></h3>
<p>TypeError: can only concatenate tuple (not “list”) to tuple</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id44">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id44" title="Permalink to this headline">¶</a></h4>
<p>You tried to concatenate (add) two different types of objects:
a <code class="docutils literal notranslate"><span class="pre">tuple</span></code> and a <code class="docutils literal notranslate"><span class="pre">list</span></code></p>
</div>
<div class="section" id="exception-raised-on-line-42-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 42 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-42-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">40</span><span class="p">:</span>         <span class="n">a_tuple</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
       <span class="mi">41</span><span class="p">:</span>         <span class="n">a_list</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">42</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a_tuple</span> <span class="o">+</span> <span class="n">a_list</span>
</pre></div>
</div>
<div class="section" id="id45">
<h5>Known identifiers<a class="headerlink" href="#id45" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a_tuple</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
    <span class="n">a_list</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-2-unsupported-operand-type-s-for">
<h2>TypeError - 2: unsupported operand type(s) for +<a class="headerlink" href="#typeerror-2-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id46">
<h3>Python exception<a class="headerlink" href="#id46" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for +: ‘int’ and ‘NoneType’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id47">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id47" title="Permalink to this headline">¶</a></h4>
<p>You tried to add two incompatible types of objects:
an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>) and a variable equal to <code class="docutils literal notranslate"><span class="pre">None</span></code> (<code class="docutils literal notranslate"><span class="pre">NoneType</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-57-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 57 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-57-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">55</span><span class="p">:</span>         <span class="n">one</span> <span class="o">=</span> <span class="mi">1</span>
       <span class="mi">56</span><span class="p">:</span>         <span class="n">none</span> <span class="o">=</span> <span class="kc">None</span>
    <span class="o">--&gt;</span><span class="mi">57</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">one</span> <span class="o">+</span> <span class="n">none</span>
</pre></div>
</div>
<div class="section" id="id48">
<h5>Known identifiers<a class="headerlink" href="#id48" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">one</span><span class="p">:</span> <span class="mi">1</span>
    <span class="n">none</span><span class="p">:</span> <span class="kc">None</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-2a-unsupported-operand-type-s-for">
<h2>TypeError - 2a: unsupported operand type(s) for +=<a class="headerlink" href="#typeerror-2a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id49">
<h3>Python exception<a class="headerlink" href="#id49" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for +=: ‘int’ and ‘str’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id50">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id50" title="Permalink to this headline">¶</a></h4>
<p>You tried to add two incompatible types of objects:
an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>) and a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-72-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 72 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-72-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">70</span><span class="p">:</span>         <span class="n">one</span> <span class="o">=</span> <span class="mi">1</span>
       <span class="mi">71</span><span class="p">:</span>         <span class="n">two</span> <span class="o">=</span> <span class="s2">&quot;two&quot;</span>
    <span class="o">--&gt;</span><span class="mi">72</span><span class="p">:</span>         <span class="n">one</span> <span class="o">+=</span> <span class="n">two</span>
</pre></div>
</div>
<div class="section" id="id51">
<h5>Known identifiers<a class="headerlink" href="#id51" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">one</span><span class="p">:</span> <span class="mi">1</span>
    <span class="n">two</span><span class="p">:</span> <span class="s1">&#39;two&#39;</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-3-unsupported-operand-type-s-for">
<h2>TypeError - 3: unsupported operand type(s) for -<a class="headerlink" href="#typeerror-3-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id52">
<h3>Python exception<a class="headerlink" href="#id52" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for -: ‘tuple’ and ‘list’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id53">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id53" title="Permalink to this headline">¶</a></h4>
<p>You tried to subtract two incompatible types of objects:
a <code class="docutils literal notranslate"><span class="pre">tuple</span></code> and a <code class="docutils literal notranslate"><span class="pre">list</span></code></p>
</div>
<div class="section" id="exception-raised-on-line-87-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 87 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-87-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">85</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">)</span>
       <span class="mi">86</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="p">[</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">87</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">-</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id54">
<h5>Known identifiers<a class="headerlink" href="#id54" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">)</span>
    <span class="n">b</span><span class="p">:</span> <span class="p">[</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-3a-unsupported-operand-type-s-for">
<h2>TypeError - 3a: unsupported operand type(s) for -=<a class="headerlink" href="#typeerror-3a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id55">
<h3>Python exception<a class="headerlink" href="#id55" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for -=: ‘list’ and ‘tuple’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id56">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id56" title="Permalink to this headline">¶</a></h4>
<p>You tried to subtract two incompatible types of objects:
a <code class="docutils literal notranslate"><span class="pre">list</span></code> and a <code class="docutils literal notranslate"><span class="pre">tuple</span></code></p>
</div>
<div class="section" id="exception-raised-on-line-102-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 102 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-102-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">100</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">)</span>
       <span class="mi">101</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="p">[</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">102</span><span class="p">:</span>         <span class="n">b</span> <span class="o">-=</span> <span class="n">a</span>
</pre></div>
</div>
<div class="section" id="id57">
<h5>Known identifiers<a class="headerlink" href="#id57" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="p">[</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">]</span>
    <span class="n">a</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-4-unsupported-operand-type-s-for">
<h2>TypeError - 4: unsupported operand type(s) for *<a class="headerlink" href="#typeerror-4-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id58">
<h3>Python exception<a class="headerlink" href="#id58" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for *: ‘complex’ and ‘set’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id59">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id59" title="Permalink to this headline">¶</a></h4>
<p>You tried to multiply two incompatible types of objects:
a complex number and a <code class="docutils literal notranslate"><span class="pre">set</span></code></p>
</div>
<div class="section" id="exception-raised-on-line-117-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 117 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-117-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">115</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="mi">1</span><span class="n">j</span>
       <span class="mi">116</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="p">{</span><span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">}</span>
    <span class="o">--&gt;</span><span class="mi">117</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">*</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id60">
<h5>Known identifiers<a class="headerlink" href="#id60" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="mi">1</span><span class="n">j</span>
    <span class="n">b</span><span class="p">:</span> <span class="p">{</span><span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">}</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-4a-unsupported-operand-type-s-for">
<h2>TypeError - 4a: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">*=</span></code><a class="headerlink" href="#typeerror-4a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id61">
<h3>Python exception<a class="headerlink" href="#id61" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for *=: ‘set’ and ‘complex’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id62">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id62" title="Permalink to this headline">¶</a></h4>
<p>You tried to multiply two incompatible types of objects:
a <code class="docutils literal notranslate"><span class="pre">set</span></code> and a complex number</p>
</div>
<div class="section" id="exception-raised-on-line-132-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 132 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-132-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">130</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="mi">1</span><span class="n">j</span>
       <span class="mi">131</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="p">{</span><span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">}</span>
    <span class="o">--&gt;</span><span class="mi">132</span><span class="p">:</span>         <span class="n">b</span> <span class="o">*=</span> <span class="n">a</span>
</pre></div>
</div>
<div class="section" id="id63">
<h5>Known identifiers<a class="headerlink" href="#id63" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="p">{</span><span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">}</span>
    <span class="n">a</span><span class="p">:</span> <span class="mi">1</span><span class="n">j</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-5-unsupported-operand-type-s-for">
<h2>TypeError - 5: unsupported operand type(s) for /<a class="headerlink" href="#typeerror-5-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id64">
<h3>Python exception<a class="headerlink" href="#id64" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for /: ‘dict’ and ‘float’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id65">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id65" title="Permalink to this headline">¶</a></h4>
<p>You tried to divide two incompatible types of objects:
a dictionary (<code class="docutils literal notranslate"><span class="pre">dict</span></code>) and a number (<code class="docutils literal notranslate"><span class="pre">float</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-147-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 147 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-147-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">145</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">146</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mf">3.1416</span>
    <span class="o">--&gt;</span><span class="mi">147</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">/</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id66">
<h5>Known identifiers<a class="headerlink" href="#id66" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
    <span class="n">b</span><span class="p">:</span> <span class="mf">3.1416</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-5a-unsupported-operand-type-s-for">
<h2>TypeError - 5a: unsupported operand type(s) for /=<a class="headerlink" href="#typeerror-5a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id67">
<h3>Python exception<a class="headerlink" href="#id67" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for /=: ‘float’ and ‘dict’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id68">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id68" title="Permalink to this headline">¶</a></h4>
<p>You tried to divide two incompatible types of objects:
a number (<code class="docutils literal notranslate"><span class="pre">float</span></code>) and a dictionary (<code class="docutils literal notranslate"><span class="pre">dict</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-162-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 162 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-162-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">160</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">161</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mf">3.1416</span>
    <span class="o">--&gt;</span><span class="mi">162</span><span class="p">:</span>         <span class="n">b</span> <span class="o">/=</span> <span class="n">a</span>
</pre></div>
</div>
<div class="section" id="id69">
<h5>Known identifiers<a class="headerlink" href="#id69" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="mf">3.1416</span>
    <span class="n">a</span><span class="p">:</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-5b-unsupported-operand-type-s-for">
<h2>TypeError - 5b: unsupported operand type(s) for //<a class="headerlink" href="#typeerror-5b-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id70">
<h3>Python exception<a class="headerlink" href="#id70" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for //: ‘dict’ and ‘int’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id71">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id71" title="Permalink to this headline">¶</a></h4>
<p>You tried to divide two incompatible types of objects:
a dictionary (<code class="docutils literal notranslate"><span class="pre">dict</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-177-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 177 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-177-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">175</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">176</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">1</span>
    <span class="o">--&gt;</span><span class="mi">177</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">//</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id72">
<h5>Known identifiers<a class="headerlink" href="#id72" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
    <span class="n">b</span><span class="p">:</span> <span class="mi">1</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-5c-unsupported-operand-type-s-for">
<h2>TypeError - 5c: unsupported operand type(s) for //=<a class="headerlink" href="#typeerror-5c-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id73">
<h3>Python exception<a class="headerlink" href="#id73" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for //=: ‘float’ and ‘dict’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id74">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id74" title="Permalink to this headline">¶</a></h4>
<p>You tried to divide two incompatible types of objects:
a number (<code class="docutils literal notranslate"><span class="pre">float</span></code>) and a dictionary (<code class="docutils literal notranslate"><span class="pre">dict</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-192-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 192 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-192-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">190</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">191</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mf">3.1416</span>
    <span class="o">--&gt;</span><span class="mi">192</span><span class="p">:</span>         <span class="n">b</span> <span class="o">//=</span> <span class="n">a</span>
</pre></div>
</div>
<div class="section" id="id75">
<h5>Known identifiers<a class="headerlink" href="#id75" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="mf">3.1416</span>
    <span class="n">a</span><span class="p">:</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-6-unsupported-operand-type-s-for">
<h2>TypeError - 6: unsupported operand type(s) for &amp;<a class="headerlink" href="#typeerror-6-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id76">
<h3>Python exception<a class="headerlink" href="#id76" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for &amp;: ‘str’ and ‘int’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id77">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id77" title="Permalink to this headline">¶</a></h4>
<p>You tried to perform the bitwise operation &amp;
on two incompatible types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-207-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 207 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-207-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">205</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">206</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">2</span>
    <span class="o">--&gt;</span><span class="mi">207</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">&amp;</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id78">
<h5>Known identifiers<a class="headerlink" href="#id78" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">b</span><span class="p">:</span> <span class="mi">2</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-6a-unsupported-operand-type-s-for">
<h2>TypeError - 6a: unsupported operand type(s) for &amp;=<a class="headerlink" href="#typeerror-6a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id79">
<h3>Python exception<a class="headerlink" href="#id79" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for &amp;=: ‘int’ and ‘str’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id80">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id80" title="Permalink to this headline">¶</a></h4>
<p>You tried to perform the bitwise operation &amp;=
on two incompatible types of objects:
an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>) and a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-222-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 222 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-222-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">220</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">221</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">2</span>
    <span class="o">--&gt;</span><span class="mi">222</span><span class="p">:</span>         <span class="n">b</span> <span class="o">&amp;=</span> <span class="n">a</span>
</pre></div>
</div>
<div class="section" id="id81">
<h5>Known identifiers<a class="headerlink" href="#id81" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="mi">2</span>
    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-7-unsupported-operand-type-s-for">
<h2>TypeError - 7: unsupported operand type(s) for **<a class="headerlink" href="#typeerror-7-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id82">
<h3>Python exception<a class="headerlink" href="#id82" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for ** or pow(): ‘dict’ and ‘float’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id83">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id83" title="Permalink to this headline">¶</a></h4>
<p>You tried to exponentiate (raise to a power)
using two incompatible types of objects:
a dictionary (<code class="docutils literal notranslate"><span class="pre">dict</span></code>) and a number (<code class="docutils literal notranslate"><span class="pre">float</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-237-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 237 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-237-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">235</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">236</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mf">3.1416</span>
    <span class="o">--&gt;</span><span class="mi">237</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">**</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id84">
<h5>Known identifiers<a class="headerlink" href="#id84" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
    <span class="n">b</span><span class="p">:</span> <span class="mf">3.1416</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-7a-unsupported-operand-type-s-for">
<h2>TypeError - 7a: unsupported operand type(s) for <code class="docutils literal notranslate"><span class="pre">**=</span></code><a class="headerlink" href="#typeerror-7a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id85">
<h3>Python exception<a class="headerlink" href="#id85" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for ** or pow(): ‘dict’ and ‘float’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id86">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id86" title="Permalink to this headline">¶</a></h4>
<p>You tried to exponentiate (raise to a power)
using two incompatible types of objects:
a dictionary (<code class="docutils literal notranslate"><span class="pre">dict</span></code>) and a number (<code class="docutils literal notranslate"><span class="pre">float</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-252-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 252 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-252-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">250</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">251</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mf">3.1416</span>
    <span class="o">--&gt;</span><span class="mi">252</span><span class="p">:</span>         <span class="n">a</span> <span class="o">**=</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id87">
<h5>Known identifiers<a class="headerlink" href="#id87" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">{</span><span class="mi">1</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
    <span class="n">b</span><span class="p">:</span> <span class="mf">3.1416</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-8-unsupported-operand-type-s-for">
<h2>TypeError - 8: unsupported operand type(s) for &gt;&gt;<a class="headerlink" href="#typeerror-8-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id88">
<h3>Python exception<a class="headerlink" href="#id88" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for &gt;&gt;: ‘str’ and ‘int’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id89">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id89" title="Permalink to this headline">¶</a></h4>
<p>You tried to perform the bit shifting operation &gt;&gt;
on two incompatible types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-267-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 267 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-267-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">265</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">266</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">42</span>
    <span class="o">--&gt;</span><span class="mi">267</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">&gt;&gt;</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id90">
<h5>Known identifiers<a class="headerlink" href="#id90" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">b</span><span class="p">:</span> <span class="mi">42</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-8a-unsupported-operand-type-s-for">
<h2>TypeError - 8a: unsupported operand type(s) for &gt;&gt;=<a class="headerlink" href="#typeerror-8a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id91">
<h3>Python exception<a class="headerlink" href="#id91" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for &gt;&gt;=: ‘str’ and ‘int’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id92">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id92" title="Permalink to this headline">¶</a></h4>
<p>You tried to perform the bit shifting operation &gt;&gt;=
on two incompatible types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-282-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 282 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-282-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">280</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">281</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">42</span>
    <span class="o">--&gt;</span><span class="mi">282</span><span class="p">:</span>         <span class="n">a</span> <span class="o">&gt;&gt;=</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id93">
<h5>Known identifiers<a class="headerlink" href="#id93" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">b</span><span class="p">:</span> <span class="mi">42</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-9-unsupported-operand-type-s-for">
<h2>TypeError - 9: unsupported operand type(s) for &#64;<a class="headerlink" href="#typeerror-9-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id94">
<h3>Python exception<a class="headerlink" href="#id94" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for &#64;: ‘str’ and ‘int’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id95">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id95" title="Permalink to this headline">¶</a></h4>
<p>You tried to use the operator &#64;
using two incompatible types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>).
This operator is normally used only
for multiplication of matrices.</p>
</div>
<div class="section" id="exception-raised-on-line-297-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 297 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-297-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">295</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">296</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">2</span>
    <span class="o">--&gt;</span><span class="mi">297</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a</span> <span class="o">@</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id96">
<h5>Known identifiers<a class="headerlink" href="#id96" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">b</span><span class="p">:</span> <span class="mi">2</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-9a-unsupported-operand-type-s-for">
<h2>TypeError - 9a: unsupported operand type(s) for &#64;=<a class="headerlink" href="#typeerror-9a-unsupported-operand-type-s-for" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id97">
<h3>Python exception<a class="headerlink" href="#id97" title="Permalink to this headline">¶</a></h3>
<p>TypeError: unsupported operand type(s) for &#64;=: ‘str’ and ‘int’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id98">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id98" title="Permalink to this headline">¶</a></h4>
<p>You tried to use the operator &#64;=
using two incompatible types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>).
This operator is normally used only
for multiplication of matrices.</p>
</div>
<div class="section" id="exception-raised-on-line-312-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 312 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-312-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">310</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">311</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">2</span>
    <span class="o">--&gt;</span><span class="mi">312</span><span class="p">:</span>         <span class="n">a</span> <span class="o">@=</span> <span class="n">b</span>
</pre></div>
</div>
<div class="section" id="id99">
<h5>Known identifiers<a class="headerlink" href="#id99" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">b</span><span class="p">:</span> <span class="mi">2</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-10-comparison-between-incompatible-types">
<h2>TypeError - 10: comparison between incompatible types<a class="headerlink" href="#typeerror-10-comparison-between-incompatible-types" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id100">
<h3>Python exception<a class="headerlink" href="#id100" title="Permalink to this headline">¶</a></h3>
<p>TypeError: ‘&lt;’ not supported between instances of ‘int’ and ‘str’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id101">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id101" title="Permalink to this headline">¶</a></h4>
<p>You tried to do an order comparison (&lt;)
between two incompatible types of objects:
an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>) and a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>)</p>
</div>
<div class="section" id="exception-raised-on-line-327-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 327 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-327-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">325</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">326</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">42</span>
    <span class="o">--&gt;</span><span class="mi">327</span><span class="p">:</span>         <span class="n">b</span> <span class="o">&lt;</span> <span class="n">a</span>
</pre></div>
</div>
<div class="section" id="id102">
<h5>Known identifiers<a class="headerlink" href="#id102" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="mi">42</span>
    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-11-bad-operand-type-for-unary">
<h2>TypeError - 11: bad operand type for unary +<a class="headerlink" href="#typeerror-11-bad-operand-type-for-unary" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id103">
<h3>Python exception<a class="headerlink" href="#id103" title="Permalink to this headline">¶</a></h3>
<p>TypeError: bad operand type for unary +: ‘str’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id104">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id104" title="Permalink to this headline">¶</a></h4>
<p>You tried to use the unary operator ‘+’
with the following type of object: a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>).
This operation is not defined for this type of object.</p>
</div>
<div class="section" id="exception-raised-on-line-340-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 340 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-340-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">338</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_type_error11</span><span class="p">():</span>
       <span class="mi">339</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">340</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="o">+</span><span class="s2">&quot;abc&quot;</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-11a-bad-operand-type-for-unary">
<h2>TypeError - 11a: bad operand type for unary -<a class="headerlink" href="#typeerror-11a-bad-operand-type-for-unary" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id105">
<h3>Python exception<a class="headerlink" href="#id105" title="Permalink to this headline">¶</a></h3>
<p>TypeError: bad operand type for unary -: ‘list’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id106">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id106" title="Permalink to this headline">¶</a></h4>
<p>You tried to use the unary operator ‘-‘
with the following type of object: a <code class="docutils literal notranslate"><span class="pre">list</span></code>.
This operation is not defined for this type of object.</p>
</div>
<div class="section" id="exception-raised-on-line-354-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 354 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-354-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">352</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_type_error11a</span><span class="p">():</span>
       <span class="mi">353</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">354</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="o">-</span><span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-11b-bad-operand-type-for-unary">
<h2>TypeError - 11b: bad operand type for unary ~<a class="headerlink" href="#typeerror-11b-bad-operand-type-for-unary" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id107">
<h3>Python exception<a class="headerlink" href="#id107" title="Permalink to this headline">¶</a></h3>
<p>TypeError: bad operand type for unary ~: ‘tuple’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id108">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id108" title="Permalink to this headline">¶</a></h4>
<p>You tried to use the unary operator ‘~’
with the following type of object: a <code class="docutils literal notranslate"><span class="pre">tuple</span></code>.
This operation is not defined for this type of object.</p>
</div>
<div class="section" id="exception-raised-on-line-368-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 368 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-368-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">366</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_type_error11b</span><span class="p">():</span>
       <span class="mi">367</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">368</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="o">~</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-12-object-does-not-support-item-assignment">
<h2>TypeError - 12: object does not support item assignment<a class="headerlink" href="#typeerror-12-object-does-not-support-item-assignment" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id109">
<h3>Python exception<a class="headerlink" href="#id109" title="Permalink to this headline">¶</a></h3>
<p>TypeError: ‘tuple’ object does not support item assignment</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id110">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id110" title="Permalink to this headline">¶</a></h4>
<p>In Python, some objects are known as immutable:
once defined, their value cannot be changed.
You tried change part of such an immutable object: a <code class="docutils literal notranslate"><span class="pre">tuple</span></code>,
most likely by using an indexing operation.</p>
</div>
<div class="section" id="exception-raised-on-line-383-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 383 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-383-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">381</span><span class="p">:</span>     <span class="n">a</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
       <span class="mi">382</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">383</span><span class="p">:</span>         <span class="n">a</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span> <span class="o">=</span> <span class="mi">0</span>
</pre></div>
</div>
<div class="section" id="id111">
<h5>Known identifiers<a class="headerlink" href="#id111" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-13-wrong-number-of-positional-arguments">
<h2>TypeError - 13: wrong number of positional arguments<a class="headerlink" href="#typeerror-13-wrong-number-of-positional-arguments" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id112">
<h3>Python exception<a class="headerlink" href="#id112" title="Permalink to this headline">¶</a></h3>
<p>TypeError: fn() takes 0 positional arguments but 1 was given</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id113">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id113" title="Permalink to this headline">¶</a></h4>
<p>You apparently have called the function <code class="docutils literal notranslate"><span class="pre">fn</span></code> with
1 positional argument(s) while it requires 0
such positional argument(s).</p>
</div>
<div class="section" id="exception-raised-on-line-399-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 399 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-399-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">397</span><span class="p">:</span> 
       <span class="mi">398</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">399</span><span class="p">:</span>         <span class="n">fn</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
</pre></div>
</div>
<div class="section" id="id114">
<h5>Known identifiers<a class="headerlink" href="#id114" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">fn</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">test_type_error13</span><span class="o">.&lt;</span><span class="nb">locals</span><span class="o">&gt;.</span><span class="n">fn</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-14-missing-positional-arguments">
<h2>TypeError - 14: missing positional arguments<a class="headerlink" href="#typeerror-14-missing-positional-arguments" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id115">
<h3>Python exception<a class="headerlink" href="#id115" title="Permalink to this headline">¶</a></h3>
<p>TypeError: fn() missing 2 required positional arguments: ‘b’ and ‘c’</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id116">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id116" title="Permalink to this headline">¶</a></h4>
<p>You apparently have called the function ‘fn()’ with
fewer positional arguments than it requires (2 missing).</p>
</div>
<div class="section" id="exception-raised-on-line-435-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 435 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-435-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">433</span><span class="p">:</span> 
       <span class="mi">434</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">435</span><span class="p">:</span>         <span class="n">fn</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
</pre></div>
</div>
<div class="section" id="id117">
<h5>Known identifiers<a class="headerlink" href="#id117" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">fn</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">test_type_error14</span><span class="o">.&lt;</span><span class="nb">locals</span><span class="o">&gt;.</span><span class="n">fn</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-15-tuple-object-is-not-callable">
<h2>TypeError - 15: tuple object is not callable<a class="headerlink" href="#typeerror-15-tuple-object-is-not-callable" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id118">
<h3>Python exception<a class="headerlink" href="#id118" title="Permalink to this headline">¶</a></h3>
<p>TypeError: ‘tuple’ object is not callable</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id119">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id119" title="Permalink to this headline">¶</a></h4>
<p>I suspect that you had an object of this type, a <code class="docutils literal notranslate"><span class="pre">tuple</span></code>,
followed by what looked like a tuple, ‘(…)’,
which Python took as an indication of a function call.
Perhaps you had a missing comma between two tuples.</p>
</div>
<div class="section" id="exception-raised-on-line-449-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 449 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-449-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">447</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_type_error15</span><span class="p">():</span>
       <span class="mi">448</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">449</span><span class="p">:</span>         <span class="n">_</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">)(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-15a-list-object-is-not-callable">
<h2>TypeError - 15a: list object is not callable<a class="headerlink" href="#typeerror-15a-list-object-is-not-callable" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id120">
<h3>Python exception<a class="headerlink" href="#id120" title="Permalink to this headline">¶</a></h3>
<p>TypeError: ‘list’ object is not callable</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id121">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id121" title="Permalink to this headline">¶</a></h4>
<p>I suspect that you had an object of this type, a <code class="docutils literal notranslate"><span class="pre">list</span></code>,
followed by what looked like a tuple, ‘(…)’,
which Python took as an indication of a function call.
Perhaps you had a missing comma before the tuple.</p>
</div>
<div class="section" id="exception-raised-on-line-462-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 462 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-462-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">460</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_type_error15a</span><span class="p">():</span>
       <span class="mi">461</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">462</span><span class="p">:</span>         <span class="n">_</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">](</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror-16-exception-derived-from-baseexception">
<h2>TypeError - 16: exception derived from BaseException<a class="headerlink" href="#typeerror-16-exception-derived-from-baseexception" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id122">
<h3>Python exception<a class="headerlink" href="#id122" title="Permalink to this headline">¶</a></h3>
<p>TypeError: exceptions must derive from BaseException</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by tring to do an operation not allowed on a given type of object.</p>
<div class="section" id="id123">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id123" title="Permalink to this headline">¶</a></h4>
<p>In Python 3, exceptions must be derived from BaseException.</p>
</div>
<div class="section" id="exception-raised-on-line-475-of-file-tests-except-test-type-error-py">
<h4>Exception raised on line 475 of file ‘TESTS:\except\test_type_error.py’.<a class="headerlink" href="#exception-raised-on-line-475-of-file-tests-except-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">473</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_type_error16</span><span class="p">():</span>
       <span class="mi">474</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">475</span><span class="p">:</span>         <span class="k">raise</span> <span class="s2">&quot;exception&quot;</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="unboundlocalerror">
<h2>UnboundLocalError<a class="headerlink" href="#unboundlocalerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id124">
<h3>Python exception<a class="headerlink" href="#id124" title="Permalink to this headline">¶</a></h3>
<p>UnboundLocalError: local variable ‘a’ referenced before assignment</p>
<p>In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a <code class="docutils literal notranslate"><span class="pre">global</span></code>
(or sometimes <code class="docutils literal notranslate"><span class="pre">nonlocal</span></code>) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an <code class="docutils literal notranslate"><span class="pre">UnboundLocalError</span></code>.</p>
<div class="section" id="id125">
<h4>Likely cause based on the information given by Python<a class="headerlink" href="#id125" title="Permalink to this headline">¶</a></h4>
<p>The variable that appears to cause the problem is <code class="docutils literal notranslate"><span class="pre">a</span></code>.
Perhaps the statement</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">global</span> <span class="n">a</span>
</pre></div>
</div>
<p>should have been included as the first line inside your function.</p>
</div>
<div class="section" id="execution-stopped-on-line-21-of-file-tests-except-test-unbound-local-error-py">
<h4>Execution stopped on line 21 of file ‘TESTS:\except\test_unbound_local_error.py’.<a class="headerlink" href="#execution-stopped-on-line-21-of-file-tests-except-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">19</span><span class="p">:</span> 
       <span class="mi">20</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">21</span><span class="p">:</span>         <span class="n">outer</span><span class="p">()</span>
</pre></div>
</div>
<div class="section" id="id126">
<h5>Known identifiers<a class="headerlink" href="#id126" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">outer</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">outer</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="exception-raised-on-line-12-of-file-tests-except-test-unbound-local-error-py">
<h4>Exception raised on line 12 of file ‘TESTS:\except\test_unbound_local_error.py’.<a class="headerlink" href="#exception-raised-on-line-12-of-file-tests-except-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">10</span><span class="p">:</span>     <span class="k">def</span> <span class="nf">inner</span><span class="p">():</span>
       <span class="mi">11</span><span class="p">:</span>         <span class="n">c</span> <span class="o">=</span> <span class="mi">3</span>
    <span class="o">--&gt;</span><span class="mi">12</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="n">a</span> <span class="o">+</span> <span class="n">b</span> <span class="o">+</span> <span class="n">c</span>
</pre></div>
</div>
<div class="section" id="id127">
<h5>Known identifiers<a class="headerlink" href="#id127" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">b</span><span class="p">:</span> <span class="mi">2</span>
    <span class="n">c</span><span class="p">:</span> <span class="mi">3</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="unknown-exception">
<h2>Unknown exception<a class="headerlink" href="#unknown-exception" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id128">
<h3>Python exception<a class="headerlink" href="#id128" title="Permalink to this headline">¶</a></h3>
<p>MyException: Some informative message about an unknown exception.</p>
<p>No information is known about this exception.
Please report this example to
https://github.com/aroberge/friendly-traceback/issues</p>
<div class="section" id="exception-raised-on-line-10-of-file-tests-except-test-unknown-error-py">
<h4>Exception raised on line 10 of file ‘TESTS:\except\test_unknown_error.py’.<a class="headerlink" href="#exception-raised-on-line-10-of-file-tests-except-test-unknown-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">8</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_unknown_error</span><span class="p">():</span>
        <span class="mi">9</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">10</span><span class="p">:</span>         <span class="k">raise</span> <span class="n">MyException</span><span class="p">(</span><span class="s2">&quot;Some informative message about an unknown exception.&quot;</span><span class="p">)</span>
</pre></div>
</div>
<div class="section" id="id129">
<h5>Known identifiers<a class="headerlink" href="#id129" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    global MyException: &lt;class &#39;test_unknown_error.MyException&#39;&gt;
</pre></div>
</div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="zerodivisionerror-1">
<h2>ZeroDivisionError - 1<a class="headerlink" href="#zerodivisionerror-1" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id130">
<h3>Python exception<a class="headerlink" href="#id130" title="Permalink to this headline">¶</a></h3>
<p>ZeroDivisionError: division by zero</p>
<p>A <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> occurs when you are attempting to divide
a value by zero:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">/</span> <span class="pre">0.</span></code>
It can also happen if you calculate the remainder of a division
using the modulo operator <code class="docutils literal notranslate"><span class="pre">%</span></code>:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">%</span> <span class="pre">0</span></code></p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-except-test-zero-division-error-py">
<h4>Exception raised on line 6 of file ‘TESTS:\except\test_zero_division_error.py’.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-except-test-zero-division-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_zero_division_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="zerodivisionerror-2">
<h2>ZeroDivisionError - 2<a class="headerlink" href="#zerodivisionerror-2" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id131">
<h3>Python exception<a class="headerlink" href="#id131" title="Permalink to this headline">¶</a></h3>
<p>ZeroDivisionError: integer division or modulo by zero</p>
<p>A <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> occurs when you are attempting to divide
a value by zero:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">/</span> <span class="pre">0.</span></code>
It can also happen if you calculate the remainder of a division
using the modulo operator <code class="docutils literal notranslate"><span class="pre">%</span></code>:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">%</span> <span class="pre">0</span></code></p>
<div class="section" id="exception-raised-on-line-20-of-file-tests-except-test-zero-division-error-py">
<h4>Exception raised on line 20 of file ‘TESTS:\except\test_zero_division_error.py’.<a class="headerlink" href="#exception-raised-on-line-20-of-file-tests-except-test-zero-division-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">18</span><span class="p">:</span>     <span class="n">zero</span> <span class="o">=</span> <span class="mi">0</span>
       <span class="mi">19</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">20</span><span class="p">:</span>         <span class="mi">1</span> <span class="o">%</span> <span class="n">zero</span>
</pre></div>
</div>
<div class="section" id="id132">
<h5>Known identifiers<a class="headerlink" href="#id132" title="Permalink to this headline">¶</a></h5>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">zero</span><span class="p">:</span> <span class="mi">0</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>
</div>


           </div>
           
          </div>
          <footer>
  
    <div class="rst-footer-buttons" role="navigation" aria-label="footer navigation">
      
        <a href="tracebacks_syntax_markdown.html" class="btn btn-neutral float-right" title="Syntax errors - markdown_docs format" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="compare.html" class="btn btn-neutral float-left" title="Comparison between Python versions: SyntaxErrors" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
    </div>
  

  <hr/>

  <div role="contentinfo">
    <p>
        
        &copy; Copyright 2019, André Roberge

    </p>
  </div>
    
    
    
    Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a
    
    <a href="https://github.com/rtfd/sphinx_rtd_theme">theme</a>
    
    provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  

  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script>

  
  
    
   

</body>
</html>