

<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>Friendly tracebacks - markdown_docs format &mdash; Friendly tracebacks 0.2.13a documentation</title>
  

  
  <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="_static/custom.css" type="text/css" />

  
  
  
  

  
  <!--[if lt IE 9]>
    <script src="_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
    
      <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
        <script src="_static/jquery.js"></script>
        <script src="_static/underscore.js"></script>
        <script src="_static/doctools.js"></script>
        <script src="_static/language_data.js"></script>
    
    <script type="text/javascript" src="_static/js/theme.js"></script>

    
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="Syntax errors - markdown_docs format" href="tracebacks_syntax_markdown.html" />
    <link rel="prev" title="Comparison between Python versions: SyntaxErrors" href="compare.html" /> 
</head>

<body class="wy-body-for-nav">

   
  <div class="wy-grid-for-nav">
    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
          

          
            <a href="index.html" class="icon icon-home" alt="Documentation Home"> Friendly tracebacks
          

          
          </a>

          
            
            
              <div class="version">
                0.2.13a
              </div>
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        
        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
              
            
            
              <p class="caption"><span class="caption-text">Begin here</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="usage.html">Installation and basic usage</a></li>
<li class="toctree-l1"><a class="reference internal" href="repl.html">Console basics</a></li>
<li class="toctree-l1"><a class="reference internal" href="editor.html">Using with an editor or IDE</a></li>
<li class="toctree-l1"><a class="reference internal" href="mu.html">Using with Mu</a></li>
<li class="toctree-l1"><a class="reference internal" href="thonny.html">Using with Thonny</a></li>
<li class="toctree-l1"><a class="reference internal" href="ipython.html">IPython and Jupyter notebooks</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks.html">Multiple tracebacks</a></li>
</ul>
<p class="caption"><span class="caption-text">Thoughts on design</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="design.html">Some thoughts on the design of Friendly-traceback</a></li>
<li class="toctree-l1"><a class="reference internal" href="themes.html">Themes and colours</a></li>
</ul>
<p class="caption"><span class="caption-text">Use in your project</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="api.html">Public API</a></li>
<li class="toctree-l1"><a class="reference internal" href="lies.html">Learn to lie</a></li>
<li class="toctree-l1"><a class="reference internal" href="formatter.html">Custom formatter</a></li>
<li class="toctree-l1"><a class="reference internal" href="usage_adv.html">Other details for advanced users</a></li>
<li class="toctree-l1"><a class="reference internal" href="plugins.html">Editor plugins</a></li>
</ul>
<p class="caption"><span class="caption-text">Contribute</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="suggest.html">Suggest an addition</a></li>
<li class="toctree-l1"><a class="reference internal" href="adding_exception.html">Developer: Add a new Exception case</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_error.html">Developer: Add a new SyntaxError case</a></li>
<li class="toctree-l1"><a class="reference internal" href="translation_notes.html">Notes on translations - using gettext</a></li>
</ul>
<p class="caption"><span class="caption-text">All the tracebacks!</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="known.html">Generic information about various exceptions</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.6.html">Friendly tracebacks - Python 3.6 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.6.html">SyntaxError - Python 3.6 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.7.html">Friendly tracebacks - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.7.html">SyntaxError - Python 3.7 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.8.html">Friendly tracebacks - Python 3.8 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.8.html">SyntaxError - Python 3.8 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.9.html">Friendly tracebacks - Python 3.9 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.9.html">SyntaxError - Python 3.9 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_en_3.10.html">Friendly tracebacks - Python 3.10 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_en_3.10.html">SyntaxError - Python 3.10 in English</a></li>
<li class="toctree-l1"><a class="reference internal" href="compare_exceptions.html">Comparing Exception messages between Python versions</a></li>
<li class="toctree-l1"><a class="reference internal" href="compare.html">Comparison between Python versions: SyntaxErrors</a></li>
</ul>
<p class="caption"><span class="caption-text">Markdown examples</span></p>
<ul class="current">
<li class="toctree-l1 current"><a class="current reference internal" href="#">Friendly tracebacks - markdown_docs format</a><ul>
<li class="toctree-l2"><a class="reference internal" href="#arithmeticerror">ArithmeticError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#generic">Generic</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-9-of-file-tests-runtime-test-arithmetic-error-py">Exception raised on line 9 of file TESTS:\runtime\test_arithmetic_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#attributeerror">AttributeError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#builtin-function">Builtin function</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-188-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 188 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#builtin-module-with-no-file">Builtin module with no file</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-205-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 205 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#id1">Generic</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-36-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 36 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#module-attribute-typo">Module attribute typo</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-113-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 113 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#nonetype">Nonetype</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-152-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 152 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#object-attribute-typo">Object attribute typo</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-52-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 52 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#perhaps-comma">Perhaps comma</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-171-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 171 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#shadow-stdlib-module">Shadow stdlib module</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-134-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 134 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#use-builtin">Use builtin</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-68-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 68 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#use-synonym">Use synonym</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-84-of-file-tests-runtime-test-attribute-error-py">Exception raised on line 84 of file TESTS:\runtime\test_attribute_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#filenotfounderror">FileNotFoundError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id2">Generic</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-file-not-found-error-py">Exception raised on line 6 of file TESTS:\runtime\test_file_not_found_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#importerror">ImportError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#circular-import">Circular import</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#execution-stopped-on-line-20-of-file-tests-runtime-test-import-error-py">Execution stopped on line 20 of file TESTS:\runtime\test_import_error.py.</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-2-of-file-tests-circular-b-py">Exception raised on line 2 of file TESTS:\circular_b.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#simple-import-error">Simple import error</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-import-error-py">Exception raised on line 6 of file TESTS:\runtime\test_import_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#indexerror">IndexError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#long-list">Long list</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-24-of-file-tests-runtime-test-index-error-py">Exception raised on line 24 of file TESTS:\runtime\test_index_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#short-tuple">Short tuple</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-8-of-file-tests-runtime-test-index-error-py">Exception raised on line 8 of file TESTS:\runtime\test_index_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#keyerror">KeyError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id3">Generic</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-7-of-file-tests-runtime-test-key-error-py">Exception raised on line 7 of file TESTS:\runtime\test_key_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#lookuperror">LookupError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id4">Generic</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-10-of-file-tests-runtime-test-lookup-error-py">Exception raised on line 10 of file TESTS:\runtime\test_lookup_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#modulenotfounderror">ModuleNotFoundError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#not-a-package">Not a package</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-41-of-file-tests-runtime-test-module-not-found-error-py">Exception raised on line 41 of file TESTS:\runtime\test_module_not_found_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#standard-library-module">Standard library module</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-module-not-found-error-py">Exception raised on line 6 of file TESTS:\runtime\test_module_not_found_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#nameerror">NameError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#annotated-variable">Annotated variable</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-21-of-file-tests-runtime-test-name-error-py">Exception raised on line 21 of file TESTS:\runtime\test_name_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#id5">Generic</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-name-error-py">Exception raised on line 6 of file TESTS:\runtime\test_name_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#synonym">Synonym</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-66-of-file-tests-runtime-test-name-error-py">Exception raised on line 66 of file TESTS:\runtime\test_name_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#overflowerror">OverflowError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id6">Generic</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-overflow-error-py">Exception raised on line 6 of file TESTS:\runtime\test_overflow_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#recursionerror">RecursionError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id7">Generic</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#execution-stopped-on-line-8-of-file-tests-runtime-test-recursion-error-py">Execution stopped on line 8 of file TESTS:\runtime\test_recursion_error.py.</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-recursion-error-py">Exception raised on line 6 of file TESTS:\runtime\test_recursion_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#typeerror">TypeError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#bad-type-for-unary-operator">Bad type for unary operator</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-348-of-file-tests-runtime-test-type-error-py">Exception raised on line 348 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#can-only-concatenate">Can only concatenate</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-36-of-file-tests-runtime-test-type-error-py">Exception raised on line 36 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#cannot-convert-dictionary-update-sequence">Cannot convert dictionary update sequence</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-752-of-file-tests-runtime-test-type-error-py">Exception raised on line 752 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#cannot-multiply-by-non-int">Cannot multiply by non int</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-546-of-file-tests-runtime-test-type-error-py">Exception raised on line 546 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#cannot-unpack-non-iterable-object">Cannot unpack non iterable object</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-724-of-file-tests-runtime-test-type-error-py">Exception raised on line 724 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#comparison-not-supported">Comparison not supported</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-298-of-file-tests-runtime-test-type-error-py">Exception raised on line 298 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#derive-from-baseexception">Derive from BaseException</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-489-of-file-tests-runtime-test-type-error-py">Exception raised on line 489 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#indices-must-be-integers-or-slices">Indices must be integers or slices</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-628-of-file-tests-runtime-test-type-error-py">Exception raised on line 628 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#not-an-integer">Not an integer</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-591-of-file-tests-runtime-test-type-error-py">Exception raised on line 591 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#not-callable">Not callable</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-476-of-file-tests-runtime-test-type-error-py">Exception raised on line 476 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#object-is-not-iterable">Object is not iterable</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-710-of-file-tests-runtime-test-type-error-py">Exception raised on line 710 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#object-is-not-subscriptable">Object is not subscriptable</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-696-of-file-tests-runtime-test-type-error-py">Exception raised on line 696 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#slice-indices-must-be-integers-or-none">Slice indices must be integers or None</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-642-of-file-tests-runtime-test-type-error-py">Exception raised on line 642 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#too-few-positional-argument">Too few positional argument</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-418-of-file-tests-runtime-test-type-error-py">Exception raised on line 418 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#too-many-positional-argument">Too many positional argument</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-399-of-file-tests-runtime-test-type-error-py">Exception raised on line 399 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#tuple-no-item-assignment">Tuple no item assignment</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-366-of-file-tests-runtime-test-type-error-py">Exception raised on line 366 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#unhachable-type">Unhachable type</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-659-of-file-tests-runtime-test-type-error-py">Exception raised on line 659 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#unsupported-operand-types">Unsupported operand types</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-282-of-file-tests-runtime-test-type-error-py">Exception raised on line 282 of file TESTS:\runtime\test_type_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#unboundlocalerror">UnboundLocalError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#missing-global">Missing global</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#execution-stopped-on-line-27-of-file-tests-runtime-test-unbound-local-error-py">Execution stopped on line 27 of file TESTS:\runtime\test_unbound_local_error.py.</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-9-of-file-tests-runtime-test-unbound-local-error-py">Exception raised on line 9 of file TESTS:\runtime\test_unbound_local_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#missing-nonlocal">Missing nonlocal</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#execution-stopped-on-line-48-of-file-tests-runtime-test-unbound-local-error-py">Execution stopped on line 48 of file TESTS:\runtime\test_unbound_local_error.py.</a></li>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-18-of-file-tests-runtime-test-unbound-local-error-py">Exception raised on line 18 of file TESTS:\runtime\test_unbound_local_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#unknownerror">UnknownError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#id8">Generic</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-10-of-file-tests-runtime-test-unknown-error-py">Exception raised on line 10 of file TESTS:\runtime\test_unknown_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#valueerror">ValueError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#not-enough-values-to-unpack">Not enough values to unpack</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-28-of-file-tests-runtime-test-value-error-py">Exception raised on line 28 of file TESTS:\runtime\test_value_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#too-many-values-to-unpack">Too many values to unpack</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-43-of-file-tests-runtime-test-value-error-py">Exception raised on line 43 of file TESTS:\runtime\test_value_error.py.</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="#zerodivisionerror">ZeroDivisionError</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#division-operator">Division operator</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-6-of-file-tests-runtime-test-zero-division-error-py">Exception raised on line 6 of file TESTS:\runtime\test_zero_division_error.py.</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#modulo-operator">Modulo operator</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#exception-raised-on-line-21-of-file-tests-runtime-test-zero-division-error-py">Exception raised on line 21 of file TESTS:\runtime\test_zero_division_error.py.</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_syntax_markdown.html">Syntax errors - markdown_docs format</a></li>
</ul>
<p class="caption"><span class="caption-text">En français</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="tracebacks_fr.html"> Friendly tracebacks - en Français</a></li>
<li class="toctree-l1"><a class="reference internal" href="syntax_tracebacks_fr.html"> Friendly SyntaxError tracebacks - en Français</a></li>
</ul>

            
          
        </div>
        
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="index.html">Friendly tracebacks</a>
        
      </nav>


      <div class="wy-nav-content">
        
        <div class="rst-content style-external-links">
        
          















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">
    
      <li><a href="index.html" class="icon icon-home"></a> &raquo;</li>
        
      <li>Friendly tracebacks - markdown_docs format</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
            
            <a href="_sources/tracebacks_markdown.md.txt" rel="nofollow"> View page source</a>
          
        
      </li>
    
  </ul>

  
  <div class="rst-breadcrumbs-buttons" role="navigation" aria-label="breadcrumb navigation">
      
        <a href="tracebacks_syntax_markdown.html" class="btn btn-neutral float-right" title="Syntax errors - markdown_docs format" accesskey="n">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="compare.html" class="btn btn-neutral float-left" title="Comparison between Python versions: SyntaxErrors" accesskey="p"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
  </div>
  
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <div class="section" id="friendly-tracebacks-markdown-docs-format">
<h1>Friendly tracebacks - markdown_docs format<a class="headerlink" href="#friendly-tracebacks-markdown-docs-format" title="Permalink to this headline">¶</a></h1>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>The content of this page is generated by running
trb_english_markdown.py located in the <code class="docutils literal notranslate"><span class="pre">tests/</span></code> directory.
This needs to be done explicitly, independently of updating the
documentation using Sphinx.
</p>
</div><p>Friendly-traceback version: 0.2.13a
Python version: 3.8.4</p>
<hr class="docutils" />
<div class="section" id="arithmeticerror">
<h2>ArithmeticError<a class="headerlink" href="#arithmeticerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="generic">
<h3>Generic<a class="headerlink" href="#generic" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_arithmetic_error.py&quot;</span>, line <span class="m">9</span>, in <span class="n">test_Generic</span>
    <span class="k">raise</span> <span class="ne">ArithmeticError</span><span class="p">(</span><span class="s1">&#39;error&#39;</span><span class="p">)</span>
<span class="gr">ArithmeticError</span>: <span class="n">error</span>
</pre></div>
</div>
<p><code class="docutils literal notranslate"><span class="pre">ArithmeticError</span></code> is the base class for those built-in exceptions
that are raised for various arithmetic errors.
It is unusual that you are seeing this exception;
normally, a more specific exception should have been raised.</p>
<div class="section" id="exception-raised-on-line-9-of-file-tests-runtime-test-arithmetic-error-py">
<h4>Exception raised on line 9 of file TESTS:\runtime\test_arithmetic_error.py.<a class="headerlink" href="#exception-raised-on-line-9-of-file-tests-runtime-test-arithmetic-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">7</span><span class="p">:</span>         <span class="c1"># Usually, a subclass such as ZeroDivisionError, etc., would</span>
        <span class="mi">8</span><span class="p">:</span>         <span class="c1"># likely be raised.</span>
    <span class="o">--&gt;</span> <span class="mi">9</span><span class="p">:</span>         <span class="k">raise</span> <span class="ne">ArithmeticError</span><span class="p">(</span><span class="s1">&#39;error&#39;</span><span class="p">)</span>
       <span class="mi">10</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="ne">ArithmeticError</span><span class="p">:</span> <span class="o">&lt;</span><span class="k">class</span> <span class="nc">ArithmeticError</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="attributeerror">
<h2>AttributeError<a class="headerlink" href="#attributeerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="builtin-function">
<h3>Builtin function<a class="headerlink" href="#builtin-function" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">188</span>, in <span class="n">test_Builtin_function</span>
    <span class="nb">len</span><span class="o">.</span><span class="n">text</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;builtin_function_or_method&#39; object has no attribute &#39;text&#39;</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">len(text)</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p><code class="docutils literal notranslate"><span class="pre">len</span></code> is a function. Perhaps you meant to write
<code class="docutils literal notranslate"><span class="pre">len(text)</span></code></p>
<div class="section" id="exception-raised-on-line-188-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 188 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-188-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">186</span><span class="p">:</span>     <span class="n">text</span> <span class="o">=</span> <span class="s1">&#39;Hello world!&#39;</span>
       <span class="mi">187</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">188</span><span class="p">:</span>         <span class="nb">len</span><span class="o">.</span><span class="n">text</span>
       <span class="mi">189</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">text</span><span class="p">:</span> <span class="s1">&#39;Hello world!&#39;</span>
    <span class="nb">len</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">builtin</span> <span class="n">function</span> <span class="nb">len</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="builtin-module-with-no-file">
<h3>Builtin module with no file<a class="headerlink" href="#builtin-module-with-no-file" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">205</span>, in <span class="n">test_Builtin_module_with_no_file</span>
    <span class="n">sys</span><span class="o">.</span><span class="n">foo</span>
<span class="gr">AttributeError</span>: <span class="n">module &#39;sys&#39; has no attribute &#39;foo&#39;</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>Python tells us that no object with name <code class="docutils literal notranslate"><span class="pre">foo</span></code> is
found in module <code class="docutils literal notranslate"><span class="pre">sys</span></code>.</p>
<div class="section" id="exception-raised-on-line-205-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 205 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-205-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">203</span><span class="p">:</span> 
       <span class="mi">204</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">205</span><span class="p">:</span>         <span class="n">sys</span><span class="o">.</span><span class="n">foo</span>
       <span class="mi">206</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">sys</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">module</span> <span class="n">sys</span> <span class="p">(</span><span class="n">builtin</span><span class="p">)</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="id1">
<h3>Generic<a class="headerlink" href="#id1" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">36</span>, in <span class="n">test_Generic</span>
    <span class="n">a</span><span class="o">.</span><span class="n">x</span>  <span class="c1"># Testing instance</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;A&#39; object has no attribute &#39;x&#39;</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>The object <code class="docutils literal notranslate"><span class="pre">a</span></code> has no attribute named <code class="docutils literal notranslate"><span class="pre">x</span></code>.</p>
<div class="section" id="exception-raised-on-line-36-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 36 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-36-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">34</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
       <span class="mi">35</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="n">A</span><span class="p">()</span>
    <span class="o">--&gt;</span><span class="mi">36</span><span class="p">:</span>         <span class="n">a</span><span class="o">.</span><span class="n">x</span>  <span class="c1"># Testing instance</span>
       <span class="mi">37</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">A</span> <span class="nb">object</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_attribute_error.test_Generic</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="module-attribute-typo">
<h3>Module attribute typo<a class="headerlink" href="#module-attribute-typo" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">113</span>, in <span class="n">test_Module_attribute_typo</span>
    <span class="n">math</span><span class="o">.</span><span class="n">cost</span>
<span class="gr">AttributeError</span>: <span class="n">module &#39;math&#39; has no attribute &#39;cost&#39;</span>
</pre></div>
</div>
<p>Did you mean one of the following: <code class="docutils literal notranslate"><span class="pre">cos,</span> <span class="pre">cosh,</span> <span class="pre">acos</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>Instead of writing <code class="docutils literal notranslate"><span class="pre">math.cost</span></code>, perhaps you meant to write one of
the following names which are attributes of module <code class="docutils literal notranslate"><span class="pre">math</span></code>:
<code class="docutils literal notranslate"><span class="pre">cos,</span> <span class="pre">cosh,</span> <span class="pre">acos</span></code></p>
<div class="section" id="exception-raised-on-line-113-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 113 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-113-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">111</span><span class="p">:</span> 
       <span class="mi">112</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">113</span><span class="p">:</span>         <span class="n">math</span><span class="o">.</span><span class="n">cost</span>
       <span class="mi">114</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">math</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">module</span> <span class="n">math</span> <span class="p">(</span><span class="n">builtin</span><span class="p">)</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="nonetype">
<h3>Nonetype<a class="headerlink" href="#nonetype" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">152</span>, in <span class="n">test_Nonetype</span>
    <span class="n">a</span><span class="o">.</span><span class="n">b</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;NoneType&#39; object has no attribute &#39;b&#39;</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>You are attempting to access the attribute <code class="docutils literal notranslate"><span class="pre">b</span></code>
for a variable whose value is <code class="docutils literal notranslate"><span class="pre">None</span></code>.</p>
<div class="section" id="exception-raised-on-line-152-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 152 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-152-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">150</span><span class="p">:</span>     <span class="n">a</span> <span class="o">=</span> <span class="kc">None</span>
       <span class="mi">151</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">152</span><span class="p">:</span>         <span class="n">a</span><span class="o">.</span><span class="n">b</span>
       <span class="mi">153</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="kc">None</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="object-attribute-typo">
<h3>Object attribute typo<a class="headerlink" href="#object-attribute-typo" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">52</span>, in <span class="n">test_Object_attribute_typo</span>
    <span class="n">a</span><span class="o">.</span><span class="n">appendh</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;list&#39; object has no attribute &#39;appendh&#39;</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">append</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>Perhaps you meant to write <code class="docutils literal notranslate"><span class="pre">a.append</span></code> instead of <code class="docutils literal notranslate"><span class="pre">a.appendh</span></code></p>
<div class="section" id="exception-raised-on-line-52-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 52 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-52-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">50</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
       <span class="mi">51</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">52</span><span class="p">:</span>         <span class="n">a</span><span class="o">.</span><span class="n">appendh</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
                   <span class="o">^^^^^^^^^</span>
       <span class="mi">53</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="perhaps-comma">
<h3>Perhaps comma<a class="headerlink" href="#perhaps-comma" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">171</span>, in <span class="n">test_Perhaps_comma</span>
    <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="n">abcd</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;str&#39; object has no attribute &#39;defg&#39;</span>
</pre></div>
</div>
<p>Did you mean to separate object names by a comma?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p><code class="docutils literal notranslate"><span class="pre">defg</span></code> is not an attribute of <code class="docutils literal notranslate"><span class="pre">abcd</span></code>.
However, both <code class="docutils literal notranslate"><span class="pre">abcd</span></code> and <code class="docutils literal notranslate"><span class="pre">defg</span></code> are known objects.
Perhaps you wrote a period to separate these two objects,
instead of using a comma.</p>
<div class="section" id="exception-raised-on-line-171-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 171 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-171-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">169</span><span class="p">:</span>     <span class="c1"># fmt: off</span>
       <span class="mi">170</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">171</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="n">abcd</span>
       <span class="mi">172</span><span class="p">:</span>         <span class="o">.</span><span class="n">defg</span><span class="p">]</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">abcd</span><span class="p">:</span> <span class="s1">&#39;hello&#39;</span>
    <span class="n">defg</span><span class="p">:</span> <span class="s1">&#39;world&#39;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="shadow-stdlib-module">
<h3>Shadow stdlib module<a class="headerlink" href="#shadow-stdlib-module" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">134</span>, in <span class="n">test_Shadow_stdlib_module</span>
    <span class="n">turtle</span><span class="o">.</span><span class="n">Pen</span>
<span class="gr">AttributeError</span>: <span class="n">module &#39;turtle&#39; has no attribute &#39;Pen&#39;</span>
</pre></div>
</div>
<p>Did you give your program the same name as a Python module?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>You imported a module named <code class="docutils literal notranslate"><span class="pre">turtle</span></code> from <code class="docutils literal notranslate"><span class="pre">TESTS:\turtle.py</span></code>.
There is also a module named <code class="docutils literal notranslate"><span class="pre">turtle</span></code> in Python’s standard library.
Perhaps you need to rename your module.</p>
<div class="section" id="exception-raised-on-line-134-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 134 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-134-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">132</span><span class="p">:</span> 
       <span class="mi">133</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">134</span><span class="p">:</span>         <span class="n">turtle</span><span class="o">.</span><span class="n">Pen</span>
       <span class="mi">135</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">turtle</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">module</span> <span class="n">turtle</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">TESTS</span><span class="p">:</span>\<span class="n">turtle</span><span class="o">.</span><span class="n">py</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="use-builtin">
<h3>Use builtin<a class="headerlink" href="#use-builtin" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">68</span>, in <span class="n">test_Use_builtin</span>
    <span class="n">a</span><span class="o">.</span><span class="n">length</span><span class="p">()</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;list&#39; object has no attribute &#39;length&#39;</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">len(a)</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>The object <code class="docutils literal notranslate"><span class="pre">a</span></code> has no attribute named <code class="docutils literal notranslate"><span class="pre">length</span></code>.
Perhaps you can use the Python builtin function <code class="docutils literal notranslate"><span class="pre">len</span></code> instead:
<code class="docutils literal notranslate"><span class="pre">len(a)</span></code>.</p>
<div class="section" id="exception-raised-on-line-68-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 68 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-68-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">66</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
       <span class="mi">67</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">68</span><span class="p">:</span>         <span class="n">a</span><span class="o">.</span><span class="n">length</span><span class="p">()</span>
                   <span class="o">^^^^^^^^</span>
       <span class="mi">69</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="use-synonym">
<h3>Use synonym<a class="headerlink" href="#use-synonym" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_attribute_error.py&quot;</span>, line <span class="m">84</span>, in <span class="n">test_Use_synonym</span>
    <span class="n">a</span><span class="o">.</span><span class="n">add</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
<span class="gr">AttributeError</span>: <span class="n">&#39;list&#39; object has no attribute &#39;add&#39;</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">append</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">AttributeError</span></code> occurs when the code contains something like
<code class="docutils literal notranslate"><span class="pre">object.x</span></code>
and <code class="docutils literal notranslate"><span class="pre">x</span></code> is not a method or attribute (variable) belonging to <code class="docutils literal notranslate"><span class="pre">object</span></code>.</p>
<p>The object <code class="docutils literal notranslate"><span class="pre">a</span></code> has no attribute named <code class="docutils literal notranslate"><span class="pre">add</span></code>.
However, <code class="docutils literal notranslate"><span class="pre">a</span></code> has the following attributes with similar meanings:
<code class="docutils literal notranslate"><span class="pre">append,</span> <span class="pre">extend,</span> <span class="pre">insert</span></code>.</p>
<div class="section" id="exception-raised-on-line-84-of-file-tests-runtime-test-attribute-error-py">
<h4>Exception raised on line 84 of file TESTS:\runtime\test_attribute_error.py.<a class="headerlink" href="#exception-raised-on-line-84-of-file-tests-runtime-test-attribute-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">82</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
       <span class="mi">83</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">84</span><span class="p">:</span>         <span class="n">a</span><span class="o">.</span><span class="n">add</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>
                   <span class="o">^^^^^</span>
       <span class="mi">85</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="filenotfounderror">
<h2>FileNotFoundError<a class="headerlink" href="#filenotfounderror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id2">
<h3>Generic<a class="headerlink" href="#id2" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_file_not_found_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_Generic</span>
    <span class="nb">open</span><span class="p">(</span><span class="s2">&quot;does_not_exist&quot;</span><span class="p">)</span>
<span class="gr">FileNotFoundError</span>: <span class="n">[Errno 2] No such file or directory: &#39;does_not_exist&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">FileNotFoundError</span></code> exception indicates that you
are trying to open a file that cannot be found by Python.
This could be because you misspelled the name of the file.</p>
<p>In your program, the name of the
file that cannot be found is <code class="docutils literal notranslate"><span class="pre">does_not_exist</span></code>.</p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-file-not-found-error-py">
<h4>Exception raised on line 6 of file TESTS:\runtime\test_file_not_found_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-file-not-found-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Generic</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="nb">open</span><span class="p">(</span><span class="s2">&quot;does_not_exist&quot;</span><span class="p">)</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="nb">open</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">builtin</span> <span class="n">function</span> <span class="nb">open</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="importerror">
<h2>ImportError<a class="headerlink" href="#importerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="circular-import">
<h3>Circular import<a class="headerlink" href="#circular-import" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_import_error.py&quot;</span>, line <span class="m">20</span>, in <span class="n">test_Circular_import</span>
    <span class="kn">import</span> <span class="nn">circular_a</span>
  File <span class="nb">&quot;TESTS:\circular_a.py&quot;</span>, line <span class="m">2</span>, in <span class="n">&lt;module&gt;</span>
    <span class="kn">import</span> <span class="nn">circular_b</span>
  File <span class="nb">&quot;TESTS:\circular_b.py&quot;</span>, line <span class="m">2</span>, in <span class="n">&lt;module&gt;</span>
    <span class="kn">from</span> <span class="nn">circular_a</span> <span class="kn">import</span> <span class="n">a</span>
<span class="gr">ImportError</span>: <span class="n">cannot import name &#39;a&#39; from partially initialized module &#39;circular_a&#39; (most likely due to a circular import) (C:\Users\andre\github\friendly-traceback\tests\circular_a.py)</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">ImportError</span></code> exception indicates that a certain object could not
be imported from a module or package. Most often, this is
because the name of the object is not spelled correctly.</p>
<p>The object that could not be imported is <code class="docutils literal notranslate"><span class="pre">a</span></code>.
The module or package where it was
expected to be found is <code class="docutils literal notranslate"><span class="pre">circular_a</span></code>.</p>
<p>The problem was likely caused by what is known as a ‘circular import’.
First, Python imported and started executing the code in file
‘TESTS:\runtime\test_import_error.py’.
which imports module <code class="docutils literal notranslate"><span class="pre">circular_a</span></code>.
During this process, the code in another file,
‘TESTS:\circular_b.py’
was executed. However in this last file, an attempt was made
to import the original module <code class="docutils literal notranslate"><span class="pre">circular_a</span></code>
a second time, before Python had completed the first import.</p>
<div class="section" id="execution-stopped-on-line-20-of-file-tests-runtime-test-import-error-py">
<h4>Execution stopped on line 20 of file TESTS:\runtime\test_import_error.py.<a class="headerlink" href="#execution-stopped-on-line-20-of-file-tests-runtime-test-import-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">18</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Circular_import</span><span class="p">():</span>
       <span class="mi">19</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">20</span><span class="p">:</span>         <span class="kn">import</span> <span class="nn">circular_a</span>
       <span class="mi">21</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
<div class="section" id="exception-raised-on-line-2-of-file-tests-circular-b-py">
<h4>Exception raised on line 2 of file TESTS:\circular_b.py.<a class="headerlink" href="#exception-raised-on-line-2-of-file-tests-circular-b-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">1</span><span class="p">:</span> <span class="s2">&quot;&quot;&quot;File used in for test_circular_import() in test_import_error.py&quot;&quot;&quot;</span>
    <span class="o">--&gt;</span><span class="mi">2</span><span class="p">:</span> <span class="kn">from</span> <span class="nn">circular_a</span> <span class="kn">import</span> <span class="n">a</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="simple-import-error">
<h3>Simple import error<a class="headerlink" href="#simple-import-error" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_import_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_Simple_import_error</span>
    <span class="kn">from</span> <span class="nn">math</span> <span class="kn">import</span> <span class="n">Pi</span>
<span class="gr">ImportError</span>: <span class="n">cannot import name &#39;Pi&#39; from &#39;math&#39; (unknown location)</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">pi</span></code>?</p>
<p>An <code class="docutils literal notranslate"><span class="pre">ImportError</span></code> exception indicates that a certain object could not
be imported from a module or package. Most often, this is
because the name of the object is not spelled correctly.</p>
<p>Perhaps you meant to import <code class="docutils literal notranslate"><span class="pre">pi</span></code> (from <code class="docutils literal notranslate"><span class="pre">math</span></code>) instead of <code class="docutils literal notranslate"><span class="pre">Pi</span></code></p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-import-error-py">
<h4>Exception raised on line 6 of file TESTS:\runtime\test_import_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-import-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Simple_import_error</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="kn">from</span> <span class="nn">math</span> <span class="kn">import</span> <span class="n">Pi</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="indexerror">
<h2>IndexError<a class="headerlink" href="#indexerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="long-list">
<h3>Long list<a class="headerlink" href="#long-list" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_index_error.py&quot;</span>, line <span class="m">24</span>, in <span class="n">test_Long_list</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">50</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span>
<span class="gr">IndexError</span>: <span class="n">list index out of range</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">IndexError</span></code> occurs when you are try to get an item from a list,
a tuple, or a similar object (sequence), by using an index which
does not exists; typically, this is because the index you give
is greater than the length of the sequence.</p>
<p>You have tried to get the item with index <code class="docutils literal notranslate"><span class="pre">50</span></code> of <code class="docutils literal notranslate"><span class="pre">a</span></code>,
a <code class="docutils literal notranslate"><span class="pre">list</span></code> of length <code class="docutils literal notranslate"><span class="pre">40</span></code>.</p>
<div class="section" id="exception-raised-on-line-24-of-file-tests-runtime-test-index-error-py">
<h4>Exception raised on line 24 of file TESTS:\runtime\test_index_error.py.<a class="headerlink" href="#exception-raised-on-line-24-of-file-tests-runtime-test-index-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">22</span><span class="p">:</span>     <span class="n">b</span> <span class="o">=</span> <span class="nb">tuple</span><span class="p">(</span><span class="nb">range</span><span class="p">(</span><span class="mi">50</span><span class="p">))</span>
       <span class="mi">23</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">24</span><span class="p">:</span>         <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">50</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">0</span><span class="p">])</span>
                         <span class="o">^^^^^</span>
       <span class="mi">25</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">[</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">,</span> <span class="mi">6</span><span class="p">,</span> <span class="mi">7</span><span class="p">,</span> <span class="mi">8</span><span class="p">,</span> <span class="mi">9</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="mi">12</span><span class="p">,</span> <span class="mi">13</span><span class="p">,</span> <span class="mi">14</span><span class="p">,</span> <span class="mi">15</span><span class="p">,</span> <span class="mi">16</span><span class="p">,</span> <span class="mi">17</span><span class="p">,</span> <span class="mi">18</span><span class="p">,</span> <span class="o">...</span><span class="p">]</span>
        <span class="nb">len</span><span class="p">(</span><span class="n">a</span><span class="p">):</span> <span class="mi">40</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="short-tuple">
<h3>Short tuple<a class="headerlink" href="#short-tuple" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_index_error.py&quot;</span>, line <span class="m">8</span>, in <span class="n">test_Short_tuple</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">3</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">2</span><span class="p">])</span>
<span class="gr">IndexError</span>: <span class="n">tuple index out of range</span>
</pre></div>
</div>
<p>Remember: the first item of a <code class="docutils literal notranslate"><span class="pre">tuple</span></code> is at index 0.</p>
<p>An <code class="docutils literal notranslate"><span class="pre">IndexError</span></code> occurs when you are try to get an item from a list,
a tuple, or a similar object (sequence), by using an index which
does not exists; typically, this is because the index you give
is greater than the length of the sequence.</p>
<p>You have tried to get the item with index <code class="docutils literal notranslate"><span class="pre">3</span></code> of <code class="docutils literal notranslate"><span class="pre">a</span></code>,
a <code class="docutils literal notranslate"><span class="pre">tuple</span></code> of length <code class="docutils literal notranslate"><span class="pre">3</span></code>.
The largest valid index of <code class="docutils literal notranslate"><span class="pre">a</span></code> is <code class="docutils literal notranslate"><span class="pre">2</span></code>.</p>
<div class="section" id="exception-raised-on-line-8-of-file-tests-runtime-test-index-error-py">
<h4>Exception raised on line 8 of file TESTS:\runtime\test_index_error.py.<a class="headerlink" href="#exception-raised-on-line-8-of-file-tests-runtime-test-index-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">6</span><span class="p">:</span>     <span class="n">b</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
        <span class="mi">7</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span> <span class="mi">8</span><span class="p">:</span>         <span class="nb">print</span><span class="p">(</span><span class="n">a</span><span class="p">[</span><span class="mi">3</span><span class="p">],</span> <span class="n">b</span><span class="p">[</span><span class="mi">2</span><span class="p">])</span>
                         <span class="o">^^^^</span>
        <span class="mi">9</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="keyerror">
<h2>KeyError<a class="headerlink" href="#keyerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id3">
<h3>Generic<a class="headerlink" href="#id3" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_key_error.py&quot;</span>, line <span class="m">7</span>, in <span class="n">test_Generic</span>
    <span class="n">d</span><span class="p">[</span><span class="s2">&quot;c&quot;</span><span class="p">]</span>
<span class="gr">KeyError</span>: <span class="n">&#39;c&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">KeyError</span></code> is raised when a value is not found as a
key in a Python dict.</p>
<p>In your program, the key that cannot be found is <code class="docutils literal notranslate"><span class="pre">'c'</span></code>.</p>
<div class="section" id="exception-raised-on-line-7-of-file-tests-runtime-test-key-error-py">
<h4>Exception raised on line 7 of file TESTS:\runtime\test_key_error.py.<a class="headerlink" href="#exception-raised-on-line-7-of-file-tests-runtime-test-key-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">5</span><span class="p">:</span>     <span class="n">d</span> <span class="o">=</span> <span class="p">{</span><span class="s2">&quot;a&quot;</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="s2">&quot;b&quot;</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
       <span class="mi">6</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">7</span><span class="p">:</span>         <span class="n">d</span><span class="p">[</span><span class="s2">&quot;c&quot;</span><span class="p">]</span>
       <span class="mi">8</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">d</span><span class="p">:</span> <span class="p">{</span><span class="s1">&#39;a&#39;</span><span class="p">:</span> <span class="mi">1</span><span class="p">,</span> <span class="s1">&#39;b&#39;</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="lookuperror">
<h2>LookupError<a class="headerlink" href="#lookuperror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id4">
<h3>Generic<a class="headerlink" href="#id4" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_lookup_error.py&quot;</span>, line <span class="m">10</span>, in <span class="n">test_Generic</span>
    <span class="k">raise</span> <span class="ne">LookupError</span><span class="p">(</span><span class="s2">&quot;Fake message&quot;</span><span class="p">)</span>
<span class="gr">LookupError</span>: <span class="n">Fake message</span>
</pre></div>
</div>
<p><code class="docutils literal notranslate"><span class="pre">LookupError</span></code> is the base class for the exceptions that are raised
when a key or index used on a mapping or sequence is invalid.
It can also be raised directly by codecs.lookup().</p>
<div class="section" id="exception-raised-on-line-10-of-file-tests-runtime-test-lookup-error-py">
<h4>Exception raised on line 10 of file TESTS:\runtime\test_lookup_error.py.<a class="headerlink" href="#exception-raised-on-line-10-of-file-tests-runtime-test-lookup-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">8</span><span class="p">:</span>         <span class="c1"># other than possibly codecs.lookup(), which is why we raise</span>
        <span class="mi">9</span><span class="p">:</span>         <span class="c1"># it directly here for our example.</span>
    <span class="o">--&gt;</span><span class="mi">10</span><span class="p">:</span>         <span class="k">raise</span> <span class="ne">LookupError</span><span class="p">(</span><span class="s2">&quot;Fake message&quot;</span><span class="p">)</span>
       <span class="mi">11</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="ne">LookupError</span><span class="p">:</span> <span class="o">&lt;</span><span class="k">class</span> <span class="nc">LookupError</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="modulenotfounderror">
<h2>ModuleNotFoundError<a class="headerlink" href="#modulenotfounderror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="not-a-package">
<h3>Not a package<a class="headerlink" href="#not-a-package" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_module_not_found_error.py&quot;</span>, line <span class="m">41</span>, in <span class="n">test_Not_a_package</span>
    <span class="kn">import</span> <span class="nn">os.pathh</span>
<span class="gr">ModuleNotFoundError</span>: <span class="n">No module named &#39;os.pathh&#39;; &#39;os&#39; is not a package</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">import</span> <span class="pre">os.path</span></code>?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">ModuleNotFoundError</span></code> exception indicates that you
are trying to import a module that cannot be found by Python.
This could be because you misspelled the name of the module
or because it is not installed on your computer.</p>
<p>Perhaps you meant <code class="docutils literal notranslate"><span class="pre">import</span> <span class="pre">os.path</span></code>.
<code class="docutils literal notranslate"><span class="pre">path</span></code> is a name similar to <code class="docutils literal notranslate"><span class="pre">pathh</span></code> and is a module that
can be imported from <code class="docutils literal notranslate"><span class="pre">os</span></code>.
Other objects with similar names that are part of
<code class="docutils literal notranslate"><span class="pre">os</span></code> include <code class="docutils literal notranslate"><span class="pre">fspath</span></code>.</p>
<div class="section" id="exception-raised-on-line-41-of-file-tests-runtime-test-module-not-found-error-py">
<h4>Exception raised on line 41 of file TESTS:\runtime\test_module_not_found_error.py.<a class="headerlink" href="#exception-raised-on-line-41-of-file-tests-runtime-test-module-not-found-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">39</span><span class="p">:</span> 
       <span class="mi">40</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">41</span><span class="p">:</span>         <span class="kn">import</span> <span class="nn">os.pathh</span>
       <span class="mi">42</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="standard-library-module">
<h3>Standard library module<a class="headerlink" href="#standard-library-module" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_module_not_found_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_Standard_library_module</span>
    <span class="kn">import</span> <span class="nn">Tkinter</span>
<span class="gr">ModuleNotFoundError</span>: <span class="n">No module named &#39;Tkinter&#39;</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">tkinter</span></code>?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">ModuleNotFoundError</span></code> exception indicates that you
are trying to import a module that cannot be found by Python.
This could be because you misspelled the name of the module
or because it is not installed on your computer.</p>
<p>The name of the module that could not be imported is <code class="docutils literal notranslate"><span class="pre">Tkinter</span></code>.
<code class="docutils literal notranslate"><span class="pre">tkinter</span></code> is an existing module that has a similar name.</p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-module-not-found-error-py">
<h4>Exception raised on line 6 of file TESTS:\runtime\test_module_not_found_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-module-not-found-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Standard_library_module</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="kn">import</span> <span class="nn">Tkinter</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="nameerror">
<h2>NameError<a class="headerlink" href="#nameerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="annotated-variable">
<h3>Annotated variable<a class="headerlink" href="#annotated-variable" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_name_error.py&quot;</span>, line <span class="m">21</span>, in <span class="n">test_Annotated_variable</span>
    <span class="n">y</span> <span class="o">=</span> <span class="n">x</span>
<span class="gr">NameError</span>: <span class="n">name &#39;x&#39; is not defined</span>
</pre></div>
</div>
<p>Did you use a colon instead of an equal sign?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<p>In your program, <code class="docutils literal notranslate"><span class="pre">x</span></code> is an unknown name.
A type hint found for <code class="docutils literal notranslate"><span class="pre">x</span></code> in the global scope.
Perhaps you had used a colon instead of an equal sign and written</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">x</span> <span class="p">:</span> <span class="mi">3</span>
</pre></div>
</div>
<p>instead of</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">x</span> <span class="o">=</span> <span class="mi">3</span>
</pre></div>
</div>
<div class="section" id="exception-raised-on-line-21-of-file-tests-runtime-test-name-error-py">
<h4>Exception raised on line 21 of file TESTS:\runtime\test_name_error.py.<a class="headerlink" href="#exception-raised-on-line-21-of-file-tests-runtime-test-name-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">19</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Annotated_variable</span><span class="p">():</span>
       <span class="mi">20</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">21</span><span class="p">:</span>         <span class="n">y</span> <span class="o">=</span> <span class="n">x</span>
                       <span class="o">^</span>
       <span class="mi">22</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="id5">
<h3>Generic<a class="headerlink" href="#id5" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_name_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_Generic</span>
    <span class="n">this</span> <span class="o">=</span> <span class="n">something</span>
<span class="gr">NameError</span>: <span class="n">name &#39;something&#39; is not defined</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<p>In your program, <code class="docutils literal notranslate"><span class="pre">something</span></code> is an unknown name.
I have no additional information for you.</p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-name-error-py">
<h4>Exception raised on line 6 of file TESTS:\runtime\test_name_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-name-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Generic</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="n">this</span> <span class="o">=</span> <span class="n">something</span>
                         <span class="o">^^^^^^^^^</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="synonym">
<h3>Synonym<a class="headerlink" href="#synonym" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_name_error.py&quot;</span>, line <span class="m">66</span>, in <span class="n">test_Synonym</span>
    <span class="n">cost</span>  <span class="c1"># wrote from math import * above</span>
<span class="gr">NameError</span>: <span class="n">name &#39;cost&#39; is not defined</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">cos</span></code>?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">NameError</span></code> exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.</p>
<p>In your program, <code class="docutils literal notranslate"><span class="pre">cost</span></code> is an unknown name.
Instead of writing <code class="docutils literal notranslate"><span class="pre">cost</span></code>, perhaps you meant one of the following:</p>
<ul class="simple">
<li><p>Global scope: <code class="docutils literal notranslate"><span class="pre">cos</span></code>, <code class="docutils literal notranslate"><span class="pre">cosh</span></code>, <code class="docutils literal notranslate"><span class="pre">acos</span></code></p></li>
</ul>
<div class="section" id="exception-raised-on-line-66-of-file-tests-runtime-test-name-error-py">
<h4>Exception raised on line 66 of file TESTS:\runtime\test_name_error.py.<a class="headerlink" href="#exception-raised-on-line-66-of-file-tests-runtime-test-name-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">64</span><span class="p">:</span> 
       <span class="mi">65</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">66</span><span class="p">:</span>         <span class="n">cost</span>  <span class="c1"># wrote from math import * above</span>
                   <span class="o">^^^^</span>
       <span class="mi">67</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="overflowerror">
<h2>OverflowError<a class="headerlink" href="#overflowerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id6">
<h3>Generic<a class="headerlink" href="#id6" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_overflow_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_Generic</span>
    <span class="mf">2.0</span> <span class="o">**</span> <span class="mi">1600</span>
<span class="gr">OverflowError</span>: <span class="n">(34, &#39;Result too large&#39;)</span>
</pre></div>
</div>
<p>An <code class="docutils literal notranslate"><span class="pre">OverflowError</span></code> is raised when the result of an arithmetic operation
is too large to be handled by the computer’s processor.</p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-overflow-error-py">
<h4>Exception raised on line 6 of file TESTS:\runtime\test_overflow_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-overflow-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Generic</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="mf">2.0</span> <span class="o">**</span> <span class="mi">1600</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="recursionerror">
<h2>RecursionError<a class="headerlink" href="#recursionerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id7">
<h3>Generic<a class="headerlink" href="#id7" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_recursion_error.py&quot;</span>, line <span class="m">8</span>, in <span class="n">test_Generic</span>
    <span class="n">a</span><span class="p">()</span>

<span class="x">       ... More lines not shown. ...</span>

<span class="x">    return a()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_recursion_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">a</span>
    <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_recursion_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">a</span>
    <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
<span class="gr">RecursionError</span>: <span class="n">maximum recursion depth exceeded</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">RecursionError</span></code> is raised when a function calls itself,
directly or indirectly, too many times.
It almost always indicates that you made an error in your code
and that your program would never stop.</p>
<div class="section" id="execution-stopped-on-line-8-of-file-tests-runtime-test-recursion-error-py">
<h4>Execution stopped on line 8 of file TESTS:\runtime\test_recursion_error.py.<a class="headerlink" href="#execution-stopped-on-line-8-of-file-tests-runtime-test-recursion-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">6</span><span class="p">:</span>         <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
        <span class="mi">7</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span> <span class="mi">8</span><span class="p">:</span>         <span class="n">a</span><span class="p">()</span>
        <span class="mi">9</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">a</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_Generic</span>
</pre></div>
</div>
</div>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-recursion-error-py">
<h4>Exception raised on line 6 of file TESTS:\runtime\test_recursion_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-recursion-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Generic</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">def</span> <span class="nf">a</span><span class="p">():</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="k">return</span> <span class="n">a</span><span class="p">()</span>
                         <span class="o">^^^</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">a</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_Generic</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="typeerror">
<h2>TypeError<a class="headerlink" href="#typeerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="bad-type-for-unary-operator">
<h3>Bad type for unary operator<a class="headerlink" href="#bad-type-for-unary-operator" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">348</span>, in <span class="n">test_Bad_type_for_unary_operator</span>
    <span class="n">a</span> <span class="o">=+</span> <span class="s2">&quot;def&quot;</span>
<span class="gr">TypeError</span>: <span class="n">bad operand type for unary +: &#39;str&#39;</span>
</pre></div>
</div>
<p>Perhaps you meant to write <code class="docutils literal notranslate"><span class="pre">+=</span></code> instead of <code class="docutils literal notranslate"><span class="pre">=+</span></code></p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to use the unary operator ‘+’
with the following type of object: a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>).
This operation is not defined for this type of object.</p>
<p>Perhaps you meant to write <code class="docutils literal notranslate"><span class="pre">+=</span></code> instead of <code class="docutils literal notranslate"><span class="pre">=+</span></code></p>
<div class="section" id="exception-raised-on-line-348-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 348 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-348-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">346</span><span class="p">:</span>         <span class="c1"># fmt: off</span>
       <span class="mi">347</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;abc&quot;</span>
    <span class="o">--&gt;</span><span class="mi">348</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=+</span> <span class="s2">&quot;def&quot;</span>
                       <span class="o">^^^^^^^</span>
       <span class="mi">349</span><span class="p">:</span>         <span class="c1"># fmt: on</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="can-only-concatenate">
<h3>Can only concatenate<a class="headerlink" href="#can-only-concatenate" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">36</span>, in <span class="n">test_Can_only_concatenate</span>
    <span class="n">result</span> <span class="o">=</span> <span class="n">a_tuple</span> <span class="o">+</span> <span class="n">a_list</span>
<span class="gr">TypeError</span>: <span class="n">can only concatenate tuple (not &quot;list&quot;) to tuple</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to concatenate (add) two different types of objects:
a <code class="docutils literal notranslate"><span class="pre">tuple</span></code> and a <code class="docutils literal notranslate"><span class="pre">list</span></code>.</p>
<div class="section" id="exception-raised-on-line-36-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 36 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-36-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">34</span><span class="p">:</span>         <span class="n">a_tuple</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
       <span class="mi">35</span><span class="p">:</span>         <span class="n">a_list</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
    <span class="o">--&gt;</span><span class="mi">36</span><span class="p">:</span>         <span class="n">result</span> <span class="o">=</span> <span class="n">a_tuple</span> <span class="o">+</span> <span class="n">a_list</span>
                            <span class="o">^^^^^^^^^^^^^^^^</span>
       <span class="mi">37</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a_tuple</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
    <span class="n">a_list</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="cannot-convert-dictionary-update-sequence">
<h3>Cannot convert dictionary update sequence<a class="headerlink" href="#cannot-convert-dictionary-update-sequence" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">752</span>, in <span class="n">test_Cannot_convert_dictionary_update_sequence</span>
    <span class="n">dd</span><span class="o">.</span><span class="n">update</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">])</span>
<span class="gr">TypeError</span>: <span class="n">cannot convert dictionary update sequence element #0 to a sequence</span>
</pre></div>
</div>
<p>Perhaps you need to use the <code class="docutils literal notranslate"><span class="pre">dict.fromkeys()</span></code> method.</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p><code class="docutils literal notranslate"><span class="pre">dict.update()</span></code> does not accept a sequence as an argument.
Instead of writing <code class="docutils literal notranslate"><span class="pre">dd.update([1,</span> <span class="pre">2,</span> <span class="pre">3])</span></code>
perhaps you should use the <code class="docutils literal notranslate"><span class="pre">dict.fromkeys()</span></code> method: <code class="docutils literal notranslate"><span class="pre">dd.update(</span> <span class="pre">dict.fromkeys([1,</span> <span class="pre">2,</span> <span class="pre">3])</span> <span class="pre">)</span></code>.</p>
<div class="section" id="exception-raised-on-line-752-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 752 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-752-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">750</span><span class="p">:</span>     <span class="n">dd</span> <span class="o">=</span> <span class="p">{</span><span class="s2">&quot;a&quot;</span><span class="p">:</span> <span class="s2">&quot;a&quot;</span><span class="p">}</span>
       <span class="mi">751</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">752</span><span class="p">:</span>         <span class="n">dd</span><span class="o">.</span><span class="n">update</span><span class="p">([</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">])</span>
       <span class="mi">753</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">dd</span><span class="p">:</span> <span class="p">{</span><span class="s1">&#39;a&#39;</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span><span class="p">}</span>
    <span class="n">dd</span><span class="o">.</span><span class="n">update</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">builtin</span> <span class="n">method</span> <span class="n">update</span> <span class="n">of</span> <span class="nb">dict</span> <span class="nb">object</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="cannot-multiply-by-non-int">
<h3>Cannot multiply by non int<a class="headerlink" href="#cannot-multiply-by-non-int" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">546</span>, in <span class="n">test_Cannot_multiply_by_non_int</span>
    <span class="s2">&quot;a&quot;</span> <span class="o">*</span> <span class="s2">&quot;2&quot;</span>
<span class="gr">TypeError</span>: <span class="n">can&#39;t multiply sequence by non-int of type &#39;str&#39;</span>
</pre></div>
</div>
<p>Did you forget to convert <code class="docutils literal notranslate"><span class="pre">&quot;2&quot;</span></code> into an integer?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You can only multiply sequences, such as list, tuples,
strings, etc., by integers.
Perhaps you forgot to convert <code class="docutils literal notranslate"><span class="pre">&quot;2&quot;</span></code> into an integer.</p>
<div class="section" id="exception-raised-on-line-546-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 546 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-546-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">544</span><span class="p">:</span> 
       <span class="mi">545</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">546</span><span class="p">:</span>         <span class="s2">&quot;a&quot;</span> <span class="o">*</span> <span class="s2">&quot;2&quot;</span>
       <span class="mi">547</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="cannot-unpack-non-iterable-object">
<h3>Cannot unpack non iterable object<a class="headerlink" href="#cannot-unpack-non-iterable-object" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">724</span>, in <span class="n">test_Cannot_unpack_non_iterable_object</span>
    <span class="n">a</span><span class="p">,</span> <span class="n">b</span> <span class="o">=</span> <span class="mf">42.0</span>
<span class="gr">TypeError</span>: <span class="n">cannot unpack non-iterable float object</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>Unpacking is a convenient way to assign a name,
to each item of an iterable.
An iterable is an object capable of returning its members one at a time.
Python containers (<code class="docutils literal notranslate"><span class="pre">list,</span> <span class="pre">tuple,</span> <span class="pre">dict</span></code>, etc.) are iterables,
but not objects of type <code class="docutils literal notranslate"><span class="pre">float</span></code>.</p>
<div class="section" id="exception-raised-on-line-724-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 724 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-724-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">722</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Cannot_unpack_non_iterable_object</span><span class="p">():</span>
       <span class="mi">723</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">724</span><span class="p">:</span>         <span class="n">a</span><span class="p">,</span> <span class="n">b</span> <span class="o">=</span> <span class="mf">42.0</span>
       <span class="mi">725</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="comparison-not-supported">
<h3>Comparison not supported<a class="headerlink" href="#comparison-not-supported" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">298</span>, in <span class="n">test_Comparison_not_supported</span>
    <span class="n">b</span> <span class="o">&lt;</span> <span class="n">a</span>
<span class="gr">TypeError</span>: <span class="n">&#39;&lt;&#39; not supported between instances of &#39;int&#39; and &#39;str&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to do an order comparison (&lt;)
between two incompatible types of objects:
an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>) and a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>).</p>
<div class="section" id="exception-raised-on-line-298-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 298 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-298-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">296</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">297</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">42</span>
    <span class="o">--&gt;</span><span class="mi">298</span><span class="p">:</span>         <span class="n">b</span> <span class="o">&lt;</span> <span class="n">a</span>
       <span class="mi">299</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">b</span><span class="p">:</span> <span class="mi">42</span>
    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="derive-from-baseexception">
<h3>Derive from BaseException<a class="headerlink" href="#derive-from-baseexception" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">489</span>, in <span class="n">test_Derive_from_BaseException</span>
    <span class="k">raise</span> <span class="s2">&quot;exception&quot;</span>
<span class="gr">TypeError</span>: <span class="n">exceptions must derive from BaseException</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>In Python 3, exceptions must be derived from BaseException.</p>
<div class="section" id="exception-raised-on-line-489-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 489 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-489-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">487</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Derive_from_BaseException</span><span class="p">():</span>
       <span class="mi">488</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">489</span><span class="p">:</span>         <span class="k">raise</span> <span class="s2">&quot;exception&quot;</span>
       <span class="mi">490</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="indices-must-be-integers-or-slices">
<h3>Indices must be integers or slices<a class="headerlink" href="#indices-must-be-integers-or-slices" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">628</span>, in <span class="n">test_Indices_must_be_integers_or_slices</span>
    <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">][</span><span class="s2">&quot;2&quot;</span><span class="p">]</span>
<span class="gr">TypeError</span>: <span class="n">list indices must be integers or slices, not str</span>
</pre></div>
</div>
<p>Did you forget to convert <code class="docutils literal notranslate"><span class="pre">&quot;2&quot;</span></code> into an integer?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>In the expression <code class="docutils literal notranslate"><span class="pre">[1,</span> <span class="pre">2,</span> <span class="pre">3][&quot;2&quot;]</span></code>
what is included between the square brackets, <code class="docutils literal notranslate"><span class="pre">[...]</span></code>,
must be either an integer or a slice
(<code class="docutils literal notranslate"><span class="pre">start:stop</span></code> or <code class="docutils literal notranslate"><span class="pre">start:stop:step</span></code>)
and you have used a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) instead.</p>
<p>Perhaps you forgot to convert <code class="docutils literal notranslate"><span class="pre">&quot;2&quot;</span></code> into an integer.</p>
<div class="section" id="exception-raised-on-line-628-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 628 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-628-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">626</span><span class="p">:</span> 
       <span class="mi">627</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">628</span><span class="p">:</span>         <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">][</span><span class="s2">&quot;2&quot;</span><span class="p">]</span>
       <span class="mi">629</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="not-an-integer">
<h3>Not an integer<a class="headerlink" href="#not-an-integer" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">591</span>, in <span class="n">test_Not_an_integer</span>
    <span class="nb">range</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">d</span><span class="p">)</span>
<span class="gr">TypeError</span>: <span class="n">&#39;str&#39; object cannot be interpreted as an integer</span>
</pre></div>
</div>
<p>Did you forget to convert <code class="docutils literal notranslate"><span class="pre">c,</span> <span class="pre">d</span></code> into integers?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You wrote an object of type <code class="docutils literal notranslate"><span class="pre">str</span></code> where an integer was expected.
Perhaps you forgot to convert <code class="docutils literal notranslate"><span class="pre">c,</span> <span class="pre">d</span></code> into integers.</p>
<div class="section" id="exception-raised-on-line-591-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 591 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-591-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">589</span><span class="p">:</span>     <span class="n">c</span><span class="p">,</span> <span class="n">d</span> <span class="o">=</span> <span class="s2">&quot;2&quot;</span><span class="p">,</span> <span class="s2">&quot;3&quot;</span>
       <span class="mi">590</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">591</span><span class="p">:</span>         <span class="nb">range</span><span class="p">(</span><span class="n">c</span><span class="p">,</span> <span class="n">d</span><span class="p">)</span>
       <span class="mi">592</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">c</span><span class="p">:</span> <span class="s1">&#39;2&#39;</span>
    <span class="n">d</span><span class="p">:</span> <span class="s1">&#39;3&#39;</span>
    <span class="nb">range</span><span class="p">:</span> <span class="o">&lt;</span><span class="k">class</span> <span class="nc">range</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="not-callable">
<h3>Not callable<a class="headerlink" href="#not-callable" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">476</span>, in <span class="n">test_Not_callable</span>
    <span class="n">_</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">](</span><span class="mi">3</span> <span class="o">+</span> <span class="mi">4</span><span class="p">)</span>
<span class="gr">TypeError</span>: <span class="n">&#39;list&#39; object is not callable</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">[1,</span> <span class="pre">2][3</span> <span class="pre">+</span> <span class="pre">4]</span></code>?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>Because of the surrounding parenthesis, <code class="docutils literal notranslate"><span class="pre">(3</span> <span class="pre">+</span> <span class="pre">4)</span></code>
is interpreted by Python as indicating a function call for
<code class="docutils literal notranslate"><span class="pre">[1,</span> <span class="pre">2]</span></code>, which is an object of type <code class="docutils literal notranslate"><span class="pre">list</span></code>
which cannot be called.</p>
<p>However, <code class="docutils literal notranslate"><span class="pre">[1,</span> <span class="pre">2]</span></code> is a sequence.
Perhaps you meant to use <code class="docutils literal notranslate"><span class="pre">[]</span></code> instead of <code class="docutils literal notranslate"><span class="pre">()</span></code> and write
<code class="docutils literal notranslate"><span class="pre">[1,</span> <span class="pre">2][3</span> <span class="pre">+</span> <span class="pre">4]</span></code></p>
<div class="section" id="exception-raised-on-line-476-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 476 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-476-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">474</span><span class="p">:</span> 
       <span class="mi">475</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">476</span><span class="p">:</span>         <span class="n">_</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">](</span><span class="mi">3</span> <span class="o">+</span> <span class="mi">4</span><span class="p">)</span>
                        <span class="o">^^^^^^^^^^^^^</span>
       <span class="mi">477</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="object-is-not-iterable">
<h3>Object is not iterable<a class="headerlink" href="#object-is-not-iterable" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">710</span>, in <span class="n">test_Object_is_not_iterable</span>
    <span class="nb">list</span><span class="p">(</span><span class="mi">42</span><span class="p">)</span>
<span class="gr">TypeError</span>: <span class="n">&#39;int&#39; object is not iterable</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>An iterable is an object capable of returning its members one at a time.
Python containers (<code class="docutils literal notranslate"><span class="pre">list,</span> <span class="pre">tuple,</span> <span class="pre">dict</span></code>, etc.) are iterables.
An iterable is required here.</p>
<div class="section" id="exception-raised-on-line-710-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 710 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-710-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">708</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Object_is_not_iterable</span><span class="p">():</span>
       <span class="mi">709</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">710</span><span class="p">:</span>         <span class="nb">list</span><span class="p">(</span><span class="mi">42</span><span class="p">)</span>
       <span class="mi">711</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="nb">list</span><span class="p">:</span> <span class="o">&lt;</span><span class="k">class</span> <span class="nc">list</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="object-is-not-subscriptable">
<h3>Object is not subscriptable<a class="headerlink" href="#object-is-not-subscriptable" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">696</span>, in <span class="n">test_Object_is_not_subscriptable</span>
    <span class="n">a</span> <span class="o">=</span> <span class="n">f</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span>
<span class="gr">TypeError</span>: <span class="n">&#39;function&#39; object is not subscriptable</span>
</pre></div>
</div>
<p>Did you mean <code class="docutils literal notranslate"><span class="pre">f(1)</span></code>?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>Subscriptable objects are typically containers from which
you can retrieve item using the notation <code class="docutils literal notranslate"><span class="pre">[...]</span></code>.</p>
<p>Perhaps you meant to write <code class="docutils literal notranslate"><span class="pre">f(1)</span></code>.</p>
<div class="section" id="exception-raised-on-line-696-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 696 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-696-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">694</span><span class="p">:</span> 
       <span class="mi">695</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">696</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="n">f</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span>
                        <span class="o">^^^^</span>
       <span class="mi">697</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">f</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">f</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_Object_is_not_subscriptable</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="slice-indices-must-be-integers-or-none">
<h3>Slice indices must be integers or None<a class="headerlink" href="#slice-indices-must-be-integers-or-none" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">642</span>, in <span class="n">test_Slice_indices_must_be_integers_or_None</span>
    <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">][</span><span class="mf">1.0</span><span class="p">:</span><span class="mf">2.0</span><span class="p">]</span>
<span class="gr">TypeError</span>: <span class="n">slice indices must be integers or None or have an __index__ method</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>When using a slice to extract a range of elements
from a sequence, that is something like
<code class="docutils literal notranslate"><span class="pre">[start:stop]</span></code> or <code class="docutils literal notranslate"><span class="pre">[start:stop:step]</span></code>
each of <code class="docutils literal notranslate"><span class="pre">start</span></code>, <code class="docutils literal notranslate"><span class="pre">stop</span></code>, <code class="docutils literal notranslate"><span class="pre">step</span></code> must be either an integer, <code class="docutils literal notranslate"><span class="pre">None</span></code>,
or possibly some other object having an <code class="docutils literal notranslate"><span class="pre">__index__</span></code> method.</p>
<div class="section" id="exception-raised-on-line-642-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 642 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-642-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">640</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Slice_indices_must_be_integers_or_None</span><span class="p">():</span>
       <span class="mi">641</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">642</span><span class="p">:</span>         <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">][</span><span class="mf">1.0</span><span class="p">:</span><span class="mf">2.0</span><span class="p">]</span>
       <span class="mi">643</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="too-few-positional-argument">
<h3>Too few positional argument<a class="headerlink" href="#too-few-positional-argument" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">418</span>, in <span class="n">test_Too_few_positional_argument</span>
    <span class="n">fn</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="gr">TypeError</span>: <span class="n">fn() missing 2 required positional arguments: &#39;b&#39; and &#39;c&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You apparently have called the function ‘fn()’ with
fewer positional arguments than it requires (2 missing).</p>
<div class="section" id="exception-raised-on-line-418-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 418 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-418-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">416</span><span class="p">:</span> 
       <span class="mi">417</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">418</span><span class="p">:</span>         <span class="n">fn</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
       <span class="mi">419</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">fn</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">fn</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_Too_few_positional_argument</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="too-many-positional-argument">
<h3>Too many positional argument<a class="headerlink" href="#too-many-positional-argument" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">399</span>, in <span class="n">test_Too_many_positional_argument</span>
    <span class="n">A</span><span class="p">()</span><span class="o">.</span><span class="n">f</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="gr">TypeError</span>: <span class="n">f() takes 1 positional argument but 2 were given</span>
</pre></div>
</div>
<p>Perhaps you forgot <code class="docutils literal notranslate"><span class="pre">self</span></code> when defining <code class="docutils literal notranslate"><span class="pre">f</span></code>.</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You apparently have called the function <code class="docutils literal notranslate"><span class="pre">f</span></code> with
2 positional argument(s) while it requires 1
such positional argument(s).
Perhaps you forgot <code class="docutils literal notranslate"><span class="pre">self</span></code> when defining <code class="docutils literal notranslate"><span class="pre">f</span></code>.</p>
<div class="section" id="exception-raised-on-line-399-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 399 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-399-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">397</span><span class="p">:</span> 
       <span class="mi">398</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">399</span><span class="p">:</span>         <span class="n">A</span><span class="p">()</span><span class="o">.</span><span class="n">f</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
       <span class="mi">400</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">A</span><span class="p">:</span> <span class="o">&lt;</span><span class="k">class</span> <span class="nc">A</span><span class="o">&gt;</span> <span class="kn">from</span> <span class="nn">test_type_error.test_Too_many_positional_argument</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="tuple-no-item-assignment">
<h3>Tuple no item assignment<a class="headerlink" href="#tuple-no-item-assignment" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">366</span>, in <span class="n">test_Tuple_no_item_assignment</span>
    <span class="n">a</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span> <span class="o">=</span> <span class="mi">0</span>
<span class="gr">TypeError</span>: <span class="n">&#39;tuple&#39; object does not support item assignment</span>
</pre></div>
</div>
<p>Did you mean to use a list?</p>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>In Python, some objects are known as immutable:
once defined, their value cannot be changed.
You tried change part of such an immutable object: a <code class="docutils literal notranslate"><span class="pre">tuple</span></code>,
most likely by using an indexing operation.
Perhaps you meant to use a list instead.</p>
<div class="section" id="exception-raised-on-line-366-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 366 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-366-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">364</span><span class="p">:</span>     <span class="n">a</span> <span class="o">=</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
       <span class="mi">365</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">366</span><span class="p">:</span>         <span class="n">a</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span> <span class="o">=</span> <span class="mi">0</span>
       <span class="mi">367</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">[</span><span class="mi">0</span><span class="p">]:</span> <span class="mi">1</span>
    <span class="n">a</span><span class="p">:</span> <span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="unhachable-type">
<h3>Unhachable type<a class="headerlink" href="#unhachable-type" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">659</span>, in <span class="n">test_Unhachable_type</span>
    <span class="p">{[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]:</span> <span class="mi">1</span><span class="p">}</span>
<span class="gr">TypeError</span>: <span class="n">unhashable type: &#39;list&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>Unhashable objects are objects that do not change value
once they are created. Only unhashable objects can be used
as elements of <code class="docutils literal notranslate"><span class="pre">set</span></code> or keys of <code class="docutils literal notranslate"><span class="pre">dict</span></code>.
Instead of using a <code class="docutils literal notranslate"><span class="pre">list</span></code>, consider using a <code class="docutils literal notranslate"><span class="pre">tuple</span></code>.</p>
<div class="section" id="exception-raised-on-line-659-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 659 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-659-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">657</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Unhachable_type</span><span class="p">():</span>
       <span class="mi">658</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">659</span><span class="p">:</span>         <span class="p">{[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">]:</span> <span class="mi">1</span><span class="p">}</span>
       <span class="mi">660</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="unsupported-operand-types">
<h3>Unsupported operand types<a class="headerlink" href="#unsupported-operand-types" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_type_error.py&quot;</span>, line <span class="m">282</span>, in <span class="n">test_Unsupported_operand_types</span>
    <span class="n">a</span> <span class="o">@=</span> <span class="n">b</span>
<span class="gr">TypeError</span>: <span class="n">unsupported operand type(s) for @=: &#39;str&#39; and &#39;int&#39;</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">TypeError</span></code> is usually caused by trying
to combine two incompatible types of objects,
by calling a function with the wrong type of object,
or by trying to do an operation not allowed on a given type of object.</p>
<p>You tried to use the operator &#64;=
using two incompatible types of objects:
a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) and an integer (<code class="docutils literal notranslate"><span class="pre">int</span></code>).
This operator is normally used only
for multiplication of matrices.</p>
<div class="section" id="exception-raised-on-line-282-of-file-tests-runtime-test-type-error-py">
<h4>Exception raised on line 282 of file TESTS:\runtime\test_type_error.py.<a class="headerlink" href="#exception-raised-on-line-282-of-file-tests-runtime-test-type-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">280</span><span class="p">:</span>         <span class="n">a</span> <span class="o">=</span> <span class="s2">&quot;a&quot;</span>
       <span class="mi">281</span><span class="p">:</span>         <span class="n">b</span> <span class="o">=</span> <span class="mi">2</span>
    <span class="o">--&gt;</span><span class="mi">282</span><span class="p">:</span>         <span class="n">a</span> <span class="o">@=</span> <span class="n">b</span>
       <span class="mi">283</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">a</span><span class="p">:</span> <span class="s1">&#39;a&#39;</span>
    <span class="n">b</span><span class="p">:</span> <span class="mi">2</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="unboundlocalerror">
<h2>UnboundLocalError<a class="headerlink" href="#unboundlocalerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="missing-global">
<h3>Missing global<a class="headerlink" href="#missing-global" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">27</span>, in <span class="n">test_Missing_global</span>
    <span class="n">outer_missing_global</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">11</span>, in <span class="n">outer_missing_global</span>
    <span class="n">inner</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">9</span>, in <span class="n">inner</span>
    <span class="n">spam_missing_global</span> <span class="o">+=</span> <span class="mi">1</span>
<span class="gr">UnboundLocalError</span>: <span class="n">local variable &#39;spam_missing_global&#39; referenced before assignment</span>
</pre></div>
</div>
<p>Did you forget to add <code class="docutils literal notranslate"><span class="pre">global</span> <span class="pre">spam_missing_global</span></code>?</p>
<p>In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a <code class="docutils literal notranslate"><span class="pre">global</span></code>
(or sometimes <code class="docutils literal notranslate"><span class="pre">nonlocal</span></code>) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an <code class="docutils literal notranslate"><span class="pre">UnboundLocalError</span></code>.</p>
<p>The name <code class="docutils literal notranslate"><span class="pre">spam_missing_global</span></code> exists in the global scope.
Perhaps the statement</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">global</span> <span class="n">spam_missing_global</span>
</pre></div>
</div>
<p>should have been included as the first line inside your function.</p>
<div class="section" id="execution-stopped-on-line-27-of-file-tests-runtime-test-unbound-local-error-py">
<h4>Execution stopped on line 27 of file TESTS:\runtime\test_unbound_local_error.py.<a class="headerlink" href="#execution-stopped-on-line-27-of-file-tests-runtime-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">25</span><span class="p">:</span> 
       <span class="mi">26</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">27</span><span class="p">:</span>         <span class="n">outer_missing_global</span><span class="p">()</span>
       <span class="mi">28</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">outer_missing_global</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">outer_missing_global</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
<div class="section" id="exception-raised-on-line-9-of-file-tests-runtime-test-unbound-local-error-py">
<h4>Exception raised on line 9 of file TESTS:\runtime\test_unbound_local_error.py.<a class="headerlink" href="#exception-raised-on-line-9-of-file-tests-runtime-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">7</span><span class="p">:</span> <span class="k">def</span> <span class="nf">outer_missing_global</span><span class="p">():</span>
        <span class="mi">8</span><span class="p">:</span>     <span class="k">def</span> <span class="nf">inner</span><span class="p">():</span>
    <span class="o">--&gt;</span> <span class="mi">9</span><span class="p">:</span>         <span class="n">spam_missing_global</span> <span class="o">+=</span> <span class="mi">1</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">spam_missing_global</span><span class="p">:</span> <span class="mi">1</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="missing-nonlocal">
<h3>Missing nonlocal<a class="headerlink" href="#missing-nonlocal" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">48</span>, in <span class="n">test_Missing_nonlocal</span>
    <span class="n">outer_missing_nonlocal</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">20</span>, in <span class="n">outer_missing_nonlocal</span>
    <span class="n">inner</span><span class="p">()</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unbound_local_error.py&quot;</span>, line <span class="m">18</span>, in <span class="n">inner</span>
    <span class="n">spam_missing_nonlocal</span> <span class="o">+=</span> <span class="mi">1</span>
<span class="gr">UnboundLocalError</span>: <span class="n">local variable &#39;spam_missing_nonlocal&#39; referenced before assignment</span>
</pre></div>
</div>
<p>Did you forget to add <code class="docutils literal notranslate"><span class="pre">nonlocal</span> <span class="pre">spam_missing_nonlocal</span></code>?</p>
<p>In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a <code class="docutils literal notranslate"><span class="pre">global</span></code>
(or sometimes <code class="docutils literal notranslate"><span class="pre">nonlocal</span></code>) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an <code class="docutils literal notranslate"><span class="pre">UnboundLocalError</span></code>.</p>
<p>The name <code class="docutils literal notranslate"><span class="pre">spam_missing_nonlocal</span></code> exists in the nonlocal scope.
Perhaps the statement</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">nonlocal</span> <span class="n">spam_missing_nonlocal</span>
</pre></div>
</div>
<p>should have been included as the first line inside your function.</p>
<div class="section" id="execution-stopped-on-line-48-of-file-tests-runtime-test-unbound-local-error-py">
<h4>Execution stopped on line 48 of file TESTS:\runtime\test_unbound_local_error.py.<a class="headerlink" href="#execution-stopped-on-line-48-of-file-tests-runtime-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">46</span><span class="p">:</span> 
       <span class="mi">47</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">48</span><span class="p">:</span>         <span class="n">outer_missing_nonlocal</span><span class="p">()</span>
       <span class="mi">49</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">outer_missing_nonlocal</span><span class="p">:</span> <span class="o">&lt;</span><span class="n">function</span> <span class="n">outer_missing_nonlocal</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
<div class="section" id="exception-raised-on-line-18-of-file-tests-runtime-test-unbound-local-error-py">
<h4>Exception raised on line 18 of file TESTS:\runtime\test_unbound_local_error.py.<a class="headerlink" href="#exception-raised-on-line-18-of-file-tests-runtime-test-unbound-local-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">16</span><span class="p">:</span> 
       <span class="mi">17</span><span class="p">:</span>     <span class="k">def</span> <span class="nf">inner</span><span class="p">():</span>
    <span class="o">--&gt;</span><span class="mi">18</span><span class="p">:</span>         <span class="n">spam_missing_nonlocal</span> <span class="o">+=</span> <span class="mi">1</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="unknownerror">
<h2>UnknownError<a class="headerlink" href="#unknownerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="id8">
<h3>Generic<a class="headerlink" href="#id8" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_unknown_error.py&quot;</span>, line <span class="m">10</span>, in <span class="n">test_Generic</span>
    <span class="k">raise</span> <span class="n">MyException</span><span class="p">(</span><span class="s2">&quot;Some informative message about an unknown exception.&quot;</span><span class="p">)</span>
<span class="gr">MyException</span>: <span class="n">Some informative message about an unknown exception.</span>
</pre></div>
</div>
<p>No information is available about this exception.</p>
<div class="section" id="exception-raised-on-line-10-of-file-tests-runtime-test-unknown-error-py">
<h4>Exception raised on line 10 of file TESTS:\runtime\test_unknown_error.py.<a class="headerlink" href="#exception-raised-on-line-10-of-file-tests-runtime-test-unknown-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>        <span class="mi">8</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Generic</span><span class="p">():</span>
        <span class="mi">9</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">10</span><span class="p">:</span>         <span class="k">raise</span> <span class="n">MyException</span><span class="p">(</span><span class="s2">&quot;Some informative message about an unknown exception.&quot;</span><span class="p">)</span>
       <span class="mi">11</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="k">global</span> <span class="n">MyException</span><span class="p">:</span> <span class="o">&lt;</span><span class="k">class</span> <span class="nc">test_unknown_error</span><span class="o">.</span><span class="n">MyException</span><span class="o">&gt;</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="valueerror">
<h2>ValueError<a class="headerlink" href="#valueerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="not-enough-values-to-unpack">
<h3>Not enough values to unpack<a class="headerlink" href="#not-enough-values-to-unpack" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_value_error.py&quot;</span>, line <span class="m">28</span>, in <span class="n">test_Not_enough_values_to_unpack</span>
    <span class="n">a</span><span class="p">,</span> <span class="n">b</span><span class="p">,</span> <span class="n">c</span> <span class="o">=</span> <span class="n">d</span>
<span class="gr">ValueError</span>: <span class="n">not enough values to unpack (expected 3, got 2)</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">ValueError</span></code> indicates that a function or an operation
received an argument of the right type, but an inappropriate value.</p>
<p>Unpacking is a convenient way to assign a name,
to each item of an iterable.
In this instance, there are more names (3)
than the length of the iterable, a string (<code class="docutils literal notranslate"><span class="pre">str</span></code>) of length 2.</p>
<div class="section" id="exception-raised-on-line-28-of-file-tests-runtime-test-value-error-py">
<h4>Exception raised on line 28 of file TESTS:\runtime\test_value_error.py.<a class="headerlink" href="#exception-raised-on-line-28-of-file-tests-runtime-test-value-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">26</span><span class="p">:</span>     <span class="n">d</span> <span class="o">=</span> <span class="s2">&quot;ab&quot;</span>
       <span class="mi">27</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">28</span><span class="p">:</span>         <span class="n">a</span><span class="p">,</span> <span class="n">b</span><span class="p">,</span> <span class="n">c</span> <span class="o">=</span> <span class="n">d</span>
       <span class="mi">29</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">d</span><span class="p">:</span> <span class="s1">&#39;ab&#39;</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="too-many-values-to-unpack">
<h3>Too many values to unpack<a class="headerlink" href="#too-many-values-to-unpack" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_value_error.py&quot;</span>, line <span class="m">43</span>, in <span class="n">test_Too_many_values_to_unpack</span>
    <span class="n">a</span><span class="p">,</span> <span class="n">b</span> <span class="o">=</span> <span class="n">c</span>
<span class="gr">ValueError</span>: <span class="n">too many values to unpack (expected 2)</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">ValueError</span></code> indicates that a function or an operation
received an argument of the right type, but an inappropriate value.</p>
<p>Unpacking is a convenient way to assign a name,
to each item of an iterable.
In this instance, there are fewer names (2)
than the length of the iterable, a <code class="docutils literal notranslate"><span class="pre">list</span></code> of length 3.</p>
<div class="section" id="exception-raised-on-line-43-of-file-tests-runtime-test-value-error-py">
<h4>Exception raised on line 43 of file TESTS:\runtime\test_value_error.py.<a class="headerlink" href="#exception-raised-on-line-43-of-file-tests-runtime-test-value-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">41</span><span class="p">:</span>     <span class="n">c</span> <span class="o">=</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
       <span class="mi">42</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">43</span><span class="p">:</span>         <span class="n">a</span><span class="p">,</span> <span class="n">b</span> <span class="o">=</span> <span class="n">c</span>
       <span class="mi">44</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">c</span><span class="p">:</span> <span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">]</span>
</pre></div>
</div>
</div>
</div>
</div>
<hr class="docutils" />
<div class="section" id="zerodivisionerror">
<h2>ZeroDivisionError<a class="headerlink" href="#zerodivisionerror" title="Permalink to this headline">¶</a></h2>
<div class="section" id="division-operator">
<h3>Division operator<a class="headerlink" href="#division-operator" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_zero_division_error.py&quot;</span>, line <span class="m">6</span>, in <span class="n">test_Division_operator</span>
    <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>
<span class="gr">ZeroDivisionError</span>: <span class="n">division by zero</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> occurs when you are attempting to divide
a value by zero:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">/</span> <span class="pre">0.</span></code>
It can also happen if you calculate the remainder of a division
using the modulo operator <code class="docutils literal notranslate"><span class="pre">%</span></code>:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">%</span> <span class="pre">0</span></code></p>
<div class="section" id="exception-raised-on-line-6-of-file-tests-runtime-test-zero-division-error-py">
<h4>Exception raised on line 6 of file TESTS:\runtime\test_zero_division_error.py.<a class="headerlink" href="#exception-raised-on-line-6-of-file-tests-runtime-test-zero-division-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">4</span><span class="p">:</span> <span class="k">def</span> <span class="nf">test_Division_operator</span><span class="p">():</span>
       <span class="mi">5</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">6</span><span class="p">:</span>         <span class="mi">1</span> <span class="o">/</span> <span class="mi">0</span>
       <span class="mi">7</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
</div>
</div>
<div class="section" id="modulo-operator">
<h3>Modulo operator<a class="headerlink" href="#modulo-operator" title="Permalink to this headline">¶</a></h3>
<div class="highlight-pytb notranslate"><div class="highlight"><pre><span></span><span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">&quot;TESTS:\runtime\test_zero_division_error.py&quot;</span>, line <span class="m">21</span>, in <span class="n">test_Modulo_operator</span>
    <span class="mi">1</span> <span class="o">%</span> <span class="n">zero</span>
<span class="gr">ZeroDivisionError</span>: <span class="n">integer division or modulo by zero</span>
</pre></div>
</div>
<p>A <code class="docutils literal notranslate"><span class="pre">ZeroDivisionError</span></code> occurs when you are attempting to divide
a value by zero:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">/</span> <span class="pre">0.</span></code>
It can also happen if you calculate the remainder of a division
using the modulo operator <code class="docutils literal notranslate"><span class="pre">%</span></code>:
<code class="docutils literal notranslate"><span class="pre">result</span> <span class="pre">=</span> <span class="pre">my_variable</span> <span class="pre">%</span> <span class="pre">0</span></code></p>
<div class="section" id="exception-raised-on-line-21-of-file-tests-runtime-test-zero-division-error-py">
<h4>Exception raised on line 21 of file TESTS:\runtime\test_zero_division_error.py.<a class="headerlink" href="#exception-raised-on-line-21-of-file-tests-runtime-test-zero-division-error-py" title="Permalink to this headline">¶</a></h4>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>       <span class="mi">19</span><span class="p">:</span>     <span class="n">zero</span> <span class="o">=</span> <span class="mi">0</span>
       <span class="mi">20</span><span class="p">:</span>     <span class="k">try</span><span class="p">:</span>
    <span class="o">--&gt;</span><span class="mi">21</span><span class="p">:</span>         <span class="mi">1</span> <span class="o">%</span> <span class="n">zero</span>
       <span class="mi">22</span><span class="p">:</span>     <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span>    <span class="n">zero</span><span class="p">:</span> <span class="mi">0</span>
</pre></div>
</div>
</div>
</div>
</div>
</div>


           </div>
           
          </div>
          <footer>
  
    <div class="rst-footer-buttons" role="navigation" aria-label="footer navigation">
      
        <a href="tracebacks_syntax_markdown.html" class="btn btn-neutral float-right" title="Syntax errors - markdown_docs format" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right"></span></a>
      
      
        <a href="compare.html" class="btn btn-neutral float-left" title="Comparison between Python versions: SyntaxErrors" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      
    </div>
  

  <hr/>

  <div role="contentinfo">
    <p>
        
        &copy; Copyright 2019, André Roberge

    </p>
  </div>
    
    
    
    Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a
    
    <a href="https://github.com/rtfd/sphinx_rtd_theme">theme</a>
    
    provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  

  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script>

  
  
    
   

</body>
</html>